### ISSUE TITLE
Check Wheeler's clang env settings for effects on ASAN

### ISSUE THREAD

**Issue by mar-celine** [sxs-collaboration/spectre#1023]
# Bug reports:

I am currently unable to reproduce the same asan errors reported in issue #1018 on wheeler,
(clang version 5.0.1) but I am able to reproduce it on my local machine (clang version 4.0.1-6)

### Current behavior:
All tests give the same asan error message:

```==28566==ERROR: AddressSanitizer failed to allocate 0xdfff0001000 (15392894357504) bytes at address 2008fff7000 (errno: 12)```

### Environment:

CMake Version: 3.9.4
SpECTRE Version: 0.0.0
SpECTRE branch: develop2
SpECTRE hash: 5d609e1b5379e93d37b56616029b594c55194180
Hostname: wheeler.caltech.edu
Host system: Linux-3.10.0-327.36.3.el7.x86_64
Host system version: 3.10.0-327.36.3.el7.x86_64
Host system processor: x86_64
CMAKE_CXX_FLAGS:
CMAKE_CXX_LINK_FLAGS:
CMAKE_CXX_FLAGS_DEBUG: -g
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS:
CMAKE_C_LINK_FLAGS:
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS:
CMAKE_Fortran_LINK_FLAGS:
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS:
CMAKE_BUILD_TYPE: Release
CMAKE_CXX_COMPILER: /usr/local/llvm/5.0.1/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 5.0.1
CMAKE_C_COMPILER: /usr/local/llvm/5.0.1/bin/clang
CMAKE_C_COMPILER_VERSION: 5.0.1
CMAKE_Fortran_COMPILER: /usr/local/gcc/7.3.0/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 7.3.0
Python Version: 2.7.12
Charm Version:  6.8.0
BLAS_LIBRARIES:  /usr/local/openblas/0.2.18/lib/libopenblas.so
Blaze Version:  3.2
Boost Version:  1.65.1
Catch Version:  2.1.2
GSL Version:  1.15
HDF5 Version:  1.8.17
jemalloc Version:  5.0.1
LIBXSMM Version:  1.8.1
LAPACK_LIBRARIES:  /usr/local/openblas/0.2.18/lib/libopenblas.so;/usr/local/openblas/0.2.18/lib/libopenblas.so
NumPy Version:  1.13.3

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by kidder** [comment]
Someone (@gsb76 ) should see if this still happens

**Comment by nilsdeppe** [comment]
This issue is explained in https://github.com/sxs-collaboration/WelcomeToSXS/wiki/Wheeler#address-sanitizer
