### ISSUE TITLE
GCC  debug builds randomly fail on Travis but nowhere else

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1031]
# Bug reports:

### Expected behavior:

Travis passes more often than it does

### Current behavior:

It doesn't.

It might be that the caches between the GCC6 and GCC7 builds are being mixed

**Comment by kidder** [comment]
Have tried separating the builds in the matrix.  Have tried building in different stages.
This is more suggestive of the caches not mixing

**Comment by kidder** [comment]
Most of the time there are just segfaults; occasionally there are approx failures that cannot be reproduced with the given seed.  In these cases, check_with_random_values generates on Travis the correct result for python, but the c++ many times generates a length-5 DataVector where the last entry is correct, but the first four are garbage.  Usually the garbage is a very small double, but in sporadic cases it give things like 15.5 or other simple doubles.   In these sporadic cases , there are sometimes two failures with different seeds which produce the same garbage values for both seeds.

**Comment by kidder** [comment]
The following tests are the ones that usually segfault:
The following tests FAILED:
	  2 - InputFiles.Burgers.Step.yaml.execute (OTHER_FAULT)
	  8 - InputFiles.GrMhd.BlastWave.yaml.execute (SEGFAULT)
	 10 - InputFiles.GrMhd.GrMhd.yaml.execute (OTHER_FAULT)
	 16 - InputFiles.Poisson.Input3D.yaml.execute (SEGFAULT)
	 18 - InputFiles.ScalarWave.Input1DPeriodic.yaml.execute (SEGFAULT)
	 20 - InputFiles.ScalarWave.Input2DPeriodic.yaml.execute (SEGFAULT)
	 22 - InputFiles.ScalarWave.Input3DPeriodic.yaml.execute (OTHER_FAULT)
	 42 - Unit.ApparentHorizons.FastFlowSchwarzschild (SEGFAULT)
	 43 - Unit.ApparentHorizons.FastFlowKerr (SEGFAULT)
	 44 - Unit.ApparentHorizons.JacobiKerr (SEGFAULT)
	 45 - Unit.ApparentHorizons.CurvatureKerr (SEGFAULT)
	 46 - Unit.ApparentHorizons.FastFlowMisc (SEGFAULT)
	 52 - Unit.ApparentHorizons.StrahlkorperGr.Expansion (SEGFAULT)
	 54 - Unit.ApparentHorizons.StrahlkorperGr.RicciScalar (SEGFAULT)
	 55 - Unit.ApparentHorizons.StrahlkorperGr.AreaElement (SEGFAULT)
	 56 - Unit.ApparentHorizons.StrahlkorperGr.SurfaceInteralOfScalar (SEGFAULT)
	 57 - Unit.ApparentHorizons.StrahlkorperGr.SpinFunction (SEGFAULT)
	 58 - Unit.ApparentHorizons.StrahlkorperGr.DimensionfulSpinMagnitude (SEGFAULT)
	 59 - Unit.ApparentHorizons.StrahlkorperGr.SpinVector (SEGFAULT)
	441 - Unit.Evolution.Systems.GeneralizedHarmonic.GaugeConstraint (SEGFAULT)
	442 - Unit.Evolution.Systems.GeneralizedHarmonic.TwoIndexConstraint (SEGFAULT)
	443 - Unit.Evolution.Systems.GeneralizedHarmonic.FourIndexConstraint (SEGFAULT)
	455 - Unit.Evolution.Systems.NewtonianEuler.ConservativeFromPrimitive (OTHER_FAULT)
	685 - Unit.PointwiseFunctions.AnalyticData.GrMhd.BondiHoyle (SEGFAULT)
	692 - Unit.PointwiseFunctions.AnalyticData.GrMhd.CylindricalBlastWave (SEGFAULT)
	699 - Unit.PointwiseFunctions.AnalyticSolutions.Gr.KerrSchild (SEGFAULT)
	710 - Unit.PointwiseFunctions.AnalyticSolutions.NewtEuler.Vortex (OTHER_FAULT)
	719 - Unit.PointwiseFunctions.AnalyticSolutions.RelEuler.FMDisk (SEGFAULT)
	728 - Unit.PointwiseFunctions.GeneralRelativity.GhQuantities (SEGFAULT)
	729 - Unit.PointwiseFunctions.GeneralRelativity.SpacetimeDecomp (SEGFAULT)
	764 - Unit.Pypp.CheckWithPython (OTHER_FAULT)

**Comment by kidder** [comment]
I have a minimal test case that still segfaults, running a single test.  From experimentation it seems that the segfault is occuring inside gr::Solutions::KerrSchild::variables.  If this is true, this would explain many (but not all) of the segfaulting tests above.  Here are some possible things to test:

- [x] turn off blaze vectorization (works in minimal test case, trying full build in #1354)
- [ ] try to print backtraces (either check the log or enable them)
- [ ] try ASAN
- [ ] check that we are not targeting a specific architecture 
- [ ] think about what is different between debug and release builds
    - compiler flags
    - default initialization of variables (nans for debug, nothing for release)
    - libxsmm is disabled in debug mode for dgemm
- [ ] valgrind (and other checks)
- [ ] try running test without catch
- [ ] change the blaze version on travis
- [ ] try doing everything in one build stage
- [ ] try replacing expression templates with explicit loops in KS::variables

**Comment by kidder** [comment]
So far #1354 seems to have solved the problem.  I will leave the issue open for a bit longer, but do not plan to spend any more time on tracking down why this fix worked
