### ISSUE TITLE
Docs for running tests locally should say you don't need to compile without precompiled headers to use IWYU

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#1037]
# Bug reports:

### Expected behavior:

file:///Users/geoffrey/Codes/spectre/spectre/ToMac/docs/html/travis_guide.html

correctly says that you need to make and configure a build directory with precompiled headers disabled in order to locally run include what you use. The docs should clarify that you don't actually have to compile to use include what you use.

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/LibraryVersions.txt` or
add its contents here.

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
We no longer use IWYU
