### ISSUE TITLE
Option to limit the initial data

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#1063]
### Feature Request

We should support applying the limiter to the initial data. This is not always necessary, because the initial data should not contain spurious oscillations, but can sometimes be helpful.

This issue is to remind us to revisit this feature after we have per-phase action lists.

**Comment by fmahebert** [comment]
@nilsdeppe Do the recently-merged phase-dependent action lists permit communicating limiter data, then applying the limiter, as part of the initialization phase? I'm unsure if once can make calls across parallel components within the initialization phase...

**Comment by nilsdeppe** [comment]
You can do communication during any phase that you want :) So yes, that seems like the appropriate place to limit. If you look at the split up initialization https://github.com/nilsdeppe/spectre/tree/split_initialization then it should be as easy as adding the limiter actions to the initialization phase.

**Comment by fmahebert** [comment]
Awesome! Then once the new initialization is merged, I think this issue will be resolved.

Adding the two actions `Limiters::Actions::SendData` and `Limiters::Actions::Limit` to the initialization action list should produce the desired functionality. These actions will have to come after evaluation of initial data, of course.

**Comment by nilsdeppe** [comment]
Yep, that's all it should be! :)

**Comment by fmahebert** [comment]
This was resolved by the PDALs (phase-dependent action lists) change last year, which made it possible to invoke more general actions (incl. a call to the limiter) in the initialization phase of an evolution.
