### ISSUE TITLE
No way to prevent compiler flag overriding

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#108]
It seems that our build system will always either append flags to enable assertions or append flags to enable optimizations, and these flags are placed at the end of the compiler invocation so they cannot be overridden.  This makes trying to debug compiler-flag-related issues really annoying, since you can't control the compiler flags.

The internet suggests setting neither Debug nor Release as the build type to do this, but our system checks for that and dies if you do it.

**Comment by kidder** [comment]
[would this be useful?](https://cmake.org/Wiki/CMake_FAQ#How_can_I_extend_the_build_modes_with_a_custom_made_one_.3F)

**Comment by wthrowe** [comment]
My suspicion is that we just need to add a fifth value to our list of acceptable strings, but I don't actually know if there's more to it than that.  Maybe we have to define the value like in your link.  I notice that code snippet references a "None" build type, which seems plausibly what I want, but I can't find any documentation of that.
