### ISSUE TITLE
Git constraints easy to accidentally circumvent

### ISSUE THREAD

**Issue by moxcodes** [sxs-collaboration/spectre#1085]
# Bug reports:
 There are a number of automatic tests run on git commits from `.git/hooks/pre-commit`, which runs `tools/FileTestDefs.sh`, which confirm basic commit integrity (e.g. no lines above 80 characters, use of `Requires` instead of `enable_if`, no trailing whitespace, etc).

### Expected behavior:

It is impossible, or at least very difficult to commit changes which fail the pre-commit checks.

### Current behavior:

As the pre-commit checks examine only the current state of the files, rather than the state which has been staged, it is possible for the following workflow to violate the constraints:
1. faulty commit staged with `git add`
2. `git commit`  fails
3. files fixed, but additional add command forgotten
4. `git commit` succeeds, and commits original faulty files staged

# Feature request:

### Desired feature:

This can probably be fixed easily enough by just re-adding all staged files prior to the checks. I cannot think of any cases where that would disrupt desired behavior.

**Comment by wthrowe** [comment]
That change would break the `git add -p` workflow.  But yes, the fact that these check the working tree rather than the staged files is annoying.
