### ISSUE TITLE
Codify code review procedures

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#1108]
We had a discussion of this on a telecon a while back.  @geoffrey4444, I think you said you were writing something up?

**Comment by geoffrey4444** [comment]
I was going to write something up after a consensus was reached on what the policy should be, but I don't think a consensus was reached before I fell out of the loop. My apologies! I'm still happy to draft something if you could point me to any notes or minutes containing the points we decided on.

**Comment by wthrowe** [comment]
As far as I know that meeting is the most recent discussion.  I pinged you because I thought you were writing up the notes.  Sounds like I'm misremembering, so don't worry about it.

**Comment by kidder** [comment]
PR #1273
