### ISSUE TITLE
Should test_move_semantics take by value?

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#111]
It would avoid the issue that its argument is moved out of but this is not obvious (as caused issues in pull request #82), but it would mean that some of the static_asserts in it become not-useful since you already need to do a move to call the function.

**Comment by nilsdeppe** [comment]
I don't immediately see a reason not to. Does it make them redundant in the case where you call test_move_semantics as `test_move_semantics(A{pars...}, A{pars...})`? I'm not sure what exactly the standard allows compilers to require in that particular case.

**Comment by wthrowe** [comment]
Experimentally, gcc wants a move constructor there.  As another question, though, do we want to check that the constructor is nothrow, since that would be stricter than what is required to call the function?

**Comment by nilsdeppe** [comment]
Okay, well experimentally is what matters. I think we should check for `nothrow` since this is a general assumption we do work under

**Comment by kidder** [comment]
decided to take first argument by rvalue reference; addressed by PR #120
