### ISSUE TITLE
Resolve issues with PR #1074 (Bondi-Hoyle Accretion)

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#1124]
# Bug reports:

We pushed some discussion from PR #1074. Specifically:

  * Some of us think KerrSchildCoords should receive mass and dimensionless spin, for consistency with elsewhere in spectre and to avoid subtle bugs by passing the wrong spin. Others disagree. We'd like to discuss and resolve this point.
  * The test for KerrSchildCoords should test an analytic solution, not just fuzzy testing.

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/LibraryVersions.txt` or
add its contents here.

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by hrueter** [comment]
What were the arguments against passing in mass and dimensionless spin to the constructor?

**Comment by kidder** [comment]
This was addressed in #1074
