### ISSUE TITLE
serialize_and_deserialize should do the test or have a wrapper that does

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#113]
It's causing confusion, since it doesn't behave like the other helpers.  Serialization is a copy operation, so by our guidelines any concrete classes that support it should have equality defined.

**Comment by nilsdeppe** [comment]
I think which approach to take depends on what we need to do for testing serialization of abstract base classes. I'm happy with either a wrapper or change it to take by value.
