### ISSUE TITLE
tools/GenerateXdmf.py hangs when run with python2 on moderately small (3MB) H5 file

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#1149]
# Bug reports:

For even moderately large hdf5 files, I'm unable to use the supplied script to visualize the data in ParaView.

To reproduce, run `EvolveValenciaDivClean` using `tests/InputFiles/GrMhd/EvolveValenciaDivClean/GrMhd.yaml`, modifying the input file so the last two lines read

~~~~
ObserveNSlabs: 1
ObserveAtT0: true
~~~~

Then, run the executable with the following options:
~~~~
#Case 0:
InitialRefinement: [0, 0, 0]
InitialGridPoints: [2, 2, 2]

#Case 1:
InitialRefinement: [1, 1, 1]
InitialGridPoints: [2, 2, 2]

#Case 2: 
InitialRefinement: [2, 2, 2]
InitialGridPoints: [2, 2, 2]
~~~~

For each case, run `date; ../../tools/GenerateXdmf.py --output GrMhd --file-prefix GrMhd; date | tee GenerateXdmf.log` to generate an xmf file for ParaView.

### Expected behavior:

The file gets generated in each case.

### Current behavior:

Case 0: `GrMhd0.h5` is 224K, xmf generated in less than 1 second
Case 1: `GrMhd0.h5` is 396K, xmf generated in 10 seconds
Case 2: `GrMhd0.h5` is 2.8M, script hangs for at least 720 seconds

### Environment:

wheeler, develop branch of spectre.

~~~~
CMake Version: 3.9.4
SpECTRE Version: 0.0.0
SpECTRE branch: develop
SpECTRE hash: 02973b31d723c0ea8c83a818365d7504f491eb75
Hostname: wheeler.caltech.edu
Host system: Linux-3.10.0-327.36.3.el7.x86_64
Host system version: 3.10.0-327.36.3.el7.x86_64
Host system processor: x86_64
CMAKE_CXX_FLAGS:  -fPIC
CMAKE_CXX_LINK_FLAGS: 
CMAKE_CXX_FLAGS_DEBUG: -g
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS:  -fPIC
CMAKE_C_LINK_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_LINK_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Release
CMAKE_CXX_COMPILER: /usr/local/llvm/5.0.1/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 5.0.1
CMAKE_C_COMPILER: /usr/local/llvm/5.0.1/bin/clang
CMAKE_C_COMPILER_VERSION: 5.0.1
CMAKE_Fortran_COMPILER: /usr/local/gcc/7.3.0/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 7.3.0
Python Version: 2.7.12
Charm Version:  6.8.0
BLAS_LIBRARIES:  /usr/local/openblas/0.2.18/lib/libopenblas.so
Blaze Version:  3.2
Boost Version:  1.65.1
Catch Version:  2.1.2
GSL Version:  1.15
HDF5 Version:  1.8.17
jemalloc Version:  5.0.1
LIBXSMM Version:  1.8.1
LAPACK_LIBRARIES:  /usr/local/openblas/0.2.18/lib/libopenblas.so;/usr/local/openblas/0.2.18/lib/libopenblas.so
NumPy Version:  1.13.3
SciPy Version:  1.0.0
~~~~

# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
I just successfully did this on 8.4GB of volume data from 6 nodes.

**Comment by nilsdeppe** [comment]
Are you dumping the data inside the docker container or out? Visualizing inside or out? This sounds like a Mac+Docker problem where syncing data between macOS and Docker is slow.

**Comment by geoffrey4444** [comment]
I ran the steps above on wheeler. If you run them on wheeler, how long does the script take to finish?

**Comment by geoffrey4444** [comment]
How long did the 8.4GB conversion take? Where did you do it?

**Comment by nilsdeppe** [comment]
Maybe 10-20 seconds on my Linux laptop.

**Comment by geoffrey4444** [comment]
Thanks @nilsdeppe  ... when you get a chance, can you try the steps I list above on wheeler, to see if you can reproduce the hang?

I have not run the python script inside docker at all. I ran it on my Mac, after copying the output files out of docker onto the Mac side. And I also tried wheeler, in case it was a docker or Mac problem.

**Comment by geoffrey4444** [comment]
Update: the hang seems to go away if I run with python 3.6 instead of python 2.7.15, as I was in all my tests before. Can the script warn or check about running with python 2?

**Comment by nilsdeppe** [comment]
PRs for such a warning are welcome :)

**Comment by geoffrey4444** [comment]
OK, I'll leave this issue open until I get to adding that warning.
