### ISSUE TITLE
Template DgElementArray and InitializeElement on Frame

### ISSUE THREAD

**Issue by mar-celine** [sxs-collaboration/spectre#1159]
### Expected behavior:

EvolveScalarWave3D should compile in the case where all instances of `Frame::Inertial` are replaced with `Frame::Grid` without needing to make changes outside of the executable file.

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
I'm not sure I agree. We should be using the physical frame (inertial), not the grid frame.

**Comment by mar-celine** [comment]
Which part are you disagreeing with? The need to template DgElementArray and InitializeElement or that EvolveScalarWave3D should compile with Frame::Grid? I can agree that as for EvolveScalarWave3D in particular we might want only Frame::Inertial for it, so I might have just picked a bad example and can change the wording on that. But my concern was more about evolution executables in general, I thought we wanted to support general Frames? Otherwise I'm not sure how to run an evolution with a Domain that only has Frame::Grid if everything else is expecting Frame::Inertial.

**Comment by nilsdeppe** [comment]
I don't know why they need to compile with the grid frame. InitializeElement should have a method of setting up dual frames, but the final frame should always be `Inertial`. I disagree with templating DgElementArray on frame.

**Comment by kidder** [comment]
Agree with @nilsdeppe, therefore I am closing this...
