### ISSUE TITLE
Missing libsharp gives over 600 lines of CMake errors

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#1181]
I was perhaps a bit hasty in merging #1066.  Running CMake without libsharp installed gives over 600 lines of error messages, mostly about bad variable values.  I assume there's a check that the libsharp search actually succeeded missing somewhere.

The errors start with the following, and continue in a roughly similar manner for a long time.
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBSHARP_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
   used as include directory in directory /home/wthrowe/spectre
```

**Comment by kidder** [comment]
looks like a problem with the arguments passed to find_package_handle_standard_args
see the other FindBla.cmake files for examples that have things defined for `FOUND_VAR` and `REQUIRED_VARS`

**Comment by moxcodes** [comment]
oops, should have tested the case without libsharp present better.
I see the fix, so I'll submit the fixup shortly.

**Comment by moxcodes** [comment]
Resolved by merge of [PR1182](https://github.com/sxs-collaboration/spectre/pull/1182)
