### ISSUE TITLE
Error norms should be computed as definite integrals

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1189]
# Bug reports:

`ValenciaDivClean/Observe.hpp` computes errors as `alg::accumulate(error, 0., PlusSquare{})`, where `error` is the scalar difference between the numerical and analytic solution, represented by a `DataVector`. It should instead compute `definite_integral(square(error), mesh)` to get a more useful quantity.

**Comment by nilsdeppe** [comment]
No, this is a standard L2 norm. There is nothing wrong with the way the error is computed. In fact, convergence of numerical methods is typically proven with L2 or L1 norms, not volume integrals over the domain. I'm closing this since this is not an issue.
