### ISSUE TITLE
Handle Initialization as a Phase

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1191]
# Feature request:

Both in the context of local time stepping and in terms of adding const global cache tags (PR #1180 comment by @hrueter and @nilsleiffischer ) it seems more natural to do all or most of the initialization in an Initialize phase. However, to make this reasonable to implement we will want phase-dependent action lists first. Phase-dependent action lists is something I've thought about and am quite sure I know how to implement.

**Comment by kidder** [comment]
Taken care of in #1535
