### ISSUE TITLE
Display authors and title of a Doxygen reference on hover

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1201]
# Feature request:

It would be nice to show information on a paper when hovering over it in the Doxygen documentation, similar to Wikipedia:

![bildschirmfoto 2018-11-27 um 16 40 46](https://user-images.githubusercontent.com/746230/49092894-4f3ecd00-f263-11e8-8c95-b663c511683b.png)

This should be possible with some custom css and extracting information from the `References.bib`.

### Component:

- [x] Documentation

**Comment by nilsdeppe** [comment]
Are we also discussing showing the preprint info here?

**Comment by nilsvu** [comment]
@nilsdeppe let's do that in #1203 (this issue is probably around for a bit longer 😄 )
