### ISSUE TITLE
Customize Doxygen bibliography format

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1203]
# Feature request:

It's probably possible to customise the bibliography rendering on https://spectre-code.org/citelist.html. For instance, @nilsdeppe suggested in #1193 to show preprint links more explicitly.

### Component:

- [x] Documentation

**Comment by nilsvu** [comment]
It would be good to have Doxygen use a different BibTeX style, but I am unsure if that is possible without forking Doxygen. Currently, Doxygen uses its own https://github.com/doxygen/doxygen/blob/master/templates/html/doxygen.bst file (in https://github.com/doxygen/doxygen/blob/65813bf307211ad647e0a2174c89ba80b3917139/src/cite.cpp#L150), and then runs https://github.com/doxygen/doxygen/blob/master/templates/html/bib2xhtml.pl over the output to convert it to HTML.

**Comment by nilsdeppe** [comment]
If you can get an option merged into Doxygen then it might be possible to use `\cite` in several years once common systems have support for it. I don't see any benefit to using it if we can't link to preprint articles from it. Forking it only helps us on Travis, not in general.

**Comment by nilsvu** [comment]
We can link to preprint / arXiv no problem with the current setup. I‘ll push an update to #1244 when I have it ready.

**Comment by nilsdeppe** [comment]
Okay, I apparently misinterpreted what you meant :) I view this issue as a bug if we can't show preprint links, and an enhancement if we can :)
