### ISSUE TITLE
Fix H5P_DEFAULT usage in Test_H5.cpp

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1213]
# Bug reports:

### Expected behavior:

Should use `h5p_default` function we have that wraps the macro

### Current behavior:

uses HDF5 macro

**Comment by fmahebert** [comment]
On current develop I do not see `H5P_DEFAULT` used in Test_H5.cpp. However I do see it in IO/H5/File.hpp:322. Is this still a bug?

**Comment by nilsdeppe** [comment]
Appears to be fixed.
