### ISSUE TITLE
Generalize MakeWithValue to support types other than double

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1215]
# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

Currently `make_with_value` always takes a `double` as the second argument. This should be generalized to any fundamental type or a `std::complex<FUNDAMENTAL_TYPE>`. Only the public function needs to be changed, I think. As individual classes need to be constructed from different types overloads of the `apply` function can be added.

**Comment by nilsdeppe** [comment]
@moxcodes I think this would be useful for the `std::complex` vectors and variables, no?

**Comment by moxcodes** [comment]
In fact, If I understand the issue properly, it should be fixed by [PR935](https://github.com/sxs-collaboration/spectre/pull/935)

**Comment by nilsdeppe** [comment]
That could be, I'm still working through the first commit there ;)

**Comment by kidder** [comment]
Fixed in #935

**Comment by hrueter** [comment]
> Fixed in #935

But #935 has not been merged.

**Comment by moxcodes** [comment]
#935 was split out into several other pull requests. The merged one that made this change was #970.
