### ISSUE TITLE
Add operator/ for double/DataVector

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#122]
It is not currently possible to write `x = constant/y;` for DataVectors `x`,`y`.

If we want to write intuitive expression templates for terms like the above, we should implement `DataVector::operator/(const double&, const DataVector&)` and the associated low-level infrastructure.

Note: we are working on a wrapper for `x = DataVector(y.size(), constant)/y` that will make the creation of a dummy numerator more generic and easy to use. The wrapper will provide a sufficient workaround, making this a low-priority issue. However, having an `operator/` would still be cleaner and more intuitive.

**Comment by osheamonn** [comment]
This issue comes up again in the porting of the CoordinateMaps, particularly in the case of the 2 and 3 dimensional wedges. Expressions of the form `radius/(1 + x)` or `1. / cos(M_PI_4 *x )` appear and it's awkward to have to use `make_arithmetic_value`.
