### ISSUE TITLE
Compiler flags are not correctly checked on Minerva

### ISSUE THREAD

**Issue by hrueter** [sxs-collaboration/spectre#1231]
# Bug reports:

cmake/AddCxxFlag.cmake: `check_and_add_cxx_flag` does not work correctly on Minerva.
Bug appeared after this commit https://github.com/sxs-collaboration/spectre/commit/ce1ac511438480d2827e86159b0b8fb1ddc80cdb#diff-5a96f5da6af64f7edc54537b85b3390f

### Expected behavior:

clang options are filtered out, when building with gcc.

### Current behavior:

gcc build fails due to clang options being present.

### Environment:

Minerva

CMake Version: 3.11.4
SpECTRE Version: 0.0.0
SpECTRE branch: minerva_env
SpECTRE hash: 0fee50c967df93dc4d0051e5ee0ffef633fafd61
Hostname: login02.cluster
Host system: Linux-3.10.0-514.26.2.el7.x86_64
Host system version: 3.10.0-514.26.2.el7.x86_64
Host system processor: x86_64
CMAKE_CXX_FLAGS:  -fPIC
CMAKE_CXX_LINK_FLAGS: 
CMAKE_CXX_FLAGS_DEBUG: -g
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS:  -fPIC
CMAKE_C_LINK_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_LINK_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Release
CMAKE_CXX_COMPILER: /home/SPACK/opt/spack/linux-centos7-x86_64/gcc-7.3.0/gcc-7.3.0-pqzvlyrhvyqucwzvefepsd7swbudesbr/bin/g++
CMAKE_CXX_COMPILER_VERSION: 7.3.0
CMAKE_C_COMPILER: /home/SPACK/opt/spack/linux-centos7-x86_64/gcc-7.3.0/gcc-7.3.0-pqzvlyrhvyqucwzvefepsd7swbudesbr/bin/gcc
CMAKE_C_COMPILER_VERSION: 7.3.0
CMAKE_Fortran_COMPILER: /home/SPACK/opt/spack/linux-centos7-x86_64/gcc-7.3.0/gcc-7.3.0-pqzvlyrhvyqucwzvefepsd7swbudesbr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 7.3.0
Python Version: 2.7.15
Charm Version:  6.8.0
BLAS_LIBRARIES:  /home/SPACK/opt/spack/linux-centos7-x86_64/gcc-7.3.0/openblas-0.3.0-cjwkboxx6kz2xsogsijpnsatdahddkfy/lib/libopenblas.so
Blaze Version:  3.2
Boost Version:  1.66.0
Catch Version:  2.2.1
GSL Version:  2.4
HDF5 Version:  1.10.1
jemalloc Version:  ..
LIBXSMM Version:  ..
LAPACK_LIBRARIES:  /home/SPACK/opt/spack/linux-centos7-x86_64/gcc-7.3.0/openblas-0.3.0-cjwkboxx6kz2xsogsijpnsatdahddkfy/lib/libopenblas.so;/home/SPACK/opt/spack/linux-centos7-x86_64/gcc-7.3.0/openblas-0.3.0-cjwkboxx6kz2xsogsijpnsatdahddkfy/lib/libopenblas.so
NumPy Version:  1.13.3
SciPy Version:  1.0.0

**Comment by wthrowe** [comment]
This is a locale issue.  Copy paste of error from #1228 (you should include stuff like this in your bug reports):
> g++: Fehler: unbekannte Kommandozeilenoption »-Wdocumentation«
> g++: Fehler: unbekannte Kommandozeilenoption »-Wnewline-eof«

Probably forcing LC_ALL=POSIX for the test compile (line 41ish of AddCxxFlag.cmake) will fix it. That would also let us remove some of the quote handling logic from later in the function.
