### ISSUE TITLE
Reference popovers can appear offscreen

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#1251]
The new popovers from #1242 can appear offscreen.  GitHub informs me that "Something went really wrong, and we can't process that file." when I try to include screenshots, so here are some links: 
[before mouseover](http://hosting.astro.cornell.edu/~wthrowe/popover_before.png)
[during mouseover](http://hosting.astro.cornell.edu/~wthrowe/popover_after.png)
As can be seen, the popover appears off the right side of the viewing area and a horizontal scrollbar appears.  But of course you can't use the scrollbar because as soon as you move the mouse it disappears again.

**Comment by hrueter** [comment]
Which browser (and which version) are you using?
Update: All browsers seem to be affected.

**Comment by wthrowe** [comment]
The screenshots were with Chromium (probably 71.0.3578.80).  Same behavior with Firefox 64.0.

**Comment by nilsvu** [comment]
Possibly moving to Bootstrap 4 would resolve this (we have 3.3.5). I'll try.
