### ISSUE TITLE
Framework for temporary computation buffers

### ISSUE THREAD

**Issue by moxcodes** [sxs-collaboration/spectre#1275]
# Feature request:

It is becoming increasingly common to use aggregated buffers to store temporary variables. This is important to performance, as it minimizes the number of allocations required, and allocations are a significant cost in highly parallel codes.

So far, similar objects have been used in #1177, #1179, #1161.

The design of these buffers has generated some discussion on its own, so this issue is to create a space for fleshing out those ideas.

A quick summary of points that have been made:
- These buffers are very similar to `Variables`, and in the case of containing vector types, they are a thin wrapper for `Variables`. However, `Variables` cannot be used directly because it cannot (and probably should not be modified to) contain `Tensor`s of doubles.
- The additional wrapping permits more descriptive names to be assigned to the buffers. This can be both a positive and negative structure, as there are times where a single buffer entry may be used for the storage of multiple, unrelated, pieces of data in different parts of a computation.
- The proliferation of specialized buffers will tend to create a large number of data types which are only well-applicable to individual computations. This is a problem solved by the structure of tags and `Variables`, and the problem is far more mild in the case of the thin wrapping of the buffers, but it still seems undesirable to have all of these data types if a more generic data type is possible. 

### Component:

- [ ] Code

**Comment by hrueter** [comment]
Here is a link to the previous discussion
https://github.com/sxs-collaboration/spectre/pull/1179#discussion_r248881363

**Comment by hrueter** [comment]
- @hrueter and myself notices that if we had the possibility to point into the spatial part of a 4-tensor, we could get rid of some of the tensors in these buffers. For instance, in #1172 there is a `d4_lapse` that we have to fill with its temporal part `d0_lapse` and spatial part `d3_lapse`. All three tensor need to be in the buffer right now, but it would be good to avoid this.

_Originally posted by @nilsleiffischer in https://github.com/sxs-collaboration/spectre/pull/1179_

**Comment by moxcodes** [comment]
After further discussion, the rough consensus among @nilsleiffischer , @nilsdeppe , and myself was that the use-case of reuse of the buffer motivated the creation of a generic object which
- for vectors, just wraps a `Variables`
- for doubles, wraps a `TaggedTuple`
Then the tags framework can be used. The main caviat to this structure is that whenever the temporary tags without clear identities are used, they should be assigned to local variable references with clear names.

There was agreement that it is desirable to save space by storing temporal and spatial components of tensors which are non-owning references into a 4-component tensor, potentially in generic index-slices of a higher rank tensor as well.  The construction of that ability to refer into larger tensors should probably be the topic of another issue.

**Comment by moxcodes** [comment]
@markscheel has kindly volunteered to implement this.
