### ISSUE TITLE
WriteReductionData needs to be called on every processor

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#1284]
# Bug reports:

### Expected behavior:

You should be able to call WriteReductionData on a Singleton component, when running on multiple cores.

You should be able to call WriteReductionData on an Array component that has fewer elements
than processors.

### Current behavior

In both of the above cases, WriteReductionData never writes data.  This appears to be because it waits until it receives `procs_on_node` calls before it does anything, which works fine if every processor calls WriteReductionData, but it doesn't work for Singletons and it doesn't work on Arrays in the case that some processors have zero elements.

I found this issue when trying to modify EvolveValenciaDivClean to output surface integrals using the Interpolation infrastructure, and running my code on Wheeler.  If it helps, I can clean up and push a branch to my fork; let me know.

(When running on a single core, none of these problems occur and everything works fine. In addition, everything works fine in the tests, since they use the mocking framework and run on one core.)

### Environment:

# Feature request:

### Component:

- [x] Code

**Comment by fmahebert** [comment]
Is this the same problem as #1147?
