### ISSUE TITLE
Add arithmetic operators for Point's

### ISSUE THREAD

**Issue by osheamonn** [sxs-collaboration/spectre#131]
It's come up multiple times now that having operator+, operator-, and operator*, operator/ for scalar multiplication would be useful to have for Points. The current plan is for this to be implemented with 'TensorExpressions' but I'm unclear on what the time frame for this is. Also since Point is rarely, if ever, used in expressions as complicated as other tensors (i.e. probably not going to be contracted with higher rank tensors) we could simply implement these operators and not rely on the TensorExpressions. We'd like to have them now for DomainHelpers, numerical derivatives in TestHelpers, and the transfinite blending that Gabe is working on. 

I've assigned myself to this since adding the simple operators shouldn't be difficult if this seems like a reasonable idea.

**Comment by nilsdeppe** [comment]
Addition and subtraction work, adding scalar multiplication and division is easy to do with TensorExpressions, I can add that

**Comment by kidder** [comment]
We addressed this by adding arithmetic operators on std::array in #136
