### ISSUE TITLE
DataVector sizes incorrect in constraint tests

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#1312]
# Bug reports:
See #508 

The 4's should be 5's

**Comment by geoffrey4444** [comment]
Sure but I like 4...what’s wrong with 4, just so I understand?

**Comment by kidder** [comment]
in #508 we agreed to use 5. and we want to be consistent throughout the code.  We know you love 4.

**Comment by geoffrey4444** [comment]
OK, just wondering! Maybe I need to file a 5->4 issue/PR some day

**Comment by nilsdeppe** [comment]
We're happy to close that PR without merging it :)

**Comment by nilsdeppe** [comment]
ping @geoffrey4444

**Comment by nilsdeppe** [comment]
I recently changed the sizes to speed up the tests. They are now the values they are because it provides a reasonable balance between runtime and accuracy.
