### ISSUE TITLE
Introduce "protocols" to structure our metaprogramming interfaces

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1349]
# Feature request:

I propose to introduce a new metaprogramming concept to our code: **Protocols**. Some variation of this feature is built into many languages, so let me quote from the [Swift documentation](https://docs.swift.org/swift-book/LanguageGuide/Protocols.html):

> A _protocol_ defines a blueprint of methods, properties, and other requirements that suit a particular task or piece of functionality. The protocol can then be _adopted_ by a class, structure, or enumeration to provide an actual implementation of those requirements. Any type that satisfies the requirements of a protocol is said to _conform_ to that protocol.

A similar feature is proposed for C++20 and goes under the name of [_concepts and constraints_](https://en.cppreference.com/w/cpp/language/constraints). We won't be able to adopt C++20 any time soon, and even then it's not clear that this is precisely what we want. So I propose to implement this feature mostly documentation-based for now, and then move to enforce it at compile-time as we go (with features becoming available in C++20, or sooner through metaprogramming).

A simple example to illustrate what I have in mind (read as pseudo-code):

```cpp
// Options/Protocols.hpp

/*!
 * \ingroup ProtocolsGroup
 * \brief Allows to create a type from input file options
 *
 * Requires:
 * - `static constexpr OptionString help`: A detailed description of the type
 *   and its options
 * - `typename options`: A `tmpl::list` of `OptionTag`s
 * - A constructor from the `::type`s of the `options`
 */
struct OptionCreatable {};
```
```cpp
// Options/CreateFromOptions.hpp

/*
 * \brief Create an instance of `T` from the `options`
 *
 * Requires:
 * - `T` conforms to `OptionCreatable`
 */
template <typename T>
T create_from_options(const Options& options) { ... }
```
```cpp
// Domain/Creators/Rectangle.hpp

/*
 * \brief A 2D rectangle
 * 
 * Conforms to:
 * - `OptionCreatable`
 */
struct Rectangle {
  // OptionCreatable interface
  static constexpr OptionString help{"A 2D rectangle"};
  using options = tmpl::list<LowerBounds, UpperBounds, ...>;
  Rectangle(std::array<double, 2> lower_bounds, std::array<double, 2> upper_bounds, ...);
};
```

Here the `create_from_options` function makes clear that it needs its template argument to be `OptionCreatable`. The documentation of `OptionCreatable` defines what that means. A `Rectangle` can then adopt this protocol, which qualifies it as a template argument to `create_from_options`.

None of this would be enforced at compile-time just yet, but it creates clear metaprogramming interfaces that are easy to trace through the code and the documentation. Eventually we can start adding metaprogramming functionality to the protocols, e.g. to use them in `Requires` or to add `static_assert`s (suggested by @nilsdeppe), or move to C++20 features when they become available, e.g. by converting the protocols into `concept`s.

Since this is mostly documentation we can start implementing this now, and gradually. I can put in a PR with a first couple of protocols to get things started. A few obvious ones:
- `db::SimpleTag` and `db::ComputeTag` may conform to a `TypedTag` protocol that allows them to be put in a DataBox, but that is also used by `TaggedTuple` and `ConstGlobalCache`. Requires only a `::name()` and `::type`.
- `Hashable` is always the first example for protocols in other languages. Requires the type implements a hash function.
- A `NumericalFlux` protocol to document all the metaprogramming details for implementing numerical fluxes. Another `NumericalFluxProvider` protocol that just requires a `numerical_flux_tag` type alias with a `::type` conforming to the `NumericalFlux` protocol (would be the Metavariables in this case).

**Bonus: Testing**

We _can_ enforce protocol conformance through tests. Every protocol provides a test function template with no arguments and returning `void` like this:

```cpp
// tests/Options/Test_Protocols.hpp

template <typename T>
void test_option_creatable() {
  T::help;
  T::options;
  // (or better static_assert them)
  // Make some options from T::options, then:
  T(some_options...);
}
```

Types adopting the protocol can then test their conformance like this:

```cpp
// tests/Domain/Creators/Test_Rectangle.cpp

test_option_creatable<Rectangle>();
```

### Component:

- [x] Code
- [x] Documentation

**Comment by nilsdeppe** [comment]
@nilsleiffischer can we close this?
