### ISSUE TITLE
IO Cleanup is broken for tests?

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1369]
# Bug reports:

### Expected behavior:

Tests pas

### Current behavior:

```
############ ERROR ############
Node: 0 Proc: 0
Line: 54 of ../src/IO/H5/File.cpp
Function: h5::H5File<h5::AccessType::ReadWrite>::H5File(std::string, bool) [Access_t = h5::AccessType::ReadWrite]
Failed HDF5 operation: Failed to open file 'Test_DistributedGmresAlgorithm_Reductions.h5'. The file exists status is: true. Writing from directory: build_clang/tests/Unit/NumericalAlgorithms/LinearSolver/Gmres. Trying to open in mode: ReadWrite
############ ERROR ############
```

My guess is that this test should delete the file *before* it starts and *after* it completes. Otherwise if the test is interrupt or fails between writing and deleting the test is in a perpetually failing state.

**Comment by nilsvu** [comment]
Could you give more information on the context of this failure?
Is it possible that this is due to some locking issue? Looks like the file exists and HDF5 tried to open it, which by itself sounds like a reasonable thing to do and shouldn't fail.

**Comment by nilsdeppe** [comment]
If you run any of the Elliptic executable tests (e.g. `Test_Dist...`) and it fails between writing the file and deleting it, the test will fail forever because it tries to open the file when it's not allowed to append. The solution is to delete the file (if it exists) at the start of the execution and also at the end.
