### ISSUE TITLE
Include order checking and sorting is broken

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1370]
# Bug reports:

### Expected behavior:

Running clang-format on a file correctly sorts includes.

### Current behavior:

The includes are not always sorted because there are `// IWYU pragma:` comments in between the includes. This is bad practice because it breaks clang-format and also clang-tidy checks. As far as I can tell this was started by @wthrowe  since I've only seen it in time stepping related code.

**Comment by wthrowe** [comment]
That's too bad.  I like that style.  But breaking the tools is bad so I'll fix it.

**Comment by nilsdeppe** [comment]
Agreed, it would be really nice
