### ISSUE TITLE
Inconsistent warnings between machines

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#139]
As discussed a few days ago, we expected sign comparison warnings from PR #127 but didn't see any on Travis.  It turns out I do see these warnings on my machine (with either gcc-5.4.0 or gcc-6.3.0), but, in addition to Travis, @osheamonn does not see them (6.3.0).

So something is causing inconsistencies, but I don't know what.

**Comment by nilsdeppe** [comment]
These now show up, (in #177 ) but I don't know what changed. I just updated the Docker image.

**Comment by nilsdeppe** [comment]
Is there anything currently we can do to reproduce this? What are the action items that need to be taken to resolve the issue?

**Comment by kidder** [comment]
@wthrowe do you want to keep this issue open, or close as `can't fix` because we cannot reproduce it?

**Comment by wthrowe** [comment]
Haven't seen this in a while, unless it is related to the known variation due to catch versions.  This bug is old enough that I think that is unrelated.  Let's close.

**Comment by nilsdeppe** [comment]
We appear to have figured this out: older versions of catch (around 2.1.2) silence warnings in the tests
