### ISSUE TITLE
TimeStepper dense output interface is awkward

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#1467]
The current requirement that dense output in a step must be performed before the step is completed makes dense-output operations that would like to know the value at the end of the step difficult.  A simple example of such a use is finding the time at which an evolved variable changes sign.

Clearing history just before taking a substep rather than just after (and modifying bookkeeping to account for that) should be enough to allow dense output just after a step.  It would be nice if this were done in a way that preserves the current ability to do pre-step dense output as well.

**Comment by nilsdeppe** [comment]
@wthrowe is this resolved? I know you've done a lot of work on dense output :)

**Comment by wthrowe** [comment]
This was fixed at some point, probably when FSAL support was added.
