### ISSUE TITLE
GH functions use compute_ prefix

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1480]
# Bug reports:

### Expected behavior:

We decided not to prefix functions with `compute_` since a function that does nothing is generally not what we want and these would be the only functions that wouldn't have a `compute_` prefix. The prefix should be removed from all GH functions that have them.

### Current behavior:

The `compute_` prefix is used.

**Comment by prayush** [comment]
@nilsdeppe : with 5e36592c792ed8a3a450fb4c6a5dd7678ed1a8f5 I think this is resolved. Can we close this issue?
