### ISSUE TITLE
Reduce initial-gauge dependency of damped harmonic gauge

### ISSUE THREAD

**Issue by prayush** [sxs-collaboration/spectre#1515]
# Bug reports:

There is an optimization that could be added to computation of damped harmonic gauge source function and its derivatives.(which is done in SpEC). 
 - [ ] If `(1 - roll_on_h_init)` is less than roundoff, then we can omit the terms involving `gauge_h_init`. 

Without this change, the evolution depends on the initial gauge until arbitrarily far in the future. This will restrict that dependency to a finite evolution time.

(c.f. [here](https://github.com/sxs-collaboration/spectre/pull/1172#discussion_r281377699))

**Comment by nilsdeppe** [comment]
We are not going to use rollon anymore since that requires spacetime Hessians on moving meshes
