### ISSUE TITLE
Change damped harmonic gauge rolloffs to be able to reproduce SpEC

### ISSUE THREAD

**Issue by prayush** [sxs-collaboration/spectre#1516]
# Bug reports:

The damped harmonic gauge in SpECTRE makes different choices for its temporal rolloffs than SpEC. Also, the way time rolloff option is implemented in SpECTRE is not amenable to reproducing the default behavior of SpEC for BBHs. If we are to do comparisons of SpECTRE vs SpEC there will need to be some further code changes in one of the two codes to ensure both are in the same gauge. Therefore:

 - [ ] Alter the way time rolloff is applied in SpECTRE to retain the capability of reproducing the default behavior in SpEC for BBHs.

(c.f. [here](https://github.com/sxs-collaboration/spectre/pull/1172#discussion_r281373949))

**Comment by nilsdeppe** [comment]
We have decided to not go with a rolloff/rollon in spectre since in SpEC it's not necessary anymore.
