### ISSUE TITLE
Add utilities to test consistency of fluxes

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#1526]
# Feature request:

PR #1322 has prompted discussion of checking the consistency of fluxes.

It would be useful to write system-agnostic utilities that check that a given flux `G(U-, U+)` satisfies:
- the flux correction `G - F` vanishes if the solution is identical on both sides of the interface (i.e., if `U- == U+`)
- the flux is correctly balanced on both sides of the interface (both sides compute the same flux `G` between the elements)

This should be tested for all our fluxes.

**Comment by nilsdeppe** [comment]
We have this now.
