### ISSUE TITLE
ExponentialFilter action allows only one set of parameters during entire execution

### ISSUE THREAD

**Issue by moxcodes** [sxs-collaboration/spectre#1530]
# Bug reports:

### Expected behavior:

Multiple different filters parameters may be used in a given execution of the code.

### Current behavior:

Static caching ensures that for a given matrix size, it is permanently set to the first `alpha` and `half_power` that was requested.

### Steps to reproduce:

replace the current test case block in `Test_Filtering.cpp` with 
```
SPECTRE_TEST_CASE("Unit.Evolution.dG.ExponentialFilter", "[Unit][Evolution]") {
  // Can't do a loop over different alpha and half_power values because matrices               
  // are cached in the action.                                                                 
  const double alpha = 10.0;
  const unsigned half_power = 16;
  invoke_test_exponential_filter_action<1, true>(alpha, half_power, false);
  invoke_test_exponential_filter_action<2, true>(alpha, half_power, false);
  invoke_test_exponential_filter_action<3, true>(alpha, half_power, false);
  invoke_test_exponential_filter_action<1, false>(alpha, half_power, false);
  invoke_test_exponential_filter_action<2, false>(alpha, half_power, false);
  invoke_test_exponential_filter_action<3, false>(alpha, half_power, false);

  const double new_alpha = 20.0;
  const unsigned new_half_power = 8;
  invoke_test_exponential_filter_action<1, true>(new_alpha, new_half_power, false);
  invoke_test_exponential_filter_action<2, true>(new_alpha, new_half_power, false);
  invoke_test_exponential_filter_action<3, true>(new_alpha, new_half_power, false);
  invoke_test_exponential_filter_action<1, false>(new_alpha, new_half_power, false);
  invoke_test_exponential_filter_action<2, false>(new_alpha, new_half_power, false);
  invoke_test_exponential_filter_action<3, false>(new_alpha, new_half_power, false);

  invoke_test_exponential_filter_action<1, true>(alpha, half_power, true);
  invoke_test_exponential_filter_action<2, true>(alpha, half_power, true);
  invoke_test_exponential_filter_action<3, true>(alpha, half_power, true);
  invoke_test_exponential_filter_action<1, false>(alpha, half_power, true);
  invoke_test_exponential_filter_action<2, false>(alpha, half_power, true);
  invoke_test_exponential_filter_action<3, false>(alpha, half_power, true);

  test_exponential_filter_creation<1>();
  test_exponential_filter_creation<2>();
  test_exponential_filter_creation<3>();
}
```
The second set of action tests fails because the parameters of the matrices used are cached as the original set, and cannot be updated to the new set.

I think the only way to properly cache these is to use rationals for the double parameter in the cache, but then the jump table is probably larger than you want it to be to support the range of values you'd want. It's possible that the right answer is to just remove caching from this application.

**Comment by nilsdeppe** [comment]
I don't see the need for this functionality. I only encountered a "need" in a test. I'd rather keep the code simple. What do you need this for?

**Comment by nilsdeppe** [comment]
I realistically won't get to this for at least 3-6 months, so I'm unassigning myself.

**Comment by moxcodes** [comment]
I have no current need for it, I was just reflecting on the difficulty of caching things which take doubles and realized I missed this on my review. My main point is simply that multiple instances of the same action should work as expected in a given execution. 

Is there a reason the matrices cannot simply be ordinary member variables of the action?

**Comment by nilsdeppe** [comment]
They could be part of the action. The reason for doing it this way is to have an interface more in line with other matrix operators in DG, but I don't see a reason not to have an interface that allows retrieving the matrices in a non-cache manner and doing caching elsewhere (e.g. in the action). In practice my experience has been that nothing is gained in terms of accuracy by only filtering some of the variables or filtering some less than others. :man_shrugging:

**Comment by nilsdeppe** [comment]
I just checked, the matrices are cached as part of the action, so the requested behavior already exists. This is why the matrices aren't cached in the `Spectral/Filtering.cpp` file. Can we close this as `invalid`?

Edit:
This functionality is even documented.

**Comment by moxcodes** [comment]
I'm confused, and willing to discuss -- Are you indicating that the actions should act as in the test code pasted in the issue?  I'm not sure I understand why this should be an invalid use; in executables that may handle different domains in different methods (e.g. cauchy evolution and characteristic extraction, just to identify a specific example), different filters might be required.
(edited for grammar)

**Comment by nilsdeppe** [comment]
Your example with CCE and cauchy evolution is supported. This is because you pass an index `FilterIndex` to the filter action. The parameters are cached for that index, so as long as you use a different `FilterIndex` in the cauchy and CCE evolutions you're fine.

The reason I'm saying it's `invalid` is because from my understanding (and maybe I'm misunderstanding), your request is the example you gave: you can filter different variables (possibly evolved on different domains) by different amounts. This feature already exists.

**Comment by moxcodes** [comment]
Aha! understood. I overlooked the usefulness of the index in the action class, which as you say, completely solves the issue I thought I had seen. Agreed, closing.

**Comment by nilsdeppe** [comment]
Ah okay, sorry for not being clearer on that earlier! And overall, thank you for bringing this up :) I think at the very least I will change the comment in the test to make it clear that the feature is supported, just not used in the test (or maybe it'll be easy to generalize the test, I'll need to look).
