### ISSUE TITLE
Wrap tmpl::append to avoid bug.

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#1537]
# Bug reports:

Consider:
``
struct a;
struct b;
using c = tmpl::append<tmpl::list<a>,b>;
``

### Expected behavior:

I would have expected `c` to be `tmpl::list<a,b>`.

### Current behavior:

`c` is an empty `tmpl::list<>`.

# Feature request:

It would be nice if `tmpl::append` were a wrapper around `brigand::append`
that, for the above example, either
1.  Resulted in `c` being `tmpl::list<a,b>`
2.  Produced an easy-to-understand compiler error instead of silently producing an empty list.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

**Comment by nilsdeppe** [comment]
@wthrowe I remember you getting various fixes merged upstream. Was fixing `append` one of them?

**Comment by wthrowe** [comment]
Yes, this is fixed upstream, and I believe we use the fixed version in CI.
