### ISSUE TITLE
Pass local cache to parallel components

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1551]
# Feature request:

Instead of the cache proxy that is currently passed to `initialize` and `execute_next_phase`, pass its `ckLocalBranch()`.

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

### Detailed discussion:

**Comment by nilsvu** [comment]
discussed during the #1535 review

**Comment by nilsdeppe** [comment]
- for `initialize` this is not possible.
- I'm removing `execute_next_phase`
