### ISSUE TITLE
Collect cache tags from actions automatically

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1552]
# Feature request:

Have `ConstGlobalCache_detail::make_tag_list` collect the cache tags also from all actions in all components, so that each component doesn't have to do that themselves.

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

### Detailed discussion:

**Comment by nilsvu** [comment]
Came up while reviewing #1535

**Comment by kidder** [comment]
I will do this as part of simplifying getting options into Databoxes

**Comment by nilsvu** [comment]
@kidder is this issue resolved with your recent PR? If so, you have the honor of closing it :)

**Comment by kidder** [comment]
Implemented in #1676
