### ISSUE TITLE
Rename create_initial_element

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#1556]
# Bug report:

### Expected behavior:

Function name reflects its action.

### Current behavior:

Function name does not reflect its action.

"Initial" has strong connotations to time-evolution, but this function creates an element defined by a particular spatial resolution, independent of time.

I suggest renaming `create_initial_element ` to `create_root_level_element`. Other options could be `create_base_resolution_element`, `create_block_covering_element`, or similar.

If the general idea is agreeable, then after we agree on a new name I volunteer to make the change.

**Comment by kidder** [comment]
No, it is meant only for creating an initial element.  The documentation is incomplete and should state that when doing so it assumes that it has neighbors that share its refinement levels.    It is not the root_level_element or a block_covering_element and I don't know what a base_resolution_element is. It is very likely to be wrong to create an element with this function at any other time.   So the documentation should be improved, but the name is fine...

**Comment by fmahebert** [comment]
Okay, I agree that the documentation should be improved, because I clearly misunderstood what this function is doing. Forget any of my suggestions, then.

Even after your comment I remain somewhat unsure of what this function is actually doing. What I think you're saying is: this function creates an element at some specified refinement level and position within the block, but assumes there is no h-refinement when setting up the element's neighbor information. Is that about right?

**Comment by kidder** [comment]
Yes, that is correct.
