### ISSUE TITLE
Remove execute_next_phase functions

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1562]
# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

The `execute_next_phase` functions are not really necessary since most of the same can be achieved using iterable actions and having `Main.hpp` call `start_next_phase` directly. Implementing this will take some work since several different parts of the code use `execute_next_phase` to call simple actions, which would no longer be supported.

**Comment by kidder** [comment]
Here are the non-trivial execute_next_phase calls:

- [ ] SingletonHelloWorld.hpp
- [ ] InterpolationTarget.hpp 
- [ ] Test_AlgorithmCore.cpp
- [ ] Test_AlgorithmNodeLock.cpp
- [ ] Test_AlgorithmParallel.cpp
- [ ] Test_AlgorithmReduction.cpp

**Comment by nilsdeppe** [comment]
It appears we are keeping said function :)
