### ISSUE TITLE
Check termination was successful

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#1570]
# Bug reports:

### Expected behavior:

If any component has not entered the `Exit` phase then we should not mark termination as successful.

### Current behavior:

If a component is waiting on more data from somewhere termination is marked as successful even though this is not the case. For components like the `DgElementArray` that just run iterable actions the check is as simple as running `start_phase(Phase::Exit)`, but for components like observer writers this is a bit trickier since something actually needs to either (a) dump the data and then exit successfully or (b) not dump the data exit unsuccessfully.

**Comment by kidder** [comment]
discussion with @nilsdeppe 
Have ERROR hook into something global that triggers the `Main` component to call `Phase::Cleanup` on all components who can then individually decide what to try to do in the phase...

**Comment by nilsdeppe** [comment]
Fixed in #4236
