### ISSUE TITLE
Classes should not be their own tags

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#1594]
Tags are supposed to explain what an option is being used for, not what type it is.  That is not a property of the class, and for some classes can very from use to use.

The particular case I just ran into was `ExponentialFilter`, which is an action, the storage of the parameters for that action, and the tag for that storage.  This results in three separate sets of functionality mixed together in one class with few hints of what is for what use.  There are probably other similar cases.

**Comment by nilsdeppe** [comment]
Discussion with @wthrowe and @kidder:

Yes, agreed that it is reasonable to split things.

**Comment by kidder** [comment]
fixed in #1685
