### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by haraldp271** [sxs-collaboration/spectre#16]
Going through https://sxs-collaboration.github.io/spectre/installation.html, and listing everything that's unclear

* GCC 5.2 or later, or Clang 3.6 or later:   Add information for mac (Nils verbally:  LLVM 8.1 should be ok)
* mention that hdf5 needs to be compiled **without** mpi (e.g. in brew do *not* use the --with-mpi option)
* For download Charm++, state that it needs to be compiled from source (for patching).  Also mention that if compelling on a local laptop, easiest is to do cd charm; ./build for the interactive built, where default options are mostly ok.   State that precisely v6.7.1 is needed for MacOS
* mention to clone master of brigand, Catch and yaml-cpp
* When compiling bitbucket/dg-charm:spectre_2b according to the instructions in the GitHub repo, several issues arise
  1. apparently, Fortran is only capitalized in -D CMAKE_Fortran_COMPILER
  1. my charm build-directory is charm/multicore-darwin-x86_64, which is not captured by the glob "path/to/charm/build-*"
  1.  add info about patching charm++
  1. add info about how to specify the paths to the other packages that were installed earlier
  1. and/or add info about slack

**Comment by nilsdeppe** [comment]
Fixed with #13
