### ISSUE TITLE
Force Openblas serial during Charm executions

### ISSUE THREAD

**Issue by moxcodes** [sxs-collaboration/spectre#1613]
# Bug reports:

OpenBLAS has the feature of automatically detecting available cores and parallelizing matrix operations according to internal judgements of speed, via openmp. This can clash with other parallelization and actually hurt performance when those internal judgements aren't done well. 

We should probably disable this feature. For Charm-based executables, we can probably use the openblas `openblas_set_num_threads` or possibly a similar override for openmp globally in a function to be put in the `charm_init_node_funcs` for an executable to force single-threaded mode (suggestion from @nilsdeppe).

**Comment by nilsvu** [comment]
This should be fixed by #2463. @moxcodes can you confirm?
