### ISSUE TITLE
Remove dependence of Domain/CoordinateMaps on ControlSystem

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1634]
# Bug reports:

### Expected behavior:

`Domain` does not depend on ControlSystem (or anything else evolution-related).

### Current behavior:

`Domain/CoordinateMaps/CubicScale,Translation.cpp` include `ControlSystem/FunctionOfTime.hpp`.

**Comment by kidder** [comment]
fixed by #1846
