### ISSUE TITLE
Reorder Travis tasks

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#165]
For some reason Travis has decided to run its tasks in serial for my pull request, which means I don't get clang-tidy output until waiting through the OSX queue.  Can we put the OSX tasks at the end?

**Comment by kidder** [comment]
I was experimenting with having Travis only run its tasks in serial to see if it eliminated the timeouts;  we should probably put all the quick tasks at the beginning if possible

**Comment by nilsdeppe** [comment]
This is done in #177
