### ISSUE TITLE
Make Test_ImposeBoundaryConditions.cpp test a realistic configuration

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1679]
This is a follow-up on a discussion in https://github.com/sxs-collaboration/spectre/pull/1529. `Test_ImposeBoundaryConditions.cpp` places an external boundary within a block, which is not a realistic configuration, and the test can generally be made more concise.

### Component:

- [x] Tests

**Comment by nilsdeppe** [comment]
`ImposeBoundaryConditions` no longer exists, so that sort of fixes the issue...
