### ISSUE TITLE
Port code for Domain creation

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#171]
We need to be able to construct a Domain

**Comment by kidder** [comment]
Still to do:

- DomainHelper #124 
- Remaining embedding maps (Wedge, ...) needs #136 
- We need to figure out what a Domain is
- Element
- something that keeps track of neighboring Elements (known as Neighbors in Bitbucket)
- DomainCreators (probably as compile-time with run-time parameters)

**Comment by nilsdeppe** [comment]
@kidder I think this can be closed. We have #293  tracking the individual creators. What do you think?
