### ISSUE TITLE
Port Functors

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#172]

**Comment by fmahebert** [comment]
In today's call @nilsdeppe, @wthrowe, @markscheel and I discussed where to port the remaining Functors (and where to move some of the already ported ones):

**Numerical/Domain**
DataOnSlice
GridCoordinates
GridNormal
InverseJacobian
OrientVariablesOnSlice

**Numerical/Interpolation**
InterpolateToPoints
InterpolateToRegularGrid
(Also LagrangePolynomial as discussed in #208. This may be moved elsewhere in the future to join other polynomials.)

**Numerical/LinearOperators**
DefiniteIntegral (already ported into `Numerical/Spectral`)
Linearize (already ported into `Numerical/Spectral`)
MeanValue (currently under review in #185)
Divergence
Gradient
Transpose

**PointwiseFunctions/Tensor**
The items already ported into `DataStructures/Tensor/EagerMath`

**PointwiseFunctions/GeneralRelativity**
The contents of `Functors/GrFunctors`

**PointwiseFunctions/EinsteinSolution**
The contents of `Functors/EinsteinSolutions`


Finally, the following need further consideration (or may not be ported at all):
EquationOfState
ExtractPointFromCoordData (no longer needed, can now do math on `DataVectors`)
Norms & TypeOfNorm (maybe this belongs with observers)
PointwiseNorm (used in AH finder)
SetGridData (should be in initial data)

**Comment by nilsdeppe** [comment]
We currently don't have any issues with the organization, closing
