### ISSUE TITLE
Have Travis check for 'Ls'

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#179]
Ls should be List

**Comment by nilsdeppe** [comment]
Also check for `/*! \ingroup`

**Comment by nilsdeppe** [comment]
Should also check for the test names that container `Functors`

**Comment by fmahebert** [comment]
Some of these checks are temporary in their usefulness.. we are currently porting tests whose names contain `Functors`, but after we are done porting the problem should no longer occur. We may want to schedule a clean-up of these "legacy" checks once the porting is done?

**Comment by nilsdeppe** [comment]
Also check for `enable_if`
