### ISSUE TITLE
Use GitHub Actions instead of Travis

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1802]
# Proposal

Since Travis build times are currently slowing us down, I am looking at GitHub Actions as a possible replacement.

I am testing it on my fork at https://github.com/nilsleiffischer/spectre/actions right now, and so far it seems to work quite well. In particular, GitHub Actions work very nicely with Docker containers.

I can run all tests that Travis currently runs on GitHub, and according to [their documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#usage-limits) we get 20 concurrent jobs instead of Travis' 5. Also, we can set up a server to self-host GitHub Actions runners, which would allow us to run as many concurrent jobs as our server can handle.

Current limitations that I have discovered are (I will keep this list updated):
- The cache size is currently limited to 400MB per cache directory and 2GB per repository for GitHub-hosted runners (but of course unlimited for self-hosted runners).

I have pushed an example workflow with all checks <s>except unit tests</s> to #1804. You can take a look at an example PR at https://github.com/nilsleiffischer/spectre/pull/1.

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [x] Continuous integration

**Comment by nilsdeppe** [comment]
Thanks for the overview! There are some other issues:
- What are the capabilities of the machines we run on? E.g. memory available and number of cores available to each build?
- What is the time limit for each job?
- As you say, the cache is really not great. Having 20 things build in parallel without a cache is unlikely to be of much use.
- Have you looked at [Azure Pipelise](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-get-started?view=azure-devops&tabs=yaml)? That's what I think is the most promising avenue. Their caching support is currently in beta, but you get 6 hours per job.

Another possibility is to build different targets on different CI systems. E.g. Do clang 4 &5 on Travis, clang 8 & gcc 6 on Azure, and gcc 8 & 9 on GitHub Actions. While a little more complex, it's hopefully manageable in the sense that we use docker to build anyway.

Here is a table: https://github.com/r-lib/ghactions/issues/309 I think we should having something like this in the main comment of this issue comparing our needs across different offerings. I think CircleCI also does Linux nowadays.

**Comment by nilsvu** [comment]
Here's a bit more information:

- GitHub-hosted runners have 2 CPUs, 7 GB RAM and 14 GB SSD disk space (see [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources)). This is about the same that Travis provides (see [docs](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system))
- The time limit for each GitHub-hosted runner is 6 hours (see [docs](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system)).
- Indeed 2 GB of cache is not enough to cache all 14 compiler configurations that we are currently testing. A few thoughts on caching and build times:
  - Travis doesn't give any information on allowed cache sizes, so I don't actually know how much we are currently caching.
  - I think we should run most (or all) of our CI runs on a self-hosted machine anyway, where we can cache as much as we want to.
  - Actually a single CI run without caching takes about 1-2 hours on a GitHub-hosted runner, so that's the time it takes to fully test one PR (14 compiler configs that take about 1-2 hours each but run in parallel). If we can bring down CI times from 10 hours (current Travis average) to 1-2 hours, I think that would help a lot :) More caching or running on a self-host machine could bring this down further.
- I haven't looked at Azure pipelines in detail, but it actually looks very similar to GitHub Actions (not surprisingly, since it's Microsoft as well)! They don't give information on cache size limits yet, while it's still in beta. Edit: The table you posted is quite useful! I'll add a table to the description above.

**Comment by nilsdeppe** [comment]
Thanks! That helps a lot :)

One way we could get around the caching issue (related to a different discussion we had), is push the built images from develop to DockerHub. Then for each PR we actually pull the DockerHub image and rebuild whatever parts of the cache were invalidated by code changes. I think this can be combined with Azure Artifacts (GitHub Actions probably has a similar thing) to cache the base image and then just download the cache. What do you think?

**Comment by nilsvu** [comment]
Interesting idea 😄 I worry that building over a previously built image may not be as reliable as a fresh build. But indeed if we're only limited by cache size limits, we can just upload and download the cache to/from another server, e.g. one we host ourselves. That's what I think your DockerHub suggestion boils down to - upload the cache somewhere with more storage space.

If we want to stick to >~14 build configs and keep up (or increase) the rate of PRs we currently have, I think we ultimately can't expect to run on free machines for our CI. Either we spread the load over multiple services as you suggested, or we self-host runners and/or cache storage space.

**Comment by nilsdeppe** [comment]
I'm not sure how pulling from dockerhub is any less reliable than what we currently do. I'd really like to avoid hosting things ourselves. Of course, once the free services no longer work we can't get around that, but I think then it makes more sense to just set up our own build machine using, e.g. TeamCity rather than just hosting a cache.

**Comment by nilsvu** [comment]
- Perhaps I misunderstood your DockerHub suggestion. If we build and test within the Docker container, package it up, push to DockerHub, and pull that image for the next CI build, then the next CI build will execute in this prebuilt environment. It builds the executables in the directory that is already populated with the previous build, right? It may not even run CMake if it determines it unnecessary. If this is indeed what you are suggesting, then I worry this test may be not as reliable as a fresh build, in particular for edge cases (e.g. Python files created by CMake that are not updated correctly, etc). What do you think?
- Right now, this is my suggestion for the most promising CI setup:
  - We switch to GitHub Actions or Azure Pipelines, reducing CI runtimes down to 1-2 hours per PR right away (because we get the 6h time limit and 20 concurrent jobs). I have that working on GitHub Actions now.
  - If we determine we need to speed things up, we can set up a machine for self-hosted runners. That's significantly easier to maintain than a full self-hosted CI server like Jenkins or TeamCity, and it solves the caching issue.

**Comment by kidder** [comment]
mostly implemented; still want to add automatic update of documentation and revive code coverage

**Comment by nilsdeppe** [comment]
Only code coverage remains

**Comment by nilsvu** [comment]
Coverage is done as of #3367. Only the documentation needs to be updated now: #2421
