### ISSUE TITLE
Convert shell scripts to Python

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1814]
# Feature request:

It would be nice to convert the shell scripts in `tools/` to Python. I feel like that would make them easier to maintain, but maybe that's just me because I know Python better than bash.

To be clear, I don't suggest we do this now. We have better things to do right now (and probably always).

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

**Comment by nilsdeppe** [comment]
No, then we have to launch the python interpreter every time which is silly expensive. Plus there are people who know bash that don't know python.
