### ISSUE TITLE
PR #1764 fails without python bindings

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#1834]
The tests added in #1764 fail without python bindings enabled.  It looks like @moxcodes was worried about this during review.

```
   1/1034 Test #1033: Unit.Hydro.EquationsOfState.Python.PolytropicFluid .......
...................***Failed    0.04 sec
Traceback (most recent call last):
  File "/home/wthrowe/spectre/tests/Unit/PointwiseFunctions/Hydro/EquationsOfSta
te/Python/Test_PolytropicFluid.py", line 4, in <module>
    import spectre.PointwiseFunctions.Hydro.EquationsOfState as spectre_eos
ModuleNotFoundError: No module named 'spectre.PointwiseFunctions.Hydro'

          Start  584: Unit.Numerical.LinearOperators.PartialDerivs.ComputeItems
   2/1034 Test #1032: Unit.AnalyticSolutions.GeneralRelativity.Python.Tov ......
...................***Failed    0.04 sec
Traceback (most recent call last):
  File "/home/wthrowe/spectre/tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Python/Test_Tov.py", line 6, in <module>
    import spectre.PointwiseFunctions.Hydro.EquationsOfState as spectre_eos
ModuleNotFoundError: No module named 'spectre.PointwiseFunctions.Hydro'
```

**Comment by nilsdeppe** [comment]
#1836 changes the clang-8 release target to no longer build the python bindings. I also disable the 3 failing tests when bindings are not built. @nilsleiffischer please make sure this is what should be done, otherwise submit a PR to improve it.

**Comment by nilsvu** [comment]
@nilsdeppe My PR that added the bindings should have used `spectre_add_python_bindings_test` instead of `spectre_add_python_test`, which would have disabled the tests appropriately. I commented on that in your PR #1836 and actually just opened #1837 to offer a quick way to fix it if you want.
