### ISSUE TITLE
definite_integral should take a DataVector, not a Scalar<DataVector>

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#187]
I do not see why it takes a Scalar<DataVector>  (In fact it didn't in PR #47, but did in PR #51 which says it was recreated from PR #47, and it looks like we reviewed PR #47, but not PR #51. So do we need to see if there are any other differences between the two PRs?)

**Comment by nilsdeppe** [comment]
Why should it take a dataVector? Under what circumstances does it make sense to integrate something that isn't a scalar?

**Comment by kidder** [comment]
We integrate tensor components when computing norms in SpEC.

**Comment by nilsdeppe** [comment]
Alright, good reason :)
