### ISSUE TITLE
How should triggers interact with LTS/local data?

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#1877]
Most events (I believe all the currently implemented ones) have to run on every element to avoid a communication lockup.  There are two ways an event could fail to run in this way:

1. A trigger only triggers on some elements, even though it is checked on all of them.
2. A trigger is only checked on some elements.

Most triggers should be written so that (1) does not happen, but there may be diagnostic events where this is reasonable.  Such triggers must not be used to run "global" events.

Triggers are checked after every step (and may eventually be checked for dense output, but that shouldn't be an issue here), so currently all checks in LTS runs can hit case (2).  The ability to run after steps other than slab boundaries has been requested for debugging/diagnostic purposes, so we don't want to remove that.  We avoid trouble for the moment because the most common triggers explicitly check and only fire at slab boundaries.

---

My current thoughts on how to make this safer are to add a method to events returning whether they have to be run globally, and then make the actions refuse to run such events when the run is not at a slab boundary (or dense output observation).  I think just ignoring these events at invalid times will give the most intuitive behavior, since having to add "and at slab boundary" to every non-debugging trigger would be annoying, particularly when switching from GTS to LTS, but we could also consider erroring.

We can then remove checks for slab boundaries from the current triggers, so they can be used more flexibly for debugging purposes.  (We already have an "And" trigger, and adding a "AtSlabBoundary" trigger would be easy, so this doesn't lose any current functionality.)

We may then want to add a similar flag to the triggers indicating that they operate on local data and therefore should not be used to trigger any events that must be run globally.  A check for inappropriate triggers could be done at initialization time, and it probably should error since I can't think of a sane way to proceed in that case.  A trigger wrapper to suppress the error would be easy to write.

**Comment by nilsdeppe** [comment]
@wthrowe since you have dense output working, is this resolved or still an open question?

**Comment by wthrowe** [comment]
This is still unresolved, although since as far as I know no one has requested doing anything on substeps (or non-slab-boundaries for LTS, but that's not in very widespread use) I'm considering just dropping this until someone has a use for it.

If we want to close this we should add a check to RunEventsAndTriggers to restrict its effects to slab boundaries (being careful because the action is also used for elliptic executables).  I've only triggered it off boundaries on accident, and it usually causes weird errors.  I'll do this sometime unless I hear specific requests for features.

**Comment by nilsdeppe** [comment]
Restricting to slabs seems fine. The only use case I could see right now is debugging a simulation, but with dense output that probably won't be necessary. One possible local-data-only use case is monitor the max density to start triggering the horizon finder, but I could see that causing all sorts of async problems. My vote is to prevent running on substeps until we find a use case that we can't solve with dense output :)

**Comment by wthrowe** [comment]
I'll call this resolved now.  Substeps were handled in #5241.  Dense output is fine for most things in LTS.  I don't think we want to allow triggers to act differently on different elements depending on local data.

There is still the question of how to handle triggers based on some non-local property, like the max density, but that's tangential to the original issue here and we can follow up on a new issue when we think about it.
