### ISSUE TITLE
spectre-code.org website broken on mobile

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#1887]
# Bug reports:

### Expected behavior:

The main page for SpECTRE should be welcoming to as many users as possible, including users browsing from smartphones. Currently, however, spectre-code.org is broken on mobile, because of limitations of the HTML that doxygen generates.

Besides being more welcoming to users, a mobile-friendly site would make it convenient for users who might like to use a mobile device to browse our documentation.

### Current behavior:

On my smartphone, here are some screenshots illustrating the problem:

![IMG_608A5C98EA7F-1](https://user-images.githubusercontent.com/867015/71826180-33a31a00-3052-11ea-9839-dd5f13b135a9.jpeg)
![IMG_F90BEE9B053E-1](https://user-images.githubusercontent.com/867015/71826212-461d5380-3052-11ea-9563-81ec5678d2b0.jpeg)

### Possible solutions:

One possible fix might be to have doxygen generate XML instead of HTML, and then use this to render mobile-friendly HTML from the XML:

https://mcss.mosra.cz/documentation/doxygen/

### Environment:

The latest spectre-code.org website.

# Feature request:

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by kidder** [comment]
@nilsdeppe and I have played around a little with [sphinx](http://www.sphinx-doc.org/en/master/) and [breathe](https://breathe.readthedocs.io/en/latest/) which should make this possible...

**Comment by geoffrey4444** [comment]
Awesome! Thanks for looking into this :)

**Comment by nilsvu** [comment]
This is fixed now, since we're building with Doxygen 1.9.2+ in the container. #3412 further improves on the mobile layout.
