### ISSUE TITLE
ActionTesting's is_ready doesn't compile when using tags added in an action of an earlier phase

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1908]
# Bug reports:

The following PDALs should compile with the ActionTesting framework:

```cpp
  using phase_dependent_action_list = tmpl::list<
      Parallel::PhaseActions<
          typename Metavariables::Phase, Metavariables::Phase::Initialization,
          tmpl::list<
            ActionTesting::InitializeDataBox<db::AddSimpleTags<...>>,
            InitializeAnotherThing  // Uses `merge_into_data_box` to add another tag
      >>,
      Parallel::PhaseActions<
          typename Metavariables::Phase, Metavariables::Phase::Testing,
          tmpl::list<
              DoSomething  // Uses the tag added in `InitializeAnotherThing` in `is_ready`
    >>>;

// Somewhere after constructing an `ActionTesting::MockRuntimeSystem`:
runner.is_ready<the_component>(the_element_id)  // Fails to compile
```

The issue is (I think) that `ActionTesting::MockRuntimeSystem::is_ready` tries to instantiate `DoSomething::is_ready` for DataBoxes in all phases and fails for the initial DataBox that hasn't had `InitializeAnotherThing` applied yet. This setup works fine for `get_databox_tag`, so I think `is_ready` just needs to get a similar treatment.

**Comment by nilsdeppe** [comment]
Does this exist for both the test and for the actual code?

**Comment by nilsvu** [comment]
I think `src` is fine, since the PDALs with initializers in the first phase and `ReceiveDataForFluxes` in a later phase compile without error.
