### ISSUE TITLE
Python bindings don't work in singularity container

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#1922]
# Bug reports:

### Expected behavior:

In the spectre singularity container, I expect running the following python should create a file "Test.h5"
~~~~
import spectre.IO.H5 as spectre_H5
spectre_H5.H5File("Test.h5", True)
~~~~

### Current behavior:

The above code fails:
~~~~
AttributeErrorTraceback (most recent call last)
 in ()
      1 import spectre.IO.H5 as spectre_h5
----> 2 spectre_h5.H5File(file_name=“Test.h5", append_to_file=True)
AttributeError: ‘module’ object has no attribute ‘H5File’
~~~~

But the following succeeds:
~~~~
from spectre.IO.H5 import _PyH5 as spectre_H5
spectre_H5.H5File(“Test.h5", True)
~~~~

### Environment:

I'm using the singularity container `/opt/ohpc/pub/containers/spectre_ocean.sif` on `ocean.fullerton.edu`:

CMake Version: 3.10.2
SpECTRE Version: 0.0.0
SpECTRE branch: develop
SpECTRE hash: 1ef248fba663600257c36893af8fd149b2f85176
Hostname: ocean.fullerton.edu
Host system: Linux-3.10.0-957.1.3.el7.x86_64
Host system version: 3.10.0-957.1.3.el7.x86_64
Host system processor: x86_64
CMAKE_CXX_FLAGS:  -fPIC
CMAKE_CXX_LINK_FLAGS: 
CMAKE_CXX_FLAGS_DEBUG: -g
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS:  -fPIC
CMAKE_C_LINK_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_LINK_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/bin/clang++-5.0
CMAKE_CXX_COMPILER_VERSION: 5.0.1
CMAKE_C_COMPILER: /usr/bin/clang-5.0
CMAKE_C_COMPILER_VERSION: 5.0.1
CMAKE_Fortran_COMPILER: /usr/bin/gfortran-9
CMAKE_Fortran_COMPILER_VERSION: 9.2.1
Python Version: 2.7.17
Charm Version:  6.8.0
Charm SMP:  NO
BLAS_LIBRARIES:  /usr/lib/x86_64-linux-gnu/libopenblas.so
Blaze Version:  3.2
Boost Version:  1.65.1
Catch Version:  2.2.1
Google Benchmark Found
GSL Version:  2.4
HDF5 Version:  1.10.0.1
jemalloc Version:  ..
LIBXSMM Version:  ..
LAPACK_LIBRARIES:  /usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so
NumPy Version:  1.16.6
SciPy Version:  1.2.2

# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsvu** [comment]
Is this issue resolved @geoffrey4444 ?

**Comment by geoffrey4444** [comment]
Yep

**Comment by kidder** [comment]
@geoffrey4444 or @nilsleiffischer please comment on how it was resolved...

**Comment by geoffrey4444** [comment]
I rebuilt and the problem went away...I guess I somehow got my build directory in a bad state.
