### ISSUE TITLE
Clang-tidy is not run by GitHub Actions on forks

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#1933]
# Bug reports:

### Expected behavior:

I expect clang-tidy to run on GitHub actions when I create a new branch just as it did on Travis.

### Current behavior:

Clang-tidy is not run

**Comment by nilsvu** [comment]
The reason I set up this behavior is that we are running clang-tidy only on modified files in a PR, not on all files in the repository. For pushes to a branch it's not so clear which files to check.

**Comment by kidder** [comment]
There is the script `.travis/RunClangTidy.sh` that was run on travis.

**Comment by nilsdeppe** [comment]
@nilsleiffischer This is still not working correctly. Files that are updated on develop but not on the fork are run through clang-tidy too. This means that erroneous errors can appear in the run.
