### ISSUE TITLE
Unit.IO.H5.VolumeData.Python tries to write to the source directory

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#1957]
In particular, it tries to write `tests/Unit/IO/VolTestData.h5`.

**Comment by isaaclegred** [comment]
This should hopefully be fixed by #2309 and #2318, the file `tests/Unit/IO/VolTestData.h5` will be able to be removed from source permanently when it is possible to write volume data from python.

**Comment by nilsdeppe** [comment]
We looked at this in a meeting together:
- `unit_test_path` points into `src`, propose rename to `unit_test_src_path`
- add function `unit_test_build_path` that points to `tests/Unit` in build directory. We can then write files into there

**Comment by wthrowe** [comment]
Fixed in #2542.
