### ISSUE TITLE
Python bindings should support building with shared libraries

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#1961]
# Bug report

Python bindings currently don't link correctly with the Charm++ compatibility code when building with shared libraries. This issue occurs both on current `develop` with boost.python and with the new pybind11 bindings in #1782. We probably have to carefully trace library dependencies through our CMake configuration and adjust their `PUBLIC`, `PRIVATE` and `INTERFACE` properties (see https://cmake.org/cmake/help/latest/command/target_link_libraries.html#libraries-for-a-target-and-or-its-dependents). It could also help if we defined "(imported) interface targets" (see https://cmake.org/cmake/help/latest/command/add_library.html#interface-libraries).

**Comment by nilsdeppe** [comment]
Here's the Charm++ compatibility changes:

```cpp
int _Cmi_numpes = 1;

double CmiWallTimer() {
  // TODO: make it throw
  return 0;
}

void pup_bytes(pup_er p,void *ptr,size_t nBytes) {
  // TODO Add throw here
}
```

Most issues were resolved by having Spectral depend on BLAS and LIBSHARP. A lot of things need to depend on YAML-CPP. The HDF5 wrapping code needs to depend on HDF5. That was enough to get everything except the TOV interface to behave.

**Comment by nilsvu** [comment]
Thanks @nilsdeppe that will be useful!
