### ISSUE TITLE
cmake list does not append to lists in the parent scope

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#20]
The cmake command
```
list(APPEND A_LIST STUFF_TO_APPEND)
```
will only append to `A_LIST` in the current scope. 

We need to fix this in multiple locations for adding external libraries.  
The proposed fix is to define a new cmake function 
```
append_to_list(...)
```
which uses the cmake function set which can modify a variable in the PARENT_SCOPE

**Comment by nilsdeppe** [comment]
We might be able to just use `set(SPECTRE_TESTS "${SPECTRE_TESTS};${UTILITIES_TESTS}" PARENT_SCOPE)`, for example.

**Comment by kidder** [comment]
This is actually not an issue for external libraries as the Setup*.cmake files are included into the top-level CMakeLists.txt and therefore the lists are in the global scope.
