### ISSUE TITLE
document git-hooks

### ISSUE THREAD

**Issue by haraldp271** [sxs-collaboration/spectre#21]
Add a few lines of documentation explaining that the git-pre-commit hooks are being set by cmake, and point to where this is done.  

This could go into a README.md file inside hooks/

Also, change the message printed by the clang-pre-commit-hook.   I suggest the following

<code>
Your commit does not follow the clang-format adopted by SpECTRE.   Please ensure you are formatting your C++ files before committing them.  Many editors/ides have commands to clang-format before or while saving.  Alternatively, you can first save all modified files, and then run 'git clang-format -f'.  
</code>

Perhaps even better, put that info on a documentation-page.  Then shorten the error message to
<code>
Your commit does not follow the clang-format adopted by SpECTRE.   Please ensure  C++ files are clang-formatted before committing them.  See <URL> for details. 
</code>

**Comment by kidder** [comment]
Fixed by #23
