### ISSUE TITLE
Unit.ApparentHorizons.StrahlkorperGr.DimensionfulSpinMagnitude fails on macOS

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2131]
# Bug reports:

The test `Unit.ApparentHorizons.StrahlkorperGr.DimensionfulSpinMagnitude` fails with an FPE in the `DGGEV` lapack call in `find_generalized_eigenvalues`.

### Environment:

CMake Version: 3.15.5
SpECTRE Version: 0.0.0
SpECTRE branch: mac_build_ci
SpECTRE hash: 56b3c41d116b4d8d7bb9eef9f169bd99bac34654
Hostname: nlf-mbp.local
Host system: Darwin-19.3.0
Host system version: 19.3.0
Host system processor: x86_64
CMAKE_CXX_FLAGS:  -fPIC
CMAKE_CXX_LINK_FLAGS: -Wl,-search_paths_first -Wl,-headerpad_max_install_names
CMAKE_CXX_FLAGS_DEBUG: -g
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS:  -fPIC
CMAKE_C_LINK_FLAGS: -Wl,-search_paths_first -Wl,-headerpad_max_install_names
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_LINK_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 11.0.0.11000033
CMAKE_C_COMPILER: /usr/bin/clang
CMAKE_C_COMPILER_VERSION: 11.0.0.11000033
CMAKE_Fortran_COMPILER: /usr/local/bin/gfortran-9
CMAKE_Fortran_COMPILER_VERSION: 9.2.0
Python Version: 3.7.6
Charm Version:  6.8.0
Charm SMP:  YES
BLAS_LIBRARIES:  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework
Blaze Version:  3.2
Boost Version:  1.72.0
Catch Version:  2.11.1
GSL Version:  2.6
HDF5 Version:  1.10.5
jemalloc Version:  5.2.1
LIBXSMM Version:  ..
LAPACK_LIBRARIES:  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework
NumPy Version:  1.18.1
SciPy Version:  1.4.1

**Comment by kidder** [comment]
you need to install a different blas library...  for me I installed openblas with spack
