### ISSUE TITLE
CMake sometimes can't find pthread on GitHub-hosted macOS runners 

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2168]
# Bug reports:

Occasionally CMake failed [FindThreads](https://cmake.org/cmake/help/latest/module/FindThreads.html) on `macos-latest` GitHub-hosted runners because it couldn't locate `pthread.h`. I couldn't reproduce the issue since we can't control which machine GitHub Actions run on. If we encounter the issue again, here are a few ideas we could try to resolve it:

- Make sure Xcode is set up correctly with `xcode-select --install`
- Install and find `openblas` in such a way that [FindBlas](https://cmake.org/cmake/help/latest/module/FindBLAS.html) doesn't even try finding a threading library, see also the [FindBlas code](https://github.com/Kitware/CMake/blob/master/Modules/FindBLAS.cmake). Here is how this can be done:
  - Install `openblas` without threading support (the default when installing with Spack)
  - Specify `-D BLA_VENDOR=OpenBLAS` when configuring cmake
  - Provide both `BLAS_ROOT` and `LAPACK_ROOT`

### Expected behavior:

`FindBlas` always succeeds on macOS builds with GitHub Actions

### Current behavior:

Sometimes `FindBlas` fails in `FindThreads`, see e.g. [this CI run](https://github.com/nilsleiffischer/spectre/runs/533775730?check_suite_focus=true):

```
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/local/Cellar/cmake/3.16.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.16.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.16.5/share/cmake/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/local/Cellar/cmake/3.16.5/share/cmake/Modules/FindBLAS.cmake:268 (find_package)
  cmake/SetupBlas.cmake:4 (find_package)
  CMakeLists.txt:62 (include)
```

### Environment:

GitHub's `macos-latest` runner, see output of [this CI run](https://github.com/nilsleiffischer/spectre/runs/533775730?check_suite_focus=true).

**Comment by nilsdeppe** [comment]
I haven't seen this for a while. Is it still an issue?

**Comment by nilsvu** [comment]
Haven't seen it either. Let's consider it resolved :)
