### ISSUE TITLE
Monitor and adjust caching on GitHub Actions

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2173]
# Feature request:

We should take another close look at GitHub's caching policy and limits and figure out a strategy to make optimal use of it. Here‘s the documentation:
- https://github.com/actions/cache#cache-limits
- https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [x] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
now tracked in #3352
