### ISSUE TITLE
Remove cpp17 namespace after migrating to C++17

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2194]
# Bug reports:

#2193 enables C++17 but doesn't remove `cpp17::void_type` and `cpp17::array` since those are not just trivial find-replace. In the long term both of those should be removed and replaced with the appropriate C++17 language features

- [x] Remove `cpp17::void_type`
- [x] Rename `cpp17::array` to `cpp20::array` (the `operator==`, etc. are not yet constexpr in 17).
- [x] Replace `boost::optional` with `std::optional`
- [x] Replace `boost::any` with `std::any`
- [x] Replace `boost::variant` with `std::variant`
- [x] `MakeOverloader` can be simplified by using a variadic `using` statement

**Comment by moxcodes** [comment]
Is it true that every use of `MakeOverloader` can be replaced with `if constexpr`s now that we're on C++17? Or is there other behavior of `MakeOverloader` that we'll need to keep in some cases?

**Comment by nilsdeppe** [comment]
Mostly true. The one case, which I don't know if we actually use it, is if the resulting function object is passed around or stored. If you're asking about AlgorithmImpl, yes, it can be significantly simplified with `if constexpr` :)

**Comment by fmahebert** [comment]
Recent PRs #2392 and #2450 have removed our use of `namespace cpp17`, so the first two items in the item description list can be checked off 🙂.

In addition to the `boost`-related items left above, a search for "C++17" in the codebase reveals a few minor items that can also be updated. I will take a stab at these (the C++17 mentions; I'm not at this time planning to take on the boost replacements).

**Comment by fmahebert** [comment]
PRs #2685 #2736 #2753 have replaced boost::optional with std::optional, so another item can be checked off here.

**Comment by nilsdeppe** [comment]
Yay! :D Thank you!
