### ISSUE TITLE
NumericalFlux protocol imposes incorrect restrictions

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2204]
# Bug reports:

### Expected behavior:

It's possible to have tags in the Variables that are not DataBox tags. This is the actual interface of the numerical fluxes.

### Current behavior:

Tags in the Variables must be DataBox tags.

**Comment by wthrowe** [comment]
Not according to the documentation:
> A Variables holds a contiguous memory block with Tensors pointing into it.
> 
> The Tags are structs that must have a public type alias type whose value must be a Tensor<DataVector, ...>, a `static' method name() that returns a std::string of the tag name, and must derive off of db::SimpleTag. In general, they should be DataBoxTags that are not compute items.

And it uses `db::remove_all_prefixes`, which I think only works on simple tags.

(I remember being annoyed by this restriction at some point, although I can't remember why.)

**Comment by nilsdeppe** [comment]
Hmm, so I think the one call to `db::tag_name` would add that requirement, but it would be easy enough to add a wrapper that dispatches to that only if there's no `name` function. I don't remember if `remove_all_prefixes` checks anything about what things are inherited from, but I don't know how else it would work. Though that could probably also be relaxed.
