### ISSUE TITLE
Disable Rational and TimeDelta math with doubles

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2209]
# Bug reports:

### Expected behavior:

Math operations between `Rational` and `TimeDelta` should result in a compiler error. This can be achieved by explicitly deleting them:
```cpp
TimeDelta operator*(TimeDelta a, double b) noexcept = delete;
TimeDelta operator*(double a, TimeDelta b) noexcept = delete;
```

### Current behavior:

Currently if we multiply `TimeDelta` or `Rational` by a `double` the `double` is silently converted to an integer (not a rational) which results in incorrect values. For example, in the `DormandPrince5` stepper we have
```cpp
gsl::at(_c, step) * time_step
```
where `_c` is an array of `double`s and `time_step` is a `TimeDelta`. All the `_c`s are less than 1 and so the result is always zero.

**Comment by nilsdeppe** [comment]
@wthrowe could you comment with your thoughts of the proposed solution of deleting the operators?

**Comment by wthrowe** [comment]
Yes, that operation should not be allowed.  You probably also need to delete `operator/(TimeDelta, double)`.

**Comment by nilsdeppe** [comment]
Okay, sounds good. I was thinking disable all binary math operations with `double`s, including `operator+` and `-` just to be on the safe side. Does that sound okay?

**Comment by wthrowe** [comment]
Oh, yeah, do those too.  And make sure the assignment versions are caught as well.  I don't think there should be any way to combine these types with doubles.
