### ISSUE TITLE
Remove protocols

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2214]
# Feature request:

We remove `protocols`. I've found they actually make development more difficult than easier. For example, if something is wrong with a numerical flux I get the message `The numerical flux does not conform to the dg::protocols::NumericalFlux` message, but have no idea what's actually wrong. If we instead let the compiler try to build the flux into the tests I would've gotten a message like `has no member variables_tags` or `unable to call operator() with arguments...`. Is it stands, every time a protocol fails, I have to comment out each individual check until I figure out which failed. This is silly and not at all helpful.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

**Comment by nilsvu** [comment]
I understand your issue, and also found that annoying to deal with. How about we try this first: https://github.com/sxs-collaboration/spectre/issues/2205. With that, the error messages should be better than the standard compiler failures

**Comment by nilsdeppe** [comment]
I would rather just see them removed This seems like a lot of work with what to me seems to be significant downsides and minimal upsides.

**Comment by nilsdeppe** [comment]
The issues I ran into have been addressed, I think. I'll re-open if I run into more issues.
