### ISSUE TITLE
macOS CI builds fail to find libsharp

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2304]
# Bug reports:

I have repeatedly seen the macOS builds on CI fail to find libsharp recently. Here's an example: https://github.com/sxs-collaboration/spectre/runs/727841416?check_suite_focus=true
If anyone has information on this, please let me know. Else I'll try to debug the issue once I find the time.

**Comment by fmahebert** [comment]
This failure seems to occur consistently, and it isn't helping the signal/noise from our CI builds... What would you think of turning off the macOS CI builds until this is resolved?

**Comment by nilsvu** [comment]
Yep that sounds like a good idea to me, I'll put in a PR to disable the macOS build temporarily now

**Comment by nilsvu** [comment]
Actually I found the commit that broke our builds: https://github.com/spack/spack/commit/3896a401db18e0c84984df88ce094a1a601ad743

Fixed in this PR: https://github.com/sxs-collaboration/spectre/pull/2314
