### ISSUE TITLE
Propagate errors to Python

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2312]
Calling `ERROR` when using Pybindings currently crashes the Python kernel and the message is printed to the terminal. Ideally the error would propagate to Python as a runtime exception instead so Python can exit gracefully or the exception can be handled.

**Comment by isaaclegred** [comment]
One thing that might work but would be rather slow would be explicitly checking whether the calls will succeed inside of the python wrappers, then throwing a python error before the c++ call is ever made.  This would avoid the need for special case handling, and it has some precedent with `PythonBindings/BoundChecks.cpp`

**Comment by nilsvu** [comment]
@isaaclegred if I understand correctly you suggest checking for possible errors in Pybindings code before they occur. For bounds checks and such this is certainly feasible and a good way of providing useful error messages when calling Pybindings, but we can't repeat all possible `ERROR`s that may occur further down in function calls. For example, say we call the TOV analytic solution from Python that does a numerical ODE solve which may fail. The Pybindings code has no way of knowing under what conditions the ODE solve will fail. Instead, the TOV solution aborts with an `ERROR` that describes the issue. We need to re-route this error message as an exception to Python.

**Comment by isaaclegred** [comment]
Ah yes I just read through your convo in the slack channel.  Seems like https://github.com/UIUC-PPL/charm4py has some way of handling this, in particular in https://github.com/UIUC-PPL/charm4py/blob/master/charm4py/charmlib/ccharm.pxd they can somehow translate `CmiAbort` calls to python.

**Comment by nilsvu** [comment]
I believe this is resolved by #3838 🎉
