### ISSUE TITLE
Observers with same ObservationId

### ISSUE THREAD

**Issue by tomwlodarczyk** [sxs-collaboration/spectre#2363]
# Bug reports:

### Expected behavior:

In SolveElasticityProblem.hpp I have added an additional event for ObserveVolumeIntegrals. In the .h5-file under each ObservationId I should find both ErrorNorms and VolumeIntegrals. 
The changes are:
- in `SolveElasticityProblem.hpp`:
```
using events = tmpl::list<
      dg::Events::Registrars::ObserveFields<
          volume_dim, linear_solver_iteration_id, observe_fields,
          analytic_solution_fields>,
      dg::Events::Registrars::ObserveErrorNorms<linear_solver_iteration_id,
                                                analytic_solution_fields>,
      dg::Events::Registrars::ObserveVolumeIntegrals<
          volume_dim, linear_solver_iteration_id,
          tmpl::list<Elasticity::Tags::PotentialEnergyDensity<volume_dim>>>>;
``` 

- in the .yaml-file:
```EventsAndTriggers:  
  ? EveryNIterations:  
      N: 50
  : - ObserveFields
    - ObserveErrorNorms
    - ObserveVolumeIntegrals
```

### Current behavior:

If I trigger both ObserveErrorNorms and ObserveVolumeIntegrals in the same iteration, the ErrorNorms are missing. When triggering the events for separate Iterations both Datasets are present. The following works as exptected:
```EventsAndTriggers:
  ? EveryNIterations:
      N: 50
  : - ObserveFields
  ? EveryNIterations:
      Offset: 0
      N: 50
  : - ObserveErrorNorms
  ? EveryNIterations:
      Offset: 25
      N: 50
  : - ObserveVolumeIntegrals
```

### Environment:

CMake Version: 3.16.3
SpECTRE Version: 0.0.0
SpECTRE branch: Elasticity
SpECTRE hash: d0672a756107e738f6710a6b8dea7032729c1939
Hostname: login02.cluster
Host system: Linux-3.10.0-514.26.2.el7.x86_64
Host system version: 3.10.0-514.26.2.el7.x86_64
Host system processor: x86_64
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS:  -L/work/charm/multicore-linux64-clang/lib -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/bin/clang++-9
CMAKE_CXX_COMPILER_VERSION: 9.0.1
CMAKE_C_COMPILER: /usr/bin/clang-9
CMAKE_C_COMPILER_VERSION: 9.0.1
CMAKE_Fortran_COMPILER: /usr/bin/gfortran-8
CMAKE_Fortran_COMPILER_VERSION: 8.4.0
Python Version: 3.8.2

# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
I'm currently working on this. I have it working in the Burgers executable and am updating the tests. You can currently only do one reduction and volume observation.

**Comment by nilsvu** [comment]
#2436 resolved this. Thanks, @nilsdeppe !
