### ISSUE TITLE
git hook for ClangFormat apparently requires you to commit in SPECTRE_HOME.

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#238]
When committing, I got the usual warning from the ClangFormat hook:

WARNING:
ClangFormat found differences. The diff output has been written to
'/home/scheel/Code/Spectre/spectre/.clang_format_diff.patch'
You can apply the patch as is using:
git apply /home/scheel/Code/Spectre/spectre/.clang_format_diff.patch
then staging the modified files and amending your original commit.

But when I did the 'git apply...' command, it did nothing.  Nothing got modified or staged.
The problem appeared to be that I was committing in SPECTRE_HOME/tests/Unit and some of the changed files were in SPECTRE_HOME/src.

I then committed in SPECTRE_HOME, got the same warning, but there the 'git apply...' command did correctly modify and stage files.

Of course we could just require that everyone commits in SPECTRE_HOME, but this was unexpected
(to me).

**Comment by nilsdeppe** [comment]
I believe this is just how git patches work. @wthrowe any insight?

**Comment by wthrowe** [comment]
git-apply won't modify anything outside the current directory, so I don't think there's much we can do about that.  Testing, it doesn't seem to matter what directory the commit was made from, so it will work to change to the top level after seeing the message and then do the apply.

You could write an alias to do the apply from the correct directory.  Something like (untested) `git config --add alias.apply-cf '!cd "$(git rev-parse --show-toplevel)" && git apply .clang_format_diff.patch'` should make `git apply-cf` apply the patch no matter where in the repo you are.

**Comment by kidder** [comment]
I would suggest that we amend the warning from the hook to tell you to cd into SPECTRE_HOME in order to apply the patch

**Comment by nilsdeppe** [comment]
@markscheel would you mind improving the message to be reflect that the apply command needs to be run from `SPECTRE_HOME`?

**Comment by nilsdeppe** [comment]
@markscheel progress update?

**Comment by kidder** [comment]
@markscheel progress update?
