### ISSUE TITLE
BLAS segfaults in parallel Charm++ runs

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2394]
# Bug reports:

The OpenBLAS in the Docker container (as of today) segfaults in calls such as `dgetrf` in parallel Charm++ runs, i.e. when running the executable with e.g. `+p2`. I haven't tried reproducing this in any of the executables in `develop`, but encountered it in new code and noting it down in this issue to perhaps save someone else some debugging time. The issue is resolved by setting this environment variable:

```
export OPENBLAS_NUM_THREADS=1
```

**Comment by wthrowe** [comment]
We don't want BLAS running multiple threads anyway, do we?  We're doing our own threading.

**Comment by nilsvu** [comment]
@wthrowe I think that's right. I'll put in a PR that sets this environment variable in the container and updates the installation instructions. We could also call the configuration function that's mentioned in the FAQ linked above, but I'm not sure when and where.

Edit: I realised I didn't put the FAQ link into the description, so here it is: https://github.com/xianyi/OpenBLAS/wiki/Faq#multi-threaded

**Comment by wthrowe** [comment]
Fixed by #2463.
