### ISSUE TITLE
Mac OSX CI build is broken

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#2397]
# Bug reports:

### Expected behavior:

Tests pass

### Current behavior:

Linking fails with
```
[100%] Linking CXX executable ../../bin/RunTests
Fatal Error by charmc in directory /Users/runner/work/spectre/spectre/build/tests/Unit
   file with unrecognized extension /Applications/Xcode_11.6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd
charmc exiting...
```

### Environment:

To reproduce, run the MacOsX workflow 

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

**Comment by kidder** [comment]
- This appears to have started with the following update to the mac environment on GitHub actions `Environment: macos-10.15
  Version: 20200716.2`
- The unrecognized file is in the list of HDF5_LIBRARIES that cmake generates.  Previous to the above change in the GitHub Action environment, the unrecognized files was not in HDF5_LIBRARIES
- I have tried building hdf5 with spack instead of homebrew.
- I tried building with older versions of hdf5
- I tried building with either static or shared libraries
- This may be related to this charm++ issue https://github.com/UIUC-PPL/charm/issues/2495 but building on my charm 6.10.1 branch this error still occurs

**Comment by nilsvu** [comment]
This issue was resolved yesterday by https://github.com/UIUC-PPL/charm/pull/3046. The macOS build works now when using charm's `master` branch.

**Comment by nilsdeppe** [comment]
We don't use macOS in CI anymore.
