### ISSUE TITLE
Update documentation on CI

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2421]
The documentation on CI is still about Travis. It should be updated to GitHub Actions. I'm happy to do that when I'm back from vacation.

**Comment by fmahebert** [comment]
Semi-relatedly, we also still have `.travis` files in the repo.

**Comment by nilsdeppe** [comment]
@nilsleiffischer that would be great! I would guess it's not much more work than renaming Travis to GitHub Actions?

@fmahebert yes probably at this point that would be safe. We would likely need to completely redo the whole file between Travis changes and build system changes on our end.
