### ISSUE TITLE
Update environments for Charm 6.10.2

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#2422]
We still need to update these environments (in `support/Environments`) for Charm 6.10.2

- [x] frontera
- [x] minerva
- [x] ocean / orca (partially updated)
- [x] wheeler
- [ ] ~compute_canada~
- [ ] ~bluewaters~
- [ ] ~zwicky~

Edited: Oct 21

**Comment by nilsdeppe** [comment]
what's the status on this? Complete? Won't fix? Delete unavailable systems?

**Comment by fmahebert** [comment]
I've updated the checklist. Todo still
- update minerva (I don't know who's responsible)
- update some of the ocean environments, ping @geoffrey4444

**Comment by nilsvu** [comment]
I'll update Minerva

**Comment by geoffrey4444** [comment]
I will make a PR next chance I get that switches to charm 6.10.2 on ocean

**Comment by nilsdeppe** [comment]
All are updated.
