### ISSUE TITLE
The elliptic solver includes are incorrect

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2425]
# Bug reports:

There are a lot of type aliases that are difficult or impossible to track
down. This is, as far as I can tell, because the includes in the files are
incomplete. For example, the type alias `observe_detail::Registration` in
`ConjugateGradient.hpp` is not in any of the included files. I think the very
stringent adherence to DRY (Don't Repeat Yourself) in the elliptic solver
actually makes the code more difficult to navigate, but in this case it would at
least be improved if the includes were correct. Of course I can search for
"Registration" throughout the entire code base, but that's not exactly how I
think we should be navigating the project. I believe this is a fundamental issue
with the includes in the elliptic solver, and maybe even with the design of the
elliptic code. I think that if I'm struggling to follow the code, it needs to be
simplified significantly.

**Comment by nilsvu** [comment]
In a call with @nilsdeppe in response to this issue we identified #2186 as a source of confusion in how the parallel linear solvers operate.
