### ISSUE TITLE
Provide a make target to build all libraries

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#2444]
We have a "libs" target, but that doesn't seem to do the test libraries, which are most of the code.

My use case is building the libraries with high parallelization, and then building/linking the executables with low parallelization to limit the RAM use.

**Comment by nilsdeppe** [comment]
Just for clarification: how do you envision this being different from `RunTests`? There are a few extra executables that aren't part of `RunTests`, but I think that's only maybe 10 or so at most. Should those extra test executables be built as part of the `libs`? Or do you strictly want to avoid building the `RunTests` executable and just the libs? I usually build `RunTests` with high parallelization and then `test-executables` with low right after

**Comment by wthrowe** [comment]
Yes, RunTests is good enough.  And now that you mention it, I've used that trick before and forgot about it.
