### ISSUE TITLE
NodeLock.cpp is recompiled for every executable

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#2446]
I don't see any indication in NodeLock.cpp, NodeLock.hpp, or the corresponding CMakeLists.txt that this is intentional, so I assume it is a bug.

**Comment by nilsdeppe** [comment]
@moxcodes I think you wrote this file. Could you take a look to see what's happening?

**Comment by moxcodes** [comment]
Yep, that's no doubt my fault somehow. I'll have a look soon.
