### ISSUE TITLE
ParaView crashes when bases and quadratures are enabled

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2464]
# Bug reports:

1. Compile `ExportCoordinates3D`
2. Run with the `tests/InputFiles/ExportCoordinates/Input3D.yaml` input file
3. Run `GenerateXdmf.py` over the resulting volume data file
4. Open in ParaView 5.8, select "XDMF Reader"
5. Click "Apply", leaving the "Point Arrays" `bases` and `quadratures` enabled

### Expected behavior:

ParaView shows the 3D domain. 

### Current behavior:

ParaView crashes. Disabling `bases` and `quadratures` before clicking "Apply" resolves the issue.

### Environment:

- Compiled and run in Docker container on `develop`
- Opened in ParaView 5.8 on macOS

```
# LibraryVersions.txt
CMake Version: 3.16.3
SpECTRE Version: 0.0.0
SpECTRE branch: vscode
SpECTRE hash: 096058dfc90d594476e0e14c0a5f7ec0aad1403a
Hostname: 1a5f93c873af
Host system: Linux-4.19.76-linuxkit
Host system version: 4.19.76-linuxkit
Host system processor: x86_64
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS:  -L/work/charm_6_10_2/multicore-linux-x86_64-clang/lib -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/bin/clang++-10
CMAKE_CXX_COMPILER_VERSION: 10.0.0
CMAKE_C_COMPILER: /usr/bin/clang-10
CMAKE_C_COMPILER_VERSION: 10.0.0
CMAKE_Fortran_COMPILER: /usr/bin/gfortran-8
CMAKE_Fortran_COMPILER_VERSION: 8.4.0
Python Version: 3.8.2
```

**Comment by nilsvu** [comment]
@isaaclegred any ideas on this?

**Comment by nilsdeppe** [comment]
Isaac is no (currently) longer in the group, so please discuss this with me instead.

The quadrature and basis shouldn't be made visible by `GenerateXdmf`. It makes no sense to read them in as a field because they aren't written that way. They are stored in the same way that the `extents` is stored.
