### ISSUE TITLE
add_compile_definitions requires cmake 3.12+

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#2483]
# Bug reports:

### Expected behavior:

When I rebase on develop I don't have any problems unless I'm told about a breaking change

### Current behavior:

I rebase on develop and I can't compile because `add_compile_definitions` was added in #2463 which requires cmake 3.12 when our installation instructions say we support cmake 3.8

**Comment by nilsvu** [comment]
How can we avoid this in the future, should we add a CI build with our minimum cmake version?

**Comment by nilsdeppe** [comment]
That could work... Shouldn't be too terrible to add
