### ISSUE TITLE
Unit.PointwiseFunctions.AnalyticSolutions.Elasticity.HalfSpaceMirror times out often

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2566]
# Bug reports:

This test times out a lot for me. I don't know why testing an analytic solution would be this expensive... Even Kerr-Schild doesn't have this problem.

**Comment by nilsdeppe** [comment]
Here's of it showing up in CI: https://github.com/sxs-collaboration/spectre/runs/1318587809?check_suite_focus=true

**Comment by nilsvu** [comment]
Thanks for pointing to the CI run. I'll take a look at what can be done to make the test faster. I think the slow part is the test that the solution numerically solves the system, and does so with exponential scaling. The reason this is slow is that the solution must compute numerical integrals at every grid point. Perhaps we don't need to test the exponential scaling but just check the solution for a single mesh, that would probably be sufficiently fast.

**Comment by nilsdeppe** [comment]
Ping on this. We have had it happen yet again (and it does so every time I run tests on my machine...) https://github.com/sxs-collaboration/spectre/pull/2616/checks?check_run_id=1521719620
