### ISSUE TITLE
Rename AlgorithmImpl -> DistributedObject

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#2639]
# Feature request:

ActionTesting has something called MockDistributedObject that mocks AlgorithmImpl.  The names should be made to agree, so that a class `MockBla` mocks a class called `Bla`.

Not doing this rename now because of conflicts with ongoing PRs.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

**Comment by moxcodes** [comment]
@markscheel Now that #2616 has been merged, this rename won't cause as many conflicts (but now will also probably need to be applied to the names in `src/Parallel/Algorithms` to be consistent)

**Comment by nilsdeppe** [comment]
@markscheel here's the issue we talked about today :)
