### ISSUE TITLE
CoordinateMap::inverse should return std::optional, not boost::optional.

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#2653]
We have been switching to std::optional recently.
Fixing this issue should be easy but affects all CoordinateMaps and everything that uses the inverse function of CoordinateMap, so it should be done in one PR by itself to avoid conflicts.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

**Comment by fmahebert** [comment]
Done in PR #2685
