### ISSUE TITLE
Suggested values output combines with other outputs in misleading ways

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#2655]
# Bug reports:

### Expected behavior:

Spectre's output to terminal is easy to understand

### Current behavior:

Running the `EvolveGhKerrSchild` executable with the `KerrSchild.yaml` input file produces misleading output. It looks as if the "AhA" diagnostics are a suggested-value problem, but the two are independent.

```
The following options differ from their suggested values:
AhA: its=0: 2.0e-01<R<2e-01, |R|=0.2, |R_grid|=0.2, 2.2<r<2.2
AhA: its=1: 6.9e-02<R<1e-01, |R|=0.09, |R_grid|=0.09, 2.082<r<2.084
AhA: its=2: 2.1e-02<R<5e-02, |R|=0.04, |R_grid|=0.04, 2.034<r<2.036
...
```

**Comment by wthrowe** [comment]
What do you think would be a better output?

The option parser could print some sort of end message out in its destructor.  (There's no concept of "done parsing" other than that.)

There might also be problems with the horizon finder output not being clear enough, but this particular problem seems more the fault of the option parser.

**Comment by nilsvu** [comment]
How about just printing `\n---\n` after option-parsing is done? As an alternative to the destructor you could print a section-header like `Option parsing\n--------------` in `Main` before option-parsing begins and then `\n---\n` once it's done (or variations of these strings).

**Comment by moxcodes** [comment]
Another note for this is that it might be nice to only print the `The following options differ from their suggested values:` when there are any that differ from suggested values (currently, it prints regardless I think)

**Comment by wthrowe** [comment]
> How about just printing `\n---\n` after option-parsing is done? As an alternative to the destructor you could print a section-header like `Option parsing\n--------------` in `Main` before option-parsing begins and then `\n---\n` once it's done (or variations of these strings).

I like the idea of handling it in Main.  Then we don't have to worry about potential interactions of parse errors with stack unwinding.

> Another note for this is that it might be nice to only print the `The following options differ from their suggested values:` when there are any that differ from suggested values (currently, it prints regardless I think)

I haven't been able to come up with a way to do this, unfortunately.

**Comment by fmahebert** [comment]
I worry that a `----` string isn't very clear. Adding a copy before the "suggested values" message, to me, just makes it confusing about whether you're "closing" the "scope" from the first `----` or from the preceding text:
```
Option parsing:
----
The following options differ from their suggested values:
----
```

I would favor a blank line, then a message like "Option parsing completed" or "Entering SpECTRE phases" or...

(But I don't love my suggestion either. Too bad it's difficult to avoid printing the suggested values message...)
