### ISSUE TITLE
Pup'ing a unique_ptr of CoordinateMap fails. 

### ISSUE THREAD

**Issue by osheamonn** [sxs-collaboration/spectre#266]
The following code fails: 
`using rotate3d = CoordinateMaps::Rotation<3>;
const std::unique_ptr<CoordinateMapBase<Frame::Logical, Frame::Grid, 3>> x =
      std::make_unique<A>(
          make_coordinate_map<Frame::Logical, Frame::Grid>(rotate3d{}));
  serialize_and_deserialize(x);` 

with reason: Unrecognized PUP::able::PUP_ID. Is there an unregistered module? 

This comes up in trying to pup Domain. Confusingly pup'ing Block seems to work despite also containing a unique_ptr to CordinateMap.

**Comment by kidder** [comment]
The following is in Test_Block where pup'ing the Block is tested:

 ` PUPable_reg(SINGLE_ARG(CoordinateMap<Frame::Logical, Frame::Grid,
                                       CoordinateMaps::Identity<Dim>>));`

Also what is the `<A>` after `std::make_unique` in your snippet?

**Comment by osheamonn** [comment]
Ah I didn't catch that. That should fix it. And the A was a type alias to a CoordinateMap that I forgot to remove/copy-paste into the snippet.

**Comment by osheamonn** [comment]
Alright that'll do it... I hadn't noticed that was necessary. And the A was a type alias to CoordinateMap<... Rotated> that I forgot to remove or copy-paste.
