### ISSUE TITLE
make_vector does not work on Wheeler

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#267]
I hit an STL internal static_assert with make_vector using GCC 5.3.0 on Wheeler.

**Comment by nilsdeppe** [comment]
As far as I can tell this might actually be a bug in libstdc++'s implementation of vector.

**Comment by wthrowe** [comment]
I test with 5.4.0 on my machine and that version seems fine.

**Comment by nilsdeppe** [comment]
@wthrowe and I discussed changing our required GCC compiler versions to 5.4, 6.4, or 7.1 and newer. This would address several other GCC bugs and if change logs are to be believed, allow for #225 to be merged as well. #225 would eliminate the need for the static constexpr cstrings inside DataBoxTags, making them easier to use.

@wthrowe and I discussed the implications of this change, the biggest being on some clusters we will need to compile GCC 5.4 (can be done using spack) or 6.4. Both will be ABI compatible with system modules compiled with GCC 5.x, we'd need to build GCC 6.4 if the system GCC is 6.x. The only modules we will really want from the system are OpenMPI (since this will have hopefully been tuned for the cluster) and HDF5. There may also be a good system BLAS library, but with libxsmm we shouldn't really need that, except maybe on spherical shells.

@kidder could you note your thoughts on this?

**Comment by nilsdeppe** [comment]
I've installed GCC 6.4.0 and LLVM 5.0.1, as well as all other modules we depend on so this is solved. We should bump the required version to GCC 5.4.0, though. I can put in a PR for that and then we can close this.
