### ISSUE TITLE
Travis builds fail with illegal instructions

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#270]
Our Travis Linux builds nondeterministicly fail with illegal instruction errors.  We are guessing that this is due to Travis running builds on different hardware, which will break if ccache supplies an object file containing instructions the current host does not understand.

Under the assumption that we have diagnosed the problem correctly, we should be able to solve it by getting ccache to not use object files on different CPUs than they were built for.  I think the easiest way to do this would be to include the information in ccache's compiler ID hash.  According to [ccache(1)](https://ccache.samba.org/manual.html) this can be done by setting the environment variable `CCACHE_COMPILERCHECK='%compiler% -dumpmachine; %compiler% -dumpversion; uname -p'`.

I am not sure how to do this in our Travis setup, and since a failure to do it correctly would be indistinguishable from just failing to solve the problem, I'm going to let someone who understands that stuff better try this.

**Comment by wthrowe** [comment]
This is still happening.  The fact that my attempt in #287 didn't solve this makes me wonder if our guess as to the cause is wrong.

**Comment by nilsdeppe** [comment]
I haven't seen this in a while now. Has this decreased/gone away again?

**Comment by kidder** [comment]
seems to have gone away
