### ISSUE TITLE
Can't find pybind11

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2705]
# Bug reports:

I have pybind11 installed in `/usr/local/include/pybind11` and now it can't be found. 
```
CMake Error at cmake/SetupPybind11.cmake:22 (find_package):
  Could not find a package configuration file provided by "pybind11"
  (requested version 2.6.0) with any of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:95 (include)
```
This is a regression in #2672 as far as I can tell. We can't rely on any CMake modules being provided. This will be a complete disaster on supercomputers. All we should need is the include directory (this is the whole benefit of header-only libs)

**Comment by nilsdeppe** [comment]
@nilsleiffischer and I discussed this in direct messages. The conclusion was that installing via pip and a virtual env should work fine on HPC systems since we can then create a module that points directly to the installed pybind11 (no need to lead a virtual env since I've had trouble with doing that when submitting batch jobs). This is easier than dealing with copying files manually and should work pretty much everything. I think we should mention in our installation instructions that the CMake files pybind11 supplies are needed in addition to the header files.

**Comment by nilsvu** [comment]
Should be even easier with #2707. This works on frontera:

```sh
python3 -m venv py_env && ./py_env/bin/pip install pybind11
cmake -D Python_EXECUTABLE=path/to/py_env/bin/python ...
```
