### ISSUE TITLE
Test_ComplexDataVectorBinaryOperations.cpp takes 10 minutes to build

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2717]
# Bug reports:

I'm using GCC-10 in release mode with debug symbols on Ubuntu 20.10:
```
cmake -GNinja -D CHARM_ROOT=/home/nils/SpECTRE/charm/netlrts-linux-x86_64-smp-gcc \
  -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 \
  -D DEBUG_SYMBOLS=ON -D BUILD_SHARED_LIBS=ON -D CMAKE_BUILD_TYPE=Release \
  -D BUILD_PYTHON_BINDINGS=ON /home/nils/SpECTRE/spectre
```
and `LibraryVersions.txt`:
```
CMake Version: 3.18.2
SpECTRE Version: 2020.12.7
Git description: 
Git branch: container_updates
Git hash: 759a5d50fc39638aa04441c5db7ac6c44b790d50
Hostname: nilser
Host system: Linux-5.8.0-31-generic
Host system version: 5.8.0-31-generic
Host system processor: x86_64
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS:  -L/home/nils/SpECTRE/charm/netlrts-linux-x86_64-smp-gcc/lib -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Release
CMAKE_CXX_COMPILER: /usr/bin/g++-10
CMAKE_CXX_COMPILER_VERSION: 10.2.0
CMAKE_C_COMPILER: /usr/bin/gcc-10
CMAKE_C_COMPILER_VERSION: 10.2.0
CMAKE_Fortran_COMPILER: /usr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 10.2.0
Python Version: 3.8.6
```
I'm curious if this can be reproduced on other systems. I would say this is an unacceptably long build time for a single file. I don't think it takes this long with debug symbols off (I haven't tried, but it built in CI, which is a good sign). This is almost the exact same setup that the container has.

I'm not sure that splitting the file up is really the right solution here, since it's likely the proliferation of intermediate types created by the test that is the problem. One way of reducing that is to have a `BinOp` class that replaces the:
```cpp
std::make_tuple(funcl::Divides<>{}, std::make_tuple(generic, positive))
```
taking in its constructor this information (i.e. runtime info as to what operator to use). Another thing that could help is changing the `TestKind` information to runtime. Looking through the test, I think the issue likely just boils down to many nested `tmpl::for_each`-type operations that creates likely thousands of functions and types. I'm not sure how long the `std::tuple`s end up getting, but `std::tuple` (in the libstdc++ implementation) scales impressively poorly (but ABI compatibility means we are likely 10+ years away from a rewrite). I'm hoping this isn't a Blaze compilation time explosion issue.

I think the action items are:
- [ ] verify this isn't something weird with my system by testing on different machine
- [ ] test with newest Blaze (@moxcodes's PR should be useful for this)
- [ ]  assuming issue persists in newest Blaze, reduce number of `std::tuple`s generated by using more runtime info

**Comment by moxcodes** [comment]
On my machine, I got about 12 minutes to build all of `Test_DataStructures` (on a bare build directory and after clearing `ccache`). Putting `Test_ComplexDataVector` into the `RunSingleTest/CMakeLists.txt`, my overall build time from a bare build directory and after clearing `ccache` is about 55 seconds. (I used `-j12` for the number of concurrent threads my machine supports -- using only 1 core, the build time is 1:35; unsurprisingly, building just the one test does not parallelize well...)
I built in the container and my `LibraryVersions.txt` is:
```
CMake Version: 3.18.2
SpECTRE Version: 2020.12.7
Git description: 
Git branch: develop
Git hash: cd38a7a7fc27162fe872157fe45f089436f842b9
Hostname: c7325c12d9df
Host system: Linux-5.6.10-gentoo
Host system version: 5.6.10-gentoo
Host system processor: x86_64
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS:  -L/work/charm_6_10_2/multicore-linux-x86_64-gcc/lib -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Release
CMAKE_CXX_COMPILER: /usr/bin/g++-10
CMAKE_CXX_COMPILER_VERSION: 10.2.0
CMAKE_C_COMPILER: /usr/bin/gcc-10
CMAKE_C_COMPILER_VERSION: 10.2.0
CMAKE_Fortran_COMPILER: /usr/bin/gfortran-10
CMAKE_Fortran_COMPILER_VERSION: 10.2.0
Python Version: 3.8.5
```

Now, I don't disagree that these vector tests take too long to build and I think that the assessment that it is the combinatoric set of types and functions that are generated by the `tmpl::for_each` trickery is the cause of the long build time. We should get to the bottom of why your setup is taking so much longer, though -- do you think there's any chance it could be the netlrts charm build you're linking?

**Comment by moxcodes** [comment]
oops, sorry -- I totally misread which test you were saying is slow to build. Making `Test_ComplexDataVectorBinaryOperations.cpp` the single test that's built, I instead end up with about 9:40 build time, so consistent with what you're seeing, and about half of that was spent in the assembler phase, which seemed a bit unusual -- maybe an indication of the explosion of function definitions.

I'll make it a priority to convert these to runtime loops and parameters to improve the build time.
