### ISSUE TITLE
Git errors when running CMake

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#2719]
# Bug reports:

I get the following error:
```
fatal: No annotated tags can describe '761913b801cc4321ec60cb4d25e89d5b988d6d15'.
However, there were unannotated tags: try --tags.
```
I haven't tried to track down the exact circumstances, but this is on a branch with one extra commit on top of develop. This is a new development, and if I remember correctly there were some changes to the git information recently by @nilsleiffischer which I assume are the cause of this.

My environment is essentially that of the container (I'm using Ubuntu 20.10 instead of 20.04), so I expect it's reproducible there. There is an error in CI:
```
fatal: No names found, cannot describe anything.
```
which I think is essentially the same issue.

**Comment by nilsvu** [comment]
- I assume this occurs when running cmake in a repo that hasn't fetched tags, e.g. when only cloning a particular branch? Could you confirm or give details when this issue occurs, or how to reproduce it? Recent CI runs pass on develop, on PRs and on my fork.
- We should probably just add `--always` to the `git describe` in the build system so it falls back to the commit hash, as well as `--first-parent` and maybe `--match v*` while we're at it. I'll put in a PR.
- We should also make sure we're tagging releases with annotated tags. I know the v2020.12.07 tag is annotated, but I'll check the CI workflow to make sure upcoming releases create annotated tags.
