### ISSUE TITLE
Warning in workflow_dispatch CI runs

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#2852]
I don't know whether it matters, but our workflow_dispatch CI runs print the warning "Warning: Event Validation Error: The event type workflow_dispatch is not supported. Only push, pull_request events are supported at this time." in the "Post Restore ccache" phase.  Here's a current example, although I don't know how long these logs are kept for: https://github.com/sxs-collaboration/spectre/runs/1855523573

**Comment by nilsvu** [comment]
This will just need an upgrade to `actions/cache@v2`. The upgrade can be done in-place I think, by just bumping the version number.

**Comment by nilsvu** [comment]
done in https://github.com/sxs-collaboration/spectre/pull/2854. BTW it looks like we have 5GB of cache now :)
