### ISSUE TITLE
Random failure in Unit.Domain.CoordinateMaps.CylindricalEndcap

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#2879]
# Bug reports:

### Expected behavior:

Test doesn't fail

### Current behavior:

Test fails with 
```
/__w/spectre/spectre/tests/Unit/Helpers/Domain/CoordinateMaps/TestMapHelpers.hpp:174: FAILED:
  CHECK( gsl::at(gsl::at(expected_identity, i), j) == approx(i == j ? 1. : 0.) )
with expansion:
  -0.0000000000000302 == Approx( 0.0 )
with messages:
  CylindricalEndcap
  Seed is: 2824750152 from /__w/spectre/spectre/tests/Unit/Domain/
  CoordinateMaps/Test_CylindricalEndcap.cpp:21
  center_one := { -0.85538704758621464, -0.649336057119412, 0.35899907476230597
  }
  center_two := { 0.82687725167985127, -0.39149005589612873, 0.
  08637647582608521 }
  radius_one := 0.83982241234364063
  z_plane := 0.46899799388377666
  radius_two := 3.82498471745980595
  proj_center := { -1.79840685186027738, -0.74104139314354389, -2.
  32206165570202927 }
  Seed is: 3392210867 from /__w/spectre/spectre/tests/Unit/Helpers/Domain/
  CoordinateMaps/TestMapHelpers.hpp:532
  height := -0.76291987755007407
  phi := 3.06171112463691575
  radius := 0.47393096255658523
```

### Environment:

This failed on CI on my fork.  If the link doesn't work, let me know and I will add more details...

https://github.com/kidder/spectre/runs/1882348286?check_suite_focus=true

Add as an attachment `$SPECTRE_BUILD_DIR/LibraryVersions.txt` or
add its contents here.

**Comment by markscheel** [comment]
The correct solution to this is PR #2587, for which this test needed to be extensively rewritten anyway, and in #2587 I spent much more effort making the test more robust.

However, if this bug is causing problems with CI or problems for users, and needs to be fixed more quickly, I have just added a very small PR #2882 that fixes this problem at least on my machine.

**Comment by nilsdeppe** [comment]
Another seed: `Seed is: 1338229533` (just to collect here). I'm fine getting in 2587 as the fix
