### ISSUE TITLE
Options::Auto with derived class pointer

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#2914]
Not sure if this is a bug or a feature request: `Options::Auto<std::unique_ptr<Derived>>` doesn't currently auto-convert to `std::optional<std::unique_ptr<Base>>`, where `Derived : Base`. @wthrowe Do you think we could make that work? It could be useful for boundary conditions. I can provide more details if this wasn't enough.

**Comment by wthrowe** [comment]
I think the rules for choosing conversion operators are powerful enough to let this work.  I'll figure it out.
