### ISSUE TITLE
Offset in EvenlySpaced triggers does not behave as it should 

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#2924]
# Bug reports:

### Expected behavior:

If in an input file I put

~~~
EventsAndTriggers:
  ? Slabs:
      EvenlySpaced:
        Interval: 2
        Offset: 10
~~~

I would expect a trigger at 10, 12, 14, ....

### Current behavior:

Triggers at 0, 2, 4, ...

### Environment:

CMake Version: 3.18.5
SpECTRE Version: 2021.02.08
Git description: v2021.02.08-47-g783dd745f
Git branch: bbh_attempt_15
Git hash: 783dd745f8b9a7899466c56fca4fd35d16a31a1a
Hostname: ocean.fullerton.edu
Host system: Linux-3.10.0-957.1.3.el7.x86_64
Host system version: 3.10.0-957.1.3.el7.x86_64
Host system processor: x86_64
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS:  -L/opt/ohpc/pub/apps/charm_6.10.2_libs/lib -fuse-ld=lld
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /opt/ohpc/pub/apps/llvm/10.0.1/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 10.0.1
CMAKE_C_COMPILER: /opt/ohpc/pub/apps/llvm/10.0.1/bin/clang
CMAKE_C_COMPILER_VERSION: 10.0.1
CMAKE_Fortran_COMPILER: /opt/ohpc/pub/compiler/gcc/7.3.0/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 7.3.0
Python Version: 3.7.4

# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by wthrowe** [comment]
That is the behavior I intended (the offset is a shift, not a starting value).  For evenly spaced times (as opposed to slabs), you could use `PastTime` to filter the results, but we don't have anything turning on at a particular slab, which is an oversight.  For now, with small offsets you can use
```
And:
  Slabs:
    EvenlySpaced:
      ...
  Not:
    Slabs:
      Specified:
        Values: [0, 2, 4, 6, 8]
```

The input I would like to work would be something like
```
And:
  Slabs:
    EvenlySpaced:
      ...
  StartingAtSlab:
    Value: 10
```
(Could also be `StartingAtSlab: 10` to match `PastTime`, but I think I was being too clever when I wrote the latter and am more likely to change it to the more verbose form.)

**Comment by wthrowe** [comment]
#2937 allows filtering by slab range, along the lines of the second block in my previous comment.  Is this a satisfactory resolution of this issue @geoffrey4444?

**Comment by nilsdeppe** [comment]
@geoffrey4444 is this fixed now?

**Comment by geoffrey4444** [comment]
I'm satisfied with this solution, yes
