### ISSUE TITLE
Port remaining domain creators

### ISSUE THREAD

**Issue by osheamonn** [sxs-collaboration/spectre#293]
- [x] Rectangle
- [x] Brick
- [x] Disk
- [x] Shell
- [x] Sphere

We had some also that were useful for testing but we may not want to merge to master
- [x] Rotated Intervals
- [x] Rotated Rectangles
- [x] Rotated Bricks

**Comment by nilsdeppe** [comment]
Discussion with @wthrowe @kidder and myself:

RotatedIntervals, RotatedRectangles, and RotatedBricks would be good to have even master just because they are a really good testing ground for communication and minus signs.

The rubiks cube will  be replaced by an actual spherical shell.

**Comment by nilsdeppe** [comment]
@gsb76 could you hammer through the last 3? We will want these for testing
