### ISSUE TITLE
Move check for Test_DataVectors into TestHelpers

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#307]
This function would be useful for comparing DataVectors in all tests.  It should also assert that the DataVectors are not empty, as we have had bugs missed when tests pass by comparing empty DataVectors (that should not have been empty)

**Comment by nilsdeppe** [comment]
@kidder Is this sufficiently replaced by `CHECK_ITERABLE_APPROX` from f970150b280b9cefaf3b04291e573aba0d4765b0 sufficient?

**Comment by kidder** [comment]
Yes, but we should probably clean up some older tests (e.g. replacing the check_vectors function in Test_DataVectors); guess that could be another issue though...

**Comment by nilsdeppe** [comment]
Yes, we could just rename this issue, I'm fine with that :)
