### ISSUE TITLE
Support Variables tags without subitems

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#3229]
# Feature request:

The DataBox feature to add a subitem for every tag in a Variables is very useful is some situations, but is not always necessary. Sometimes a tag just stores a Variables and it's not necessary to access its constituents from the DataBox individually. In that case, the subitems significantly inflate the number of tags in the DataBox, possibly increasing compile times. I suggest we restrict the subitems feature to `Tags::Variables`, meaning that subitems won't be added for any other tag that happens to have a `using type = Variables<...>`.

**Comment by moxcodes** [comment]
I agree -- I think there are situations where this could make the databox considerably lighter.

**Comment by wthrowe** [comment]
I've worked around this, (when it was causing duplicate tags for me) by putting the `Variables` in a one-element `std::tuple`.  This proposal would be more elegant.

This might be as simple as changing the `Requires` to a specialization on the tag in the `Subitems` specialization in `Variables.hpp`, but I haven't tried it.
