### ISSUE TITLE
Shell  radial partitioning buggy

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#3233]
# Feature request:

I can't tell from the documentation of `RadialDistribution` what values I'm actually allowed to set https://spectre-code.org/structdomain_1_1creators_1_1Shell_1_1RadialDistribution.html 

# Bug:

As far as I can tell there's no check that the radial partitionings are monotonically increasing and that there are duplicates. The latter gives FPEs in the inv_jacobian that are rather difficult to debug for most users.

**Comment by nikwit** [comment]
there is a check that they are sorted in `Shell.cpp:87`. I can add this to the documentation to make it more clear. Would you also like me to add another check for duplicates?

**Comment by nilsdeppe** [comment]
ah okay, yes duplicates would be good to check. Should be pretty cheap and it's only done once. This check would've saved us 10-15 minutes earlier today

**Comment by nikwit** [comment]
added check and documentation in #3236
