### ISSUE TITLE
Test_VolumeDataReaderAlgorithm2D and 3D tries to write single-extent volume data

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#3242]
# Bug reports:

### Expected behavior:

The volume data should have at least 2 extents in each dimension, otherwise we cannot write connectivity.

### Current behavior:

The extents are things like `{2,1,1}` which we cannot process in ParaView anyway. Supporting such behavior would require completely redesigning the way we do volume data IO.

Note:
I need this fixed in order to enable compression in HDF5 (reduces volume data file size by up to 10x), so getting this fixed sooner rather than later would be good. If that can't be done I can comment out the 2d and 3d tests until this issue gets fixed.

**Comment by nilsdeppe** [comment]
I've added some numbers to increase the extents and then things seem to still pass. I'll assign this to me and link the PR once I've opened it

**Comment by nilsvu** [comment]
Sorry I missed this. What's the issue with single-value extents? In my understanding, single value extents are a valid configuration for Gauss points, no? If there's a technical issue with that we should probably assert it at the place where it breaks. For the particular test in question here, adding extra points should be no problem (there was no reason I chose single extents here).

**Comment by nilsdeppe** [comment]
They are valid for solving equations, but we don't have a way of handling them correctly in in terms of generating a connectivity. Ultimately ParaView uses this connectivity for visualizing the data by connecting the different grid points together and doing interpolation between them.

It turns out what I thought was working isn't working, and I don't really understand why the test is written the way it is. The whole test breaks and becomes inconsistent and buggy when the number of extents are increased. Since I don't understand why the test is written this way I don't really feel comfortable changing it, and it'll take me a decent amount of time to update it that I can't really allocate to this test.

I have commits on a [branch](https://github.com/nilsdeppe/spectre/tree/hdf5_compression) that adds `ASSERT`s to the places that would've caught this but of course the test needs to be fixed or remove before those could be merged.

So my question is how to best proceed. Should I comment out the tests so we can have compression for our data (reduction in file size of 2-5x) or is someone else who understands the test willing and able to update and I wait for that first?
