### ISSUE TITLE
LibraryVersions.txt does not have any information about libraries

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#3297]
# Bug reports:

### Expected behavior:

The report prints out all the information about libraries used by spectre

### Current behavior:

It only contains information about compilers, compiler flags, and python

### Environment:

All

**Comment by kidder** [comment]
appears to have been broken by commit 2e87a9db9645f8c7f7f3e0a991e39d6a5fe20064 in #2206 because  `cmake/SetupVersionFile.cmake`  overwrites the file instead of appending...

**Comment by kidder** [comment]
We need something to overwrite the file whenever cmake is invoked otherwise you get multiple copies of the information.  

I am not sure why you moved the location of `include(SetupVersionFile)` in the top level `CMakeLists.txt` so I don't know whether to:
- move the call back to where it was previously
- split `SetupVersionFile.cmake` into two parts, one that overwrites the file before any other call appends to the file, and the second to print information that you felt was incorrect unless printed at the end...

**Comment by fmahebert** [comment]
This is a duplicate of issue #2645, in which I proposed a few different solutions but never got any interest...

**Comment by kidder** [comment]
duplicate
