### ISSUE TITLE
Cannot slice `inverse_spatial_metric` onto boundary when using relativistic system

### ISSUE THREAD

**Issue by nikwit** [sxs-collaboration/spectre#3306]
# Bug reports:

When specifying  the inverse_spatial_metric as a `dg_interior_temporary_tags`, I get the error message: "error: base class 'tuples_detail::TaggedTupleLeaf<InverseSpatialMetric<3, Inertial, DataVector> >' specified more than once as a direct base class".

This appears to be because the tag is now twice in `tags_on_interior_face` in the `BoundaryConditionsImpl.hpp` and also appears to be fixed by adding a `tmpl::remove_duplicates` there. Is this a feature or a bug?

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/LibraryVersions.txt` or
add its contents here.

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
This should work. Can you add a `tmpl::remove_duplicates<...>` around the `tmpl::append<...>` that `tags_on_interior_face` is assigned to and see if that fixes the issue?

**Comment by nikwit** [comment]
Yes, that is exactly what I meant. That fixes it.

**Comment by nilsdeppe** [comment]
okay, would you mind submitting a PR with that change? Otherwise  I can too

**Comment by nikwit** [comment]
Sure, I will
