### ISSUE TITLE
Introduce `SphereUtilities` library

### ISSUE THREAD

**Issue by nikwit** [sxs-collaboration/spectre#3381]
# Feature request:

Currently, all the methods for calculations in spherical coordinates or spherical harmonic expansions are in the `ApparentHorizons` library but they are starting to be needed outside this library. Therefore I would suggest to move these functions into a new library called `SphereUtilities`.

This includes the entire `YlmSpherepack` bindings, the `SpherepackIterator`, as well as most functions in `ApparentHorizons` which are currently only in compute tags (e.g. conversions, Jacobians, Pfaffians, Hessians between Cartesian and spherical coordinates).

This has come up out of discussions with @markscheel and @nilsleiffischer in the shape map PR. We expect this to reduce code duplications, avoid cyclical dependencies and  encourage consistency across Spectre.

**Comment by nilsvu** [comment]
I think a `SphereUtilities` library would be very helpful. My question is: Where do we place it in the dependency tree? It probably needs to depend on `DataStructures`. It also mostly extends external functionality, e.g. provides an interface to spherepack, which suggests placing it in `Utilities/`. The other place that comes to mind would be `NumericalAlgorithms/`. What do you think?

**Comment by kidder** [comment]
We want to keep `Utilities` independent of `DataStructures`.  I would say that anything dealing with `YlmSpherpack` belongs  in `NumericalAlgorithms`, say in a `SphericalHarmonics` subdir.  (Separately I think all the Swsh code in `Spectral` should be moved to a separate `SpinWeightedSphericalHarmonics` subdir. ).   I think free functions dealing with coordinate transformations between spherical and Cartesian coordinates belong in a subdir in `PointwiseFunctions`, perhaps simply called `Spherical`
