### ISSUE TITLE
Document cmake arguments

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#339]
### Component:

- [ ] Code
- [X] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

We should document the cmake arguments that can be passed to configure things.

**Comment by nilsdeppe** [comment]
How does adding a page linked to from the installation instructions sound? @kidder and I discussed that and it seems reasonable. That page can then go over all the CMake variables we offer and what their options are

**Comment by wthrowe** [comment]
That sounds fine.

**Comment by nilsdeppe** [comment]
Alright, great!

**Comment by nilsdeppe** [comment]
@kidder progress update?
