### ISSUE TITLE
CITATION file

### ISSUE THREAD

**Issue by moble** [sxs-collaboration/spectre#3394]
# Feature request:

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [X] Continuous integration

### Desired feature:

- A `CITATION.cff` file

### Detailed discussion:

Github recently added [support for `CITATION` files](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files), which would bring up to two nice side effects:

  1. It adds a cute little button on the main github page that lets people just copy the bibtex entry to cite the code.
  2. Zenodo claims to be supporting this file, so it could change how that whole release side of things work.

In particular, it looks like zenodo can be set to create a new version on each release, and the zenodo metadata (including authors) would just be retrieved from this file, which would simplify a lot of the `Release.py` code.

@nilsleiffischer I know you've written a lot (all?) of the code to push releases to zenodo, so I suppose you're the one who would have to think about this.

But even if the zenodo stuff doesn't pan out, it would be nice to provide a standard bibtex entry so easily.

**Comment by nilsvu** [comment]
This is amazing, thanks for the pointer @moble! Looks like GitHub released this feature two days ago, so you reacted fast :D

We can easily generate a `CITATION.cff` file from our existing `Metadata.yaml`. That could be all we need to do for now. I think we can't / don't need to change the way we currently interact with Zenodo. AFAICT the `CITATION.cff` support by Zenodo can't reserve a DOI before the release is published, which has been the limitation of their automatic GitHub integration all along.
