### ISSUE TITLE
Current develop branch on Wheeler does not compile

### ISSUE THREAD

**Issue by mar-celine** [sxs-collaboration/spectre#340]
# Bug reports:

### Expected behavior:
For compilation to complete

### Current behavior:
g++: error: unrecognized command line option ‘-Qunused-arguments’; did you mean ‘-Wunused-argument’?
Fatal Error by charmc in directory /home/gsb76/gab_git/gccbuilddir/src/Executables/ParallelInfo
   Command g++ -D_REENTRANT -I/usr/local/charm/6.8.0/mpi-linux-x86_64-smp-gcc/bin/../include -D__CHARMC__=1 -DGIT_COMMIT_HASH=18aebe0727f11d958b9e6963eaac4edb3221c4fe -DGIT_BRANCH=gab_add_disk -pthread -Qunused-arguments -rdynamic -U_FORTIFY_SOURCE -fno-stack-protector -fno-lifetime-dse -c ParallelInfo_InfoFromBuild.cpp -o ParallelInfo_InfoFromBuild.o returned error code 1

### CMake command:

cmake -D CMAKE_BUILD_TYPE=Debug -D CMAKE_Fortran_COMPILER=gfortran ~/gab_git/spectre/

### Environment: 

CMake Version: 3.9.4
SpECTRE Version: 0.0.0
SpECTRE branch: gab_add_disk
SpECTRE hash: 18aebe0727f11d958b9e6963eaac4edb3221c4fe
Hostname: wheeler
Host system: Linux-3.10.0-327.36.3.el7.x86_64
Host system version: 3.10.0-327.36.3.el7.x86_64
Host system processor: x86_64
CMAKE_CXX_FLAGS:  -W -Wall -Wextra -Wpedantic -Wcast-align -Wcast-qual -Wdisabled-optimization -Wdocumentation -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Winvalid-pch -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wnewline-eof -Wno-documentation-unknown-command -Wno-mismatched-tags -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wsign-conversion -Wstack-protector -Wswitch-default -Wunreachable-code -Wwrite-strings -Wno-noexcept-type
CMAKE_CXX_LINK_FLAGS:  -Qunused-arguments
CMAKE_CXX_FLAGS_DEBUG: -g
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS:
CMAKE_C_LINK_FLAGS:
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS:
CMAKE_Fortran_LINK_FLAGS:
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS:
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/local/llvm/5.0.1/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 5.0.1
CMAKE_C_COMPILER: /usr/local/llvm/5.0.1/bin/clang
CMAKE_C_COMPILER_VERSION: 5.0.1
CMAKE_Fortran_COMPILER: /usr/local/gcc/6.4.0/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 6.4.0
Python Version: 2.7.5
Charm Version:  6.8.0
BLAS_LIBRARIES:  /usr/local/openblas/0.2.18/lib/libopenblas.so

**Comment by kidder** [comment]
Please add more information:  where?  what was your cmake command? what is it trying to compile when it gives the error?

**Comment by kidder** [comment]
Okay, for the record this happened because the code was compiled with clang, but linked with gcc.  There is an [open cmake issue](https://gitlab.kitware.com/cmake/cmake/issues/15934) (with no updates in over a year) requesting a CheckCxxLinkerFlag.  I'll write a simple one, but if this issue arises again in the future, we should check to see if cmake has done anything about their issue
