### ISSUE TITLE
Incorrect charm target on wheeler

### ISSUE THREAD

**Issue by moxcodes** [sxs-collaboration/spectre#3451]
Currently, we are using a charm target that uses inefficient interconnect on the wheeler system at Caltech.
We should (in this order):
- add a new charm module to wheeler using the target `verbs-linux-x86_64-smp-gcc`
- update the environment and submission files for wheeler (the submission one should be pretty similar to CaltechHPC and ocean after this change)
- remove the old charm module and announce the change so that users do not mistakenly use the slow communication version of charm++

**Comment by nilsdeppe** [comment]
We've switched to IntelMPI which seems to be performing correctly.
