### ISSUE TITLE
Implement inverse function for Wedge2D and Wedge3D

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#347]
# Feature request:

Inverse functions for Wedge2D and Wedge3D

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Implementation of inverse function for Wedge2D
- [x] Implementation of inverse function for Wedge3D

**Comment by kidder** [comment]
Wedge3D inverse was added in #334

**Comment by nilsdeppe** [comment]
@gsb76 Can you add the inverse for the 2D wedge?

**Comment by mar-celine** [comment]
Wedge2D inverse was added in #405
