### ISSUE TITLE
Timeouts in CI for InputFiles.Poisson.ProductOfSinusoids1D.yaml.execute_check_output

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#3511]
Two PRs today.  I don't think logs are persistent after a run restart, so not much point in linking to them.  There's not much information available for a timeout anyway.

**Comment by nilsdeppe** [comment]
I also noticed the BentBeam times out. I've had 3 PRs in the last couple of days time out on that test
