### ISSUE TITLE
Importing `mpmath` or `sympy` in a python file which is called by `pypp` causes a FPE

### ISSUE THREAD

**Issue by nikwit** [sxs-collaboration/spectre#3554]
# Bug reports:
When I try  to `pypp::call` a python function in a  module that imports `sympy` or `mpmath` it throws a floating point exception.  gdb traces this to `PyObject* python_module = PyImport_ImportModule(module_name.c_str());` in `Pypp.hpp` before it disappears in `libpython3.8.so.1.0` for which I dont have debug symbols. This seems like it could be an upstream issue. 

It would be nice if someone could try and reproduce this on their machine: just put an `import mpmath` or `import sympy` in any python file that is called by a unit test. I am using python 3.8 and have tried several versions of `sympy` and `mpmath`.

I am trying to unit test some long auto-generated and manipulated analytical expressions against a high bit-precision evaluation using `sympy` (I know boost can also do this but it would be a lot better to do with sympy in my case).

**Comment by wthrowe** [comment]
I'm seeing a similar issue triggered by the recently added `Unit.FiniteDifference.Wcns5zMc` test using `scipy.signal`.  I think the lower-level cause in this case is importing `cmath`, which is sufficient to cause an FPE when added to another test.  I've tested with python 3.8 and 3.10, and both behave the same.

**Comment by nikwit** [comment]
That's interesting. Unfortunately I do not really have any idea how to further debug this. This is definitely upstream, right?

**Comment by wthrowe** [comment]
Yes, although I'm not certain they would consider it a bug.

@nilsdeppe suggested disabling FPE trapping during calls to python code, and that seems reasonable to me.

**Comment by nilsdeppe** [comment]
Yea, this seems like the sort of thing that could be difficult to convince other projects is a bug, and even if we can, it still needs to be worked around before that version gets released.

Probably changing `pypp::call` to:
```cpp
  disable_floating_point_exceptions();
  auto result = detail::CallImpl<ReturnType, ConversionClassList>::call(
       module_name, function_name, t...);
  enable_floating_point_exceptions();
  return result;
```
would fix the issue. I'm not sure if this will create problems with non-copyable return types, though. If so we could probably stick the enable-disable into a constructor-destructor and create a stack object.

**Comment by wthrowe** [comment]
Seems to work.  I'll submit a PR.
