### ISSUE TITLE
TypeError: Unable to convert function return value to a Python type! without explicit import of spectre.DataStructures

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#3621]
Trying to use `get_tensor_component` from `spectre.IO.H5` results in
```
TypeError: Unable to convert function return value to a Python type! The signature was
        (self: spectre.IO.H5._PyH5.H5Vol, observation_id: int, tensor_component: str) -> DataVector
```
unless `spectre.DataStructures` has been previously included.  It should be pulled in automatically by modules that need it.

**Comment by nilsvu** [comment]
I believe this can be fixed by a `py::module::import("spectre.DataStructures")` in the C++ bindings code for the H5 lib.

**Comment by nilsdeppe** [comment]
I'll have a fix for this in an upcoming PR that does some cleanup of the volume data and python bindings
