### ISSUE TITLE
Have separate pages for Docker and Spack installation installations

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#369]
# Bug report:

#362 has a discussion of splitting the Docker and Spack documentation into two pages. The Table of Contents on the main Documentation page can then have two entries, one for Docker and one for Spack.

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

**Comment by kidder** [comment]
@nilsdeppe and I don't think this needs to be done.
