### ISSUE TITLE
Charm++ SMP detection fails for some charm configurations

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#3694]
```
-- Found Charm: /home/wthrowe/spectre-deps/charm/ucx-linux-x86_64-smp/bin/charmc (found suitable exact version "6.10.2") 
-- Charm++ NOT built with shared memory parallelism
```
Our check looks at the contents of `conv-mach.h`, but for this configuration the `CMK_SMP` macro is defined in `conv-mach-smp.h`.

**Comment by nilsvu** [comment]
Last time I looked we didn't use the SMP detection for anything. Is it worth fixing?

**Comment by wthrowe** [comment]
I'm fine with removing it instead.  We just shouldn't report the wrong answer.

**Comment by nilsvu** [comment]
Done in #2680
