### ISSUE TITLE
Switch from yapf to black

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#3730]
[Black](https://black.readthedocs.io/en/stable/index.html) is a Python formatter that has gained a lot of popularity (24k stars on GitHub vs yapf's 12k). Hera are some advantages over yapf:

- Black formats multiline strings (still experimental). That yapf doesn't do this (and isn't planning to https://github.com/google/yapf/issues/408) is one of the most annoying things about it.
- Black has a setting to require a specific version in the config file. This is also annoying with yapf, since people often try to format with whichever version they have installed and then get confused why CI doesn't pass.

**Comment by wthrowe** [comment]
Not sure I like depending on something that has a big box labeled "Note - this is a beta product" on its main page.

**Comment by kidder** [comment]
well the YAPF README says 

`YAPF is still considered in "alpha" stage, ...`

so while I share your concern @wthrowe,  it may still be an improvement to switch...

**Comment by wthrowe** [comment]
Fair enough.

**Comment by nilsdeppe** [comment]
"Note - Black is now stable!"

@nilsvu can you be in charge of this change?

**Comment by nilsvu** [comment]
Yes! It's rather low priority though so I can't say when I'll get to it.

**Comment by nilsdeppe** [comment]
Sounds good! :)
