### ISSUE TITLE
Distinguish DataVector use between grid-point values and coefficients

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#378]
# Feature request:
We would like to add code safety to distinguish between the use of a DataVector as grid-point values and spectral coefficients

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Detailed discussion:
Nils and I discussed this and think that adding a template parameter `Representation` to DataVector which is defaulted to `Grid` but could be set to `Coefficients` or `Spectral` when a DataVector is used to represent spectral coefficients.  This adds type safety as one cannot call a function that requires coefficients with a grid-point DataVector.  It will allow simplifying names of functions in YlmSpherepack as the type of the parameters can be used to overload functions instead of using different names.  Also we can disable the mathematical operators of DataVector that do not make sense for coefficients (the only allowed ones we could think of were addition, subtraction, scalar multiplication, scalar division, and negation)

**Comment by kidder** [comment]
suggestion is to introduce a new class CoefficientVector that will represent a vector of coefficients.  Initially with no math, could add scalar multiplication and addition

**Comment by prayush** [comment]
@kidder , @nilsdeppe - Does something like this <https://github.com/sxs-collaboration/spectre/compare/develop...prayush:coefficientVector> work? This is mostly adapted from the DataVector class, but with significantly less math operations (only addition/subtraction with CoefficientVector/doubles/blaze vectors, and multiplication/division by doubles)  being allowed.

**Comment by nilsdeppe** [comment]
Yes

**Comment by markscheel** [comment]
For operations like filtering, you probably want to be able to multiply a CoefficientVector by some other vector (another CoefficientVector? a DataVector?) that represents a filter function.

If we ever want to do convolutions, we also want to be able to multiply CoefficientVectors by each other.

**Comment by nilsvu** [comment]
So in a near-future PR I'll add a thin wrapper around `blaze::DynamicVector`, this will be used just for a collection of numbers that carry no particular meaning. I'll use it to return `Spectral::quadrature_weights`, to do computations for the conjugate gradient algorithm and such.

Then what's left is a data structure to hold field values on the mesh (currently `DataVector`, we probably want to keep this name? These are the nodal coefficients used everywhere) and another one that holds spectral/modal coefficients. The distinction between these two is what this issue is about I think.

**Edit:** Opened #696 to add `DenseVector : blaze::DynamicVector`.

**Comment by nilsvu** [comment]
I'd like to suggest the name `ModeVector`.

**Comment by nilsdeppe** [comment]
I think we agreed to use `ModalVector`

**Comment by nilsvu** [comment]
I'd like to propose to give matrices / linear operators the same treatment that #715 is giving `DataVector` / `ModalVector`. By the same arguments raised in this issue we should rename `Matrix` to something like `MeshOperator<DataVector, DataVector>` to make it clear that it's an operator that works on nodal coefficients, as opposed to a generic collection of numbers or, for instance, a `MeshOperator<ModalVector, DataVector>` that works on spectral/modal coefficients and returns nodal coefficients like `spectral_to_grid_points_matrix`.

We can use #696 to derive this off `DenseMatrix<double, blaze::columnMajor>` which provides us with a well-tested matrix implementation. The course of action, as a follow-up to #696, is just to rename `Matrix` to `MeshOperator` (or similar) and template it on the `ArgumentType` and `ReturnType`. The implementation of this would be made even easier if [Blaze added a tagging feature](https://bitbucket.org/blaze-lib/blaze/issues/166/allow-tagging-blaze-expressions).

**Comment by nilsdeppe** [comment]
I think this will be non-optional. Anything that does blaze DataVector-Matrix multiplication will be unsupported until there is a matrix that we want to allow it with.

I've managed to get the tagging working on my machine (required very few changes to PointerVector), but it is failing in the docker image. I'm investigating that now locally.

**Comment by kidder** [comment]
This is being done in #1080
