### ISSUE TITLE
Trouble reading input files with EventsAndTriggers in Python

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#3841]
Both PyYaml and ruamel.yaml have trouble reading in the `EventsAndTriggers` section in input files, which uses YAML objects as keys in a dict. Both Python packages complain with variations of "unhashable key" errors. ruamel.yaml seems to be able to handle a few more cases than PyYaml, but also fails to load `tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml`. I believe this is valid YAML and thus an insufficiency of the packages, but we'll have to deal with it nonetheless.

Relevant upstream issues:
- https://sourceforge.net/p/ruamel-yaml/tickets/327/
- https://github.com/yaml/pyyaml/issues/614

**Comment by nilsdeppe** [comment]
We recently changed the input file format. Is this fixed now?

**Comment by nilsvu** [comment]
Changed format again in #4942. Should be fixed now.
