### ISSUE TITLE
Travis builds failing with clang-tidy

### ISSUE THREAD

**Issue by osheamonn** [sxs-collaboration/spectre#386]
# Bug reports:

### Expected behavior:

Clang-tidy should not emit any warnings. 

### Current behavior:

Clang-tidy is failing with "warning: do not implicitly decay an array into a pointer; consider using gsl::array_view or an explicit cast instead" within DataVector.hpp, and PointerVector.hpp on our travis builds. I can also reproduce this on my own machine.

**Comment by kidder** [comment]
should be fixed by #377

**Comment by nilsdeppe** [comment]
Closed with #377
