### ISSUE TITLE
Make YlmSpherepack threadsafe

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#3929]
# Bug reports:

[Note that this problem exists for other classes in addition to YlmSpherepack (basically everything that has mutable member variables and that will live on a NodeGroup)].

### Expected behavior:

YlmSpherepack should be threadsafe, so if you put a YlmSpherepack in a NodeGroup, nothing bad will happen.

### Current behavior:

Currently, YlmSpherpack has mutable member variables, so if stored in a NodeGroup there can be race conditions and undefined behavior if different threads call different member functions simultaneously.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Detailed discussion:

There are three different classes of storage that are used in YlmSpherepack, which are all currently inside `mutable` member variables.
1. Things like `quadrature_weights_` that are allocated/computed in the `YlmSpherepack` constructor and used by various member functions.  These can be made non-`mutable` and still be computed in the constructor since they never need to change.
2. Temporary storage used in the `YlmSpherepack` constructor. These can now be allocated in the constructor and thrown away after use.
3. There are some quantities that are stored and returned by member functions but not re-used elsewhere.  These can be passed by `gsl::not_null` in those member functions instead of being stored internally.
4. Temporary storage that is needed in various `YlmSpherepack` member functions and is immediately thrown away after use, such as buffers that get passed into the Spherepack fortran routines.  For these, each such member function can take an extra buffer argument as suggested by @nilsdeppe and can also have its own buffer_size function so that anything calling it can determine the size of the buffer it needs to pass.
```
size_t spec_to_phys_buffer_size() const {...} // generally depends on l_max, m_max
void spec_to_phys(const gsl::not_null<gsl::span<double>*> buffer,other_args) const {
   const size_t buffer_size = spec_to_phys_buffer_size();
   DataVector local_buffer{};
   if (buffer->size() == 0 ) {
      local_buffer = DataVector(buffer_size);
      *buffer = gsl::make_span(local_buffer.data(),local_buffer.size());
  } else if (UNLIKELY(buffer->size() != buffer_size)) {
      ERROR("Buffer has wrong size, you should do X"....);
  }
  // ... rest of member function same as before except it uses buffer  ...
}
```

Note that for 4. above, some member functions call other member functions.  Suppose A calls B.  Then we can do things like
```
void A_buffer_size() const {return B_buffer_size() + whatever_size_A_needs_in_addition_to_what_B_needs;}
void A(const gsl::not_null<gsl::span<double>*> buffer,other_args) const {
  // ... do stuff ...

  // Now need to call B
  gsl::span<double> B_buffer = gsl::make_span(buffer->data()+A_buffer_size()-B_buffer_size(),B_buffer_size());
  B(make_not_null(&B_buffer), ...);
}
```

**Comment by markscheel** [comment]
From SpECTRE meeting April 18:  Consensus is to *always* use a passed in buffer and never allocate it internally.  And check minimum size.  So it would look like this:

```
void spec_to_phys(const gsl::not_null<gsl::span<double>*> buffer,other_args) const {
   if (UNLIKELY(buffer->size() < spec_to_phys_buffer_size())) {
      ERROR("Buffer has wrong size, you should do X"....);
  }
  // ... rest of member function same as before except it uses buffer  ...
}
```

**Comment by nilsdeppe** [comment]
This sounds like a good plan to me!
