### ISSUE TITLE
Make tensor stream operator less verbose

### ISSUE THREAD

**Issue by osheamonn** [sxs-collaboration/spectre#393]
# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired 

When streaming a tensor, stream only the data so that the output is simply: 
T(0, 0) = (1, 1)
T(0, 1) = (3, 0) ... 
The type info can be printed separately if needed. 

### Detailed discussion:

In my opinion the output for the stream operator for tensor is far too verbose. Most of the info it outputs is determined by the type of the tensor and clutters the output. If you want to print a tensor for debugging purposes usually you're only interested in the values, and if you're also interested in the index types, frames etc... you should choose to stream them separately, or just check them at compile time.

**Comment by nilsdeppe** [comment]
I agree that the information is available elsewhere (the type system). I'd be fine with just not printing it out, and observers are serializing `Tensor`s into `std::vector`s anyway, so the information isn't needed there either. If it is generally agreed upon that `TypeDisplayer` is clear enough for people to use I'm fine with just removing it. If people feel that `TypeDisplayer` is not easy enough to use then we could add a function that would allow streaming the information about indices.

**Comment by wthrowe** [comment]
I like the proposed change.

When you do it, please also add a case to the Unit.DataStructures.Tensor.Stream test that streams something with nontrivial symmetry.

**Comment by kidder** [comment]
Fixed in #395
