### ISSUE TITLE
OrientVariablesOnSlice Tests sometimes fail on Travis

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#397]
# Bug reports:

### Expected behavior:

All tests always pass on TravisCI

### Current behavior:

The OrientVariablesOnSlice test occasionally fails with the values being completely wrong, e.g. `2.0 == approx(3.5)`.

Please link to builds that fail with this problem so we can try and find some pattern and fix the issue.

**Comment by kidder** [comment]
https://travis-ci.org/sxs-collaboration/spectre/jobs/308149791

Edit(nils):
[308149791_log.txt](https://github.com/sxs-collaboration/spectre/files/1510830/308149791_log.txt)

**Comment by nilsdeppe** [comment]
https://travis-ci.org/sxs-collaboration/spectre/jobs/308464605

[308464605_log.txt](https://github.com/sxs-collaboration/spectre/files/1510944/308464605_log.txt)

**Comment by nilsdeppe** [comment]
The ElementMap test appears to be exhibiting similar symptoms: https://travis-ci.org/nilsdeppe/spectre/jobs/310969258

[element_map00.txt](https://github.com/sxs-collaboration/spectre/files/1525103/element_map00.txt)

**Comment by nilsdeppe** [comment]
I'm closing this since we haven't seen this issue in quite a while now. If it comes back we can reopen the issue.
