### ISSUE TITLE
Unit.Parallel.AlgorithmGlobalCache fails if WORKDIR/tests/Unit/Parallel/Test_AlgorithmGlobalCacheReduction.h5 exists

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#4024]
```
Node: 0 Proc: 0
Line: 452 of /home/wthrowe/spectre/tests/Unit/Parallel/Test_AlgorithmGlobalCache.cpp
Function: auto CheckMemoryMonitorRelatedMethods<TestMetavariables>::execute_next_phase(const typename TestMetavariables::Phase, const Parallel::CProxy_GlobalCache<TestMetavariables> &)::(anonymous class)::operator()(const std::string &, const std::vector<std::string> &, const double) const [Metavariables = TestMetavariables]

Failed comparison: data.rows() == 1
Line: 452
File: /home/wthrowe/spectre/tests/Unit/Parallel/Test_AlgorithmGlobalCache.cpp

############ ERROR ############
```
It is not clear to me what is supposed to be cleaning this up.  I assume I interrupted the test on a previous run and whatever the normal cleanup is didn't happen.  Rerunning gives the same error.

**Comment by wthrowe** [comment]
Actually, no, this happens after any rerun of the test, it doesn't require interrupting a previous one.

**Comment by wthrowe** [comment]
@knelli2 Is this related to any of your recent GlobalCache changes?

**Comment by knelli2** [comment]
I probably just don't remove the file when I should. Where should that be done? Before I need to write to it or once the test is finished?

**Comment by wthrowe** [comment]
I believe both is usual.

**Comment by knelli2** [comment]
I guess a bigger picture question I had was, why does the testing framework not remove all generated H5 files before/after a test is run? If the files are generated by the test purely for the purpose of checking output, it seems a bit redundant for each test to have to worry about whether it's test file has been cleaned up or not. Why not have a global thing take care of it?

**Comment by wthrowe** [comment]
With the current interface it has no way of knowing what files were/are going to be generated by the test.  Feel free to write something if you have an idea of how to fix that.
