### ISSUE TITLE
markdown-math-filter.pl breaks using $ in documentation

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#4036]
# Bug reports:

If I do
```
export VARIABLE=${BLAH}/stuff
```
in the documentation it renders correctly. There is some weird combination of line splits, and number of `$` that means the `$` gets replace with `\f$`. This is annoying because `$` is valid syntax in shell script examples. For example, see `Precompiled Headers and ccache` in https://spectre-code.org/travis_guide.html

**Comment by nilsvu** [comment]
Should be an easy fix in the perl regex. I'll take a look.
