### ISSUE TITLE
Renaming Outflow boundary condition in GRMHD and possibly other evolution systems

### ISSUE THREAD

**Issue by yoonso0-0** [sxs-collaboration/spectre#4070]
A boundary condition for GRMHD which lets outgoing fluid to leave the domain and magnetic field to evolve freely at the boundary is commonly referred to as "outflow", "hydrodynamic outflow", "free outflow" boundary condition etc. in literature. It's implemented as copy-pasting the outermost grid value of primitive variables into ghost zones if the fluid is traveling outward.

Currently we have `Outflow` boundary condition in Burgers, NewtonianEuler, CurvedScalarWave, GeneralizedHarmonic, and ValenciaDivClean evolution systems, and they all check if all characteristic speeds are directed outward.

For ValenciaDivClean, the `Outflow` boundary condition class is checking characteristic speeds with lapse and shift as follows:
```
min_speed = std::min(min(-get(lapse) - get(normal_dot_shift)),
                       min(get(lapse) - get(normal_dot_shift)));
```
which essentially is checking that the future light cone is pointed outward at the boundary, and is not affected by any hydro-related quantities. (this boundary condition  may be appropriate on the excision surface when we are simulating accretion on black hole).

Therefore I propose renaming the existing `Outflow` boundary condition in ValenciaDivClean system to "`Outgoing`", before adding the new hydro-type outflow boundary condition which will be named `FreeOutflow`, in order to reserve the term "flow" to something related to variables that are actually evolved.

I welcome any suggestions for clearer names.

* For Burgers and NewtonianEuler I think the current naming `Outflow` is fine, since all the characteristic speeds are computed from evolved variables.
* For GeneralizedHarmonic I have no good opinion. 
* I'm not familiar with CurvedScalarWave but it seems that it uses the same criteria as GeneralizedHarmonic, so would be worth considering renaming it. @nikwit ?

**Comment by nikwit** [comment]
IMO its most important that all these BCs in different systems should have the same name given that they are doing the same thing. In addition, the outflow enum in `Evolution/BoundaryConditions/Type.hpp` should have that same name for consistency. 

Regarding the name itself I do not have strong opinions but `Outgoing` seems not very informative. Other candidates I can think of are `OutflowingCharFields`, `NoBoundaryCondition` or `InsideHorizon`.

**Comment by yoonso0-0** [comment]
Another way I could think of is to leave current namings unchaged and use `HydroOutflow` or `HydroFreeOutflow` for the new one.

**Comment by nikwit** [comment]
That would probably be easiest, fine with me
