### ISSUE TITLE
Unit.Options.Python.ExtractInputSourceYAMLFromH5 fails

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#4124]
# Bug reports:

### Expected behavior:
It passes

### Current behavior:

Note that the test name should also be updated from `YAML` to `Yaml`

```
 Start 1422: Unit.Options.Python.ExtractInputSourceYAMLFromH5
 1/1 Test #1422: Unit.Options.Python.ExtractInputSourceYAMLFromH5 ...***Failed    0.12 sec
 test_read_input_source_from_h5 (__main__.TestExtractInputSourceYAMLFromH5) ... FAIL

 ======================================================================
 FAIL: test_read_input_source_from_h5 (__main__.TestExtractInputSourceYAMLFromH5)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
 File "/home/nils/SpECTRE/spectre/tests/Unit/Options/Python/Test_ExtractInputSourceYamlFromH5.py", line 39, in test_read_input_source_from_h5
 self.assertEqual(input_source, expected_input_source_yaml)
 AssertionError: b'# Distributed under the MIT License.\n#[4698 chars]se\n' != '# Distributed under the MIT License.\n# [4697 chars]se\n'
```
I'm using python 3.9.7. This looks like a string encoding issue to me. My OS is Ubuntu 20.10.

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/BuildInfo.txt` or
add its contents here.

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsvu** [comment]
I've seen string encoding issues with h5py < 3.0.0: https://docs.h5py.org/en/stable/strings.html
Which version do you use, and which is installed in the container? If this is the issue then maybe we should require h5py v3.0.0.

**Comment by nilsdeppe** [comment]
I'm using 2.10.0. I think that's the default on Ubuntu 20.10, but I don't remember if I got it from apt or pip
