### ISSUE TITLE
Generalize element neighbors to handle refinement

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#414]
# Feature request:

The Neighbors class needs to be generalized for handling refinement.  

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:
- [ ] Implement MortarNeighbors

### Detailed discussion:

The current Neighbors implementation represent FaceNeighbors which are those on the opposite side of a face of an Element.  MortarNeighors are all Elements that are neighbors of the mortar that is used to communicate flux information through the face of an Element.  FaceNeighbors are therefore a subset of the MortarNeighbors.  FaceNeighbors are useful for checking the connectivity of the Domain.  It will need to be determined which set of neighbors are used in limiting (and this could be limiter dependent).

**Comment by nilsdeppe** [comment]
@wthrowe  @kidder 

With using small mortars, is this still an issue?

**Comment by wthrowe** [comment]
No.
