### ISSUE TITLE
"Vector sizes do not match" in tensor expression division

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#4155]
The following fails at runtime with "Vector sizes do not match".  Either changing the division to multiplication or removing one of the terms in the denominator works.
```c++
  const Scalar<DataVector> S{{{{1.0}}}};
  Scalar<DataVector> result{};
  tenex::evaluate(
      make_not_null(&result),
      1.0 / (S() + S() + S() + S() + S() + S() + S() + S() + S()));
```

**Comment by macedo22** [comment]
Thanks @wthrowe Found the bug and know the fix. Will push a fix as soon as I can!

**Comment by macedo22** [comment]
@wthrowe I don't know what motivated such an interestingly specific expression, but it was pretty uniquely suited to find the bug it did, so thank you!
