### ISSUE TITLE
Incorrect errors in CubicScale

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#4171]
The CubicScale map has the checks
```c++
  if (a_of_t <= 0.0) {
    ERROR("We require expansion_a > 0 for invertibility, however expansion_a = "
          << a_of_t << ".");
  }
  if (b_of_t < 2.0 / 3.0 * a_of_t or b_of_t <= 0.0) {
    ERROR("The map is invertible only if 0 < expansion_b < expansion_a*2/3, "
          << " but expansion_b = " << b_of_t << " and expansion_a = " << a_of_t
          << ".");
  }
```
The second check is not checking the same thing as the error message claims.  Normally I would just assume a typo in the error message, but the current things that are actually checked don't seem to make a lot of sense: The first two checks are equivalent to `0 < 2/3 a <= b`, so it seems strange to then check `b > 0`.

**Comment by markscheel** [comment]
So it looks to me like the actual requirements are:
 * `a >= 0`   (or else the mapped radius is negative near the origin)
 * `b >= 2/3 a` (or else r as a function of rho turns over before the outer boundary, so the inverse map is double-valued)
 * either `a` or `b` must be nonzero (or else the mapped radius is zero for all rho).

 So if we keep the first check as-is, the second check should just be `b>=2/3 a` and I think that is enough.
 
 I will add a PR that fixes this.
