### ISSUE TITLE
UniformCylindricalEndcap::inverse has lots of untested code

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#4172]
For my current purpose, this matters because the `newton_raphson` function is either having its implementation changed or being completely removed in #4135.  When making this change elsewhere, I have often run into trouble with brackets and roundoff and similar, so I think there is a high probability that my changes will break code paths if I cannot test them.

**Comment by markscheel** [comment]
How do I run codecov locally? I haven't done it for a long time, and nowadays I find it easier to just have CI tell me cases that I missed.  (are there instructions somewhere?)
