### ISSUE TITLE
Handle retrieving compute items at runtime

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#419]
# Bug reports:

When retrieving a compute item at runtime by name there should be no name ambiguities. That is, the label of a compute item is the same for any template parameters. This is "fine" for sorting the tags, but it is not okay when retrieving them for observing. For example, we may have the derivatives of either different variables, or in different frames. The solution @kidder @wthrowe and I came up with was to add a static method `name()` that returns a `std::string` corresponding to the name to be used at runtime for accessing items in the DataBox. This could be automated by simply concatenating the name methods of all template parameters, and requiring name methods be present for non-compute items.

This is low priority until we start doing evolutions and observing data.

This came up from a comment @wthrowe made on #415

**Comment by kidder** [comment]
Names for DataBox items were added in #708
