### ISSUE TITLE
Benchmark Wedge2D 

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#421]
# Feature request:

Benchmark the functions in Wedge2D (as an exercise in learning how to benchmark code)

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Detailed discussion:

Test whether moving `std::move(physical_x *=-1)` will improve the code

**Comment by kidder** [comment]
@gsb76 what is the status of this?

**Comment by nilsdeppe** [comment]
"Not yet" - @gsb76

**Comment by nilsdeppe** [comment]
What's the status of this?

**Comment by mar-celine** [comment]
Wedge2D will now use discrete_rotation to compute which axes to negate, so I'm not sure how relevant this is anymore
