### ISSUE TITLE
Changes to Wedge2D and Wedge3D

### ISSUE THREAD

**Issue by mar-celine** [sxs-collaboration/spectre#422]
Add analytic inverse jacobians to wedge2D and wedge3D
Add lambda to wedge3D as is used in wedge2D.

**Comment by nilsdeppe** [comment]
Is this issue fixed now?

**Comment by mar-celine** [comment]
The lambdas have been added, the inverse jacobian is still being computed by matrix inversion.

**Comment by nilsdeppe** [comment]
Okay, thanks! I was just looking through issues and wanted to get updates on some.

**Comment by nilsdeppe** [comment]
What's the status of this issue?

**Comment by mar-celine** [comment]
The inverse jacobians still need to be changed

**Comment by nilsdeppe** [comment]
What's the status of this?

**Comment by mar-celine** [comment]
The analytic inverse will be added in #681 , after which this issue can be closed

**Comment by mar-celine** [comment]
Closed by #681
