### ISSUE TITLE
Potential over-extrapolation in dense output when changing step size

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#4222]
Dense output can extrapolate to the end of the current time step (currently only does so when using `AdamsBashforthN`).  This could be a problem if the step size is decreased after the `RunEventsAndDenseTriggers` action has completed but before an actual step is taken.  This can happen either if the slab size is decreased by the `ChangeSlabSize` action or if an error estimate causes an LTS step rejection.  (I believe other LTS adjustments are only applied to the next step.)  This could cause truncation-level nondeterminism.

Probably the correct solution is to only allow dense output in already completed steps.

I think fixing this might interfere with the current control-system development, and I don't think it is a serious bug, so I think we can wait on a fix until we've gotten control systems into a state where we know they will not need extrapolated data.

The changes I immediately think of needed to fix this are changing `RunEventsAndDenseTriggers` and the time-stepper tests to always use the previous step, and changing the `TimeStepper` dense-output interface to stop returning whether output is possible (because should be the same for all steppers).

**Comment by knelli2** [comment]
Is this still an issue?

**Comment by wthrowe** [comment]
I believe this can't happen anymore, although the reason isn't particularly clean.

* In LTS, we do dense output after taking the volume step, because the step is part of the RHS evaluation.
* For monotonic GTS (AdamsBashforth and AdamsMoultonPcMonotonic), we never change the step size between dense output and the step.
* For other GTS, the step size can be adjusted to avoid control-system deadlocks, but these TimeSteppers do not do any extrapolation during dense output so the problem can't occur.

I would like to move the control-system checks earlier, which would simplify this argument, but I am not sure if that is possible and it is not necessary to close this.
