### ISSUE TITLE
Improve inverse_spatial_metric for test functions

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#431]
# Bug reports:

### Expected behavior:

Don't want any test to use a tensor with a zero-component

### Current behavior:

inverse_spatial_metric currently has a zero xx component

**Comment by kidder** [comment]
@osheamonn what is the status of this?

**Comment by nilsdeppe** [comment]
related to #603

**Comment by nilsdeppe** [comment]
@osheamonn progress update?

**Comment by osheamonn** [comment]
Fixed since adding python testing infrastructure.
