### ISSUE TITLE
Clang-tidy error with Toms748 root finder

### ISSUE THREAD

**Issue by yoonso0-0** [sxs-collaboration/spectre#4311]
In the line 179 of `FixConservatives` class of GRMHD,
https://github.com/sxs-collaboration/spectre/blob/0357edee5e2bba596ae97486a2a91afe08e3a654/src/Evolution/Systems/GrMhd/ValenciaDivClean/FixConservatives.cpp#L179-L180

if I move the latter assignment (tilde_d) to in front of the first one like this : 
```
double& d_tilde = get(*tilde_d)[s];
double& ye_tilde = get(*tilde_ye)[s];
```

then I get the following error on CI : 
```
clang-tidy-10 -p=/work/build -quiet /__w/spectre/spectre/src/Evolution/Systems/GrMhd/ValenciaDivClean/FixConservatives.cpp
/usr/include/boost/math/tools/toms748_solve.hpp:209:35: error: The left operand of '-' is a garbage value [clang-analyzer-core.UndefinedBinaryOperatorResult,-warnings-as-errors]
   T A = safe_div(T(fd - fb), T(d - b), tools::max_value<T>());
                                  ^
```

**Comment by yoonso0-0** [comment]
Somehow `\\ NOLINT` commands in https://github.com/sxs-collaboration/spectre/blob/develop/src/NumericalAlgorithms/RootFinding/TOMS748.hpp are not effective?

**Comment by kidder** [comment]
This is a known problem and we have no idea how to fix it.  Therefore we ignore these clang-tidy errors when deciding to merge PRs

**Comment by yoonso0-0** [comment]
Okay, thanks!
