### ISSUE TITLE
check if Ylmspherepack needs to check if angles are in correct range for interpolation

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#432]
# Bug reports:

### Expected behavior:

If theta or phi are out of range: we either get an ASSERT or correct answer
### Current behavior:

unknown; test this and find out

**Comment by kidder** [comment]
@markscheel any update on this?

**Comment by nilsdeppe** [comment]
@markscheel progress update?

**Comment by kidder** [comment]
@markscheel progress update?
