### ISSUE TITLE
Adjustment of bounds for root finding could lead to failure

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#439]
# Bug reports:

The bounds of find_root_of_function in OneDRootFinder are adjusted by the tolerance.  This could cause the routine to fail if this adjustment causes the function to be evaluated where it would fail.
It is not documented that the function does this internally.

**Comment by fmahebert** [comment]
`OneDRootFinder` is now `toms748`.

This issue could be resolved by one or both of:
* Add warning in documentation that bounds will be adjusted
* Change code to make adjustments optional, e.g. by passing in two bools to enable/disable the upper and lower bound adjustments.

@kidder Did you have a particular resolution in mind?

**Comment by wthrowe** [comment]
We could stop adjusting the bounds and make it the caller's job to ensure their root is in range.

**Comment by fmahebert** [comment]
Sounds good to me; I have no objection to making the caller think about their bounds. And toms748 is currently only used by BulgedCube (tests aside), so that's not too many places to revisit.

**Comment by fmahebert** [comment]
Fixed in #827
