### ISSUE TITLE
Dense output with local time stepping gives incorrect results

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4399]
# Bug reports:

### Expected behavior:

Dense output with local time stepping (LTS) does not have large errors that grow linearly with the time step size.

### Current behavior:

I have a tensor that is zero at t=0. Observing with local time stepping and dense output incorrectly gives an L2 norm of O(1e-6) at t=0.

Path to evolution: `ocean:/home/geoffrey/BBH/spectre/q1spin0_develop/111622/spectre_run/h1p9csph/enforce3con/nomemmonitor/densepossibelfail/ok4`
The run sets the 3-index constraint to zero at t=0, but the observed L2 norm in the reductions h5 file is 7e-6.

### Environment:

```
SpECTRE Version: 2022.11.15
Git description: v2022.04.04-397-g2a2ba3fae3
Git branch: Enforce3ConInNumericInitialData
Git hash: 2a2ba3fae3a13179e1bcca8fcf40bab328cd3ba8
Hostname: ocean.fullerton.edu
Host system: Linux-3.10.0-957.1.3.el7.x86_64
Host system version: 3.10.0-957.1.3.el7.x86_64
Host system processor: x86_64
Boost version: 1.79.0
Charm++ version: 7.0.0
CHARM_COMPILER: /opt/ohpc/pub/apps/charm_7.0.0_gnu11_clang_smp/verbs-linux-x86_64-smp-clang-gfortran/bin/charmc
CHARM_SHARED_LIBS: OFF
CHARM_BUILDING_BLOCKS:
CHARM_CC='clang'
CHARM_CXX='clang++'
CHARM_LD='clang'
CHARM_LDXX='clang++'
CHARM_CC_FLAGS=' -DCMK_GFORTRAN -D_REENTRANT -I/opt/ohpc/pub/apps/charm_7.0.0_gnu11_clang_smp/verbs-linux-x86_64-smp-clang-gfortran/include -D__CHARMC__=1 -U_FORTIFY_SOURCE -fno-stack-protector -ftls-model=initial-exec '
CHARM_CXX_FLAGS=' -DCMK_GFORTRAN -D_REENTRANT -I/opt/ohpc/pub/apps/charm_7.0.0_gnu11_clang_smp/verbs-linux-x86_64-smp-clang-gfortran/include -D__CHARMC__=1 -U_FORTIFY_SOURCE -fno-stack-protector -ftls-model=initial-exec -std=gnu++11 '
CHARM_LD_FLAGS=' -D_REENTRANT -ftls-model=initial-exec -rdynamic -L/opt/ohpc/pub/apps/charm_7.0.0_gnu11_clang_smp/verbs-linux-x86_64-smp-clang-gfortran/lib -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-default -lldb-rand -lconverse -lpthread -lckqt -libverbs -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /opt/ohpc/pub/apps/charm_7.0.0_gnu11_clang_smp/verbs-linux-x86_64-smp-clang-gfortran/lib/conv-static.o'
CHARM_LDXX_FLAGS=' -D_REENTRANT -ftls-model=initial-exec -rdynamic -L/opt/ohpc/pub/apps/charm_7.0.0_gnu11_clang_smp/verbs-linux-x86_64-smp-clang-gfortran/lib -lmoduleEveryLB -lckmetis -lck -lmemory-default -lthreads-default -lconverse -lm -lmemory-default -lthreads-default -lldb-rand -lconverse -lpthread -lckqt -libverbs -lz -ldl -lmoduleEveryLB -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /opt/ohpc/pub/apps/charm_7.0.0_gnu11_clang_smp/verbs-linux-x86_64-smp-clang-gfortran/lib/conv-static.o'
CHARMBIN='/opt/ohpc/pub/apps/charm_7.0.0_gnu11_clang_smp/verbs-linux-x86_64-smp-clang-gfortran/bin'
CHARMINC='/opt/ohpc/pub/apps/charm_7.0.0_gnu11_clang_smp/verbs-linux-x86_64-smp-clang-gfortran/include'
CHARMLIB='/opt/ohpc/pub/apps/charm_7.0.0_gnu11_clang_smp/verbs-linux-x86_64-smp-clang-gfortran/lib'
CHARMLIBSO=''
BLAS_LIBRARIES: /opt/ohpc/pub/apps/spack2022/opt/spack/linux-centos7-broadwell/gcc-11.3.0/openblas-0.3.20-tc4qxfvqf367fkbssorninewy27t4m76/lib/libopenblas.so
LAPACK_LIBRARIES: /opt/ohpc/pub/apps/spack2022/opt/spack/linux-centos7-broadwell/gcc-11.3.0/openblas-0.3.20-tc4qxfvqf367fkbssorninewy27t4m76/lib/libopenblas.so;-lpthread;-lm;-ldl
LIBXSMM version: 1.16.1
Blaze version: 3.8
GSL version: 2.7.1
HDF5 version: 1.12.2
jemalloc version: 5.2.1
Catch version: 2.13.8
NumPy version: 1.21.1
CMake version: 3.24.1
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS:  -fuse-ld=lld
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Release
CMAKE_CXX_COMPILER: /opt/ohpc/pub/compiler/llvm/13.0.1/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 13.0.1
CMAKE_C_COMPILER: /opt/ohpc/pub/compiler/llvm/13.0.1/bin/clang
CMAKE_C_COMPILER_VERSION: 13.0.1
CMAKE_Fortran_COMPILER: /opt/ohpc/pub/compiler/gcc/11.3.0/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 11.3.0
Python version: 3.9.5
```

# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by geoffrey4444** [comment]
Here I paste a slack post from @wthrowe explaining the bug:

This bug is actually very bad.  Dense observations with LTS have an error that grows linearly with the time step size.  This is not specific to t=0, but will occur at any dense observation, even at step boundaries.  I understand the cause (the LTS adaptive-step algorithm updates the variables before dense output expects the update), but fixing it is nontrivial (and disabling adaptivity does not help).

Non-dense observations are not affected, and nothing in GTS mode is affected.

This will affect any precision measurements made, such as constraint violations.  This will also affect control-system measurements.

I recommend switching any control-system experimentation to GTS for the time being.  Continuing to use Adams-Bashforth will avoid the problems we were having with ordering DP5 output in the old experiments.  Runs without control systems can be done safely with LTS and non-dense output.  Look up StepToTimes for how to pick observation times in that mode.

**Comment by knelli2** [comment]
Constraint violations at `t = 0` for my simulations and with a possible hack from @wthrowe for LTS vs my old LTS runs and a GTS run. The LTS runs used regular triggers for output, while the GTS run used dense triggers. Haven't tried LTS with dense triggers or GTS with regular triggers.

|  | Gauge Constraint | 3 Index Constraint |
| :--: | :--: | :--: | 
| Old LTS | 2.504891753483917e-16 | 1.171029362039351e-05 |
| New LTS | 2.504891753483917e-16 | 9.254855689234238e-06 |
| GTS | 2.504891753483917e-16 | 9.254855689234238e-06 |

**Comment by knelli2** [comment]
Ok I've done a more in-depth comparison of the numbers. Here I did GTS vs LTS, with/without the hack from @wthrowe fixing this bug, and with/without setting the 3 index constraint to zero from @geoffrey4444. Everything is done at `t=0`.

First table is all output using GTS. Second table is LTS.

All rows with WT have @wthrowe's hack, and all rows with GL have @geoffrey4444's change of setting the 3 index constraint to exactly 0 after the ID is read in.

Columns with `Dense` mean I used a dense trigger to ObserveNorms. `Regular` means I used a regular trigger.

| GTS  | Dense Gauge Constraint | Regular Gauge Constraint | Dense 3 Index Constraint | Regular 3 Index Constraint |
| :--: | :--: | :--: | :--: | :--: | 
|  | 2.504891753483917e-16 | 2.504891753483917e-16 | 9.254855688961577e-06 | 9.254855688961577e-06 |
| WT  | 2.504891753483918e-16 | 2.504891753483917e-16 | 9.254855688961577e-06 | 9.254855688961577e-06 |
| GL | 2.501244021926318e-16 | 2.501244021926318e-16 | 0.000000000000000e+00 | 0.000000000000000e+00 |
| WT+GL | 2.501244021926318e-16 | 2.501244021926318e-16 | 0.000000000000000e+00 | 0.000000000000000e+00 |

| LTS  | Dense Gauge Constraint | Regular Gauge Constraint | Dense 3 Index Constraint | Regular 3 Index Constraint |
| :--: | :--: | :--: | :--: | :--: | 
|  | 1.141769286854506e-08 | 2.504891753483917e-16 | 1.336487856065117e-05 | 9.254855688961578e-06 |
| WT  | 2.504905759804451e-16 | 2.504891753483917e-16 | 9.254855688961577e-06 | 9.254855688961578e-06 |
| GL | 5.503441187819655e-08 | 2.501244021926318e-16 | 9.649148848793263e-06 | 0.000000000000000e+00 |
| WT+GL | 2.501267751799512e-16 | 2.501244021926318e-16 | 1.284005629984508e-18 | 0.000000000000000e+00 |

Trends I'd like to point out:
- The results for GTS are fairly uniform and seem independent of the WT change. Only when the GL change is applied is there any difference, and that difference is what we expect (3 index constraint being exactly 0). So @wthrowe is correct in saying that GTS isn't affected by this bug. (I believed him, but still wanted to confirm)
- For LTS, measurements done with a Regular trigger seem to be independent of the WT change (consistent with what @wthrowe said)
- For LTS Dense measurements of the gauge constraint, the WT change seems to be the dominant factor. The GL change had little effect.
- For LTS Dense measurements of the 3 index constraint, the WT change had little effect when the GL change wasn't applied. But if the GL change was applied, then the WT change made a large difference.

**Comment by geoffrey4444** [comment]
Looks like the large, linear growth in 3-index constraint I saw in my rotating Schwarzschild runs was also caused by this bug: rerunning without dense output (but still with adaptive local time stepping) eliminates the growth

![image](https://user-images.githubusercontent.com/867015/203627788-c69ece6c-0405-493c-8bbd-fe5530f8ab18.png)
