### ISSUE TITLE
DomainCreator Frame

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#443]
# Discussion

So I think for any dual frame evolution we want the DomainCreator to return the Domain in the Grid frame. Without dual frames the Grid and Inertial frames are identical. It is simplest if DomainCreators return the Domain in the Grid frame always. Can we think of any reason not to move to this? If not we should make the change now.

**Comment by wthrowe** [comment]
I think the question is which way we want to merge things for single-frame systems.  If we merge the inertial frame into the grid frame (i.e., Frame::Inertial never appears) then DomainCreators can always produce grid frame results, but equations and solutions have to handle either.  If we merge the grid frame into the inertial frame (i.e., Frame::Grid never appears) then DomainCreators have to be able to handle either frame, but equations and such can assume inertial.  It is not obvious to me which of these is better.

**Comment by nilsdeppe** [comment]
Closed with #445
