### ISSUE TITLE
Prefer Scalar<DataVector> over DataVector?

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#452]
### Discussion:

While reviewing a PR we started discussing whether to prefer `Scalar<DataVector>` over `DataVector`. These are very similar, except that the `Scalar<DataVector>` uses the `Tensor` infrastructure and so it might be conceptually more natural to use. The goal of this issue is to provide a place to discuss experiences and preferences.

**Comment by osheamonn** [comment]
What was the discussion that led to this? It seems like it'd be pretty case dependent to me. I remember on bitbucket we had an issue that `determinant` returned a `DataVector` and so couldn't be used as a compute item or as an observer until we switched it to return a `Scalar`.

**Comment by wthrowe** [comment]
This was spawned over a discussion of something in Strahlkorper.  (I forget exactly what.)  There wasn't a lot of discussion beyond realizing that none of us knew which it should be.

I think what we want to determine here is why it is case dependent and what some guidelines are for evaluating a particular case.

**Comment by nilsdeppe** [comment]
What was ultimately concluded on this is:

DataVector is fine for temporaries inside a function but functions should return Scalar<DataVector>.

@wthrowe @kidder we've had a few discussions on this. Was this the consensus?

**Comment by kidder** [comment]
Yes, this is the consensus.
