### ISSUE TITLE
Simulations crash with H5 errors when the file is read in another process

### ISSUE THREAD

**Issue by knelli2** [sxs-collaboration/spectre#4522]
# Feature request:

`h5py` [is apparently built with thread-safe hdf5](https://docs.h5py.org/en/stable/whatsnew/2.4.html?highlight=thread#thread-safety-improvements) which is why you can read data in parallel from the same read-only h5 file (it handles locks and stuff). We can't do this with out pybindings. We'll get an error. It would be nice if we could support this if we are using a thread-safe version of hdf5.

**Comment by wthrowe** [comment]
This doesn't sound like a thread-safety issue.  Reading from both in parallel would be a problem, but just having two things open is independent of threads.

**Comment by knelli2** [comment]
I meant reading from the same file in parallel on multiple threads. Updated the description

**Comment by nilsvu** [comment]
I think h5py implements its own thread safety. The issue we have is larger: Our simulations crash with HDF5 errors when another process is reading the file that the simulation is trying to write to. A workaround that @wthrowe mentioned on Slack is to set the `HDF5_USE_FILE_LOCKING=FALSE` env var. The simulation will then ignore the file lock and just write to the file. This may disrupt the reader, but at least the simulation doesn't crash. For people wondering how the HDF5 locking is implemented: https://github.com/HDFGroup/hdf5/blob/develop/doc/file-locking.md. From HDF5 version 1.10.7 onward it provides the [`H5Pset_file_locking`](https://docs.hdfgroup.org/hdf5/develop/group___f_a_p_l.html#title72) function to disable locking from within the code.

**Comment by nilsvu** [comment]
@knelli2 I hijacked this issue for the larger problem that I described above. If you think the issues are separate we can create another.
