### ISSUE TITLE
Fix sentence in 4536

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#4537]
https://github.com/sxs-collaboration/spectre/pull/4536

Deferred a grammatical thing until later because we need the PR to do simulations over the break. Will address sentence in January.

**Comment by isaaclegred** [comment]
I'll fix up the docs for the Enthalpy Tests in general, also the argument order for the Enthalpy constructor should be revisited, because it is somewhat unnatural.
