### ISSUE TITLE
GeneralizedHarmonic::Phi has wrong type

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#454]
# Bug reports:

### Expected behavior:

In Evolution/Systems/GeneralizedHarmonic/Tags.hpp,
Phi should be tnsr::iaa

### Current behavior:

Phi is tnsr::abb

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/LibraryVersions.txt` or
add its contents here.

# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by markscheel** [comment]
I can fix this in my KerrSchild PR.

**Comment by nilsdeppe** [comment]
Did this get fixed?

**Comment by markscheel** [comment]
Yes I fixed it in #455
