### ISSUE TITLE
Combine BBH and single star input files to perform binary evolutions

### ISSUE THREAD

**Issue by ffoucart** [sxs-collaboration/spectre#4574]
Objective: Use Geoffrey's BBH files and Nils' single star files to develop input files for BNS evolutions

**Comment by nilsdeppe** [comment]
- BBH: `tests/InputFiles/GeneralizedHarmonic/BinaryBlackHole.yaml`
- Single Star: `tests/InputFiles/GrMhd/GhValenciaDivClean/GhMhdTovStar.yaml`

The single star can now also be run on a cube-sphere. I'll add or update the current input file.
