### ISSUE TITLE
Improve element distribution with improved z-curve with weighting

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4582]
# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Improve distribution of elements to account not only for distance from neighboring elements (to minimize communication costs) but also weight by the element's minimum grid spacing (which affects the element's cost).
- [ ] Detail 2
- [ ] Detail 3

### Detailed discussion:
Note: @nilsvu has explored some load balancing ideas [in this commit](https://github.com/nilsvu/spectre/commit/f6c2a9f13591eadb509101efa99e1dc3582ed2a7). 

The current algorithm uses a z curve to minimize communication costs, but this leads to large amounts of idle time, especially with local adaptive time stepping...because elements with more points must take smaller time steps (because of the CFL condition) and cost more per step (since there are more points).

The first idea is to introduce a weighting, or improved cutoffs, to try to get a better initial distribution of elements that is not as poorly balanced. The goal here is not to get the optimal load balancing, but to see how much improvement we can get with a first-cut, minimal improvement to the existing z-curve strategy.

**Comment by nilsdeppe** [comment]
Current state: Nearly 2x speedup. @macedo22 is working on unit tests and code cleanup. This is great :D

**Comment by geoffrey4444** [comment]
Done with #4713
