### ISSUE TITLE
Improve time-stepping with bug fixes and performance enhancements

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4583]
# Feature request:

- [x] Fix dense output #4399 
- [ ] Support predictor-corrector Adams method to increase efficiency. If @nilsdeppe remembers correctly, @wthrowe said this would reduce cost per fix forward progress by about 3 and bring the LMM methods to roughly the same efficiency as Dormand-Prince.
- [ ] Reduce memory allocations and copies in time stepping code where possible, just to generally reduce the amount of memory allocations we do and how often we do big `memcpy` type operations. @nilsdeppe doesn't have anything specific in mind here.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Improve the time stepping infrastructure to improve performance and to fix bugs.

### Detailed discussion:

One issue resolved by these improvements is #4399 .

**Comment by wthrowe** [comment]
Is there something in particular you're asking me to do here?

**Comment by wthrowe** [comment]
Closing because I don't know what you want me to do.

**Comment by geoffrey4444** [comment]
Sorry for the delay in my reply @wthrowe ... this issue simply refers to the work you were already doing to improve the time stepper, including to fix the dense output bug #4399. If this work is already done, I'll close the issue but would like to link the relevant PRs (I looked at your recent PRs but couldn't figure out if any applied to this).

**Comment by nilsdeppe** [comment]
The other big thing is the predictor-corrector stepper to hopefully speed up the code. I think last time this came up you said it'll come post-IMEX, we mostly just want to track that this is something that could help a lot.

**Comment by wthrowe** [comment]
OK, predictor-corrector is a reasonable request.

All of #4399, IMEX, and PC require the history rewrite, which is done except that I'm trying to factor out one of the internal data structures for more general use.  (And that git is having issues with the rebase, which I have to work around somehow.)

IMEX and PC are otherwise independent, I think, but IMEX is higher priority because someone is already trying to use it.

**Comment by nilsdeppe** [comment]
Sounds good! I also think IMEX is higher priority than PC. I'll update the original comment to actually list the things we want here :)
