### ISSUE TITLE
Visualize domain diagnostics

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4588]
# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Create a standard way to visualize power monitor and jacobian diagnostic information, to make it easier to optimize domain decompositions

**Comment by nilsvu** [comment]
@nikwit @guilara what sort of plotting tools do you have that we could merge into the repo? I think both 3D visualizations in ParaView and various plots would be useful. I can contribute a script that makes plots like this:

![Image](https://user-images.githubusercontent.com/746230/214708313-4dbf9392-0358-41ab-be37-3965db853a44.png)

**Comment by guilara** [comment]
I have a basic python script (based on Niko's) that calls the python binding and makes these kinds of plots. I can clean it if you'd like me to upload it

![PowerMonitors](https://user-images.githubusercontent.com/13457788/214892521-eb317b57-da93-4da2-82e5-9c7cd4856b1b.png)

**Comment by nikwit** [comment]
I have #4611
