### ISSUE TITLE
Char speed control: interface AH, excision surface, control system

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4592]
- [x] Mark: function to get the control error $Q$ (on a branch, how how to test?) -- in progress (branch SizeControlSignal)
- [x] Kyle: write control error class that calls the control error function
- [x] Kyle: template shape control on measurement so use `BothHorizons` measurement for BBH and single horizon measurement for single BH
- [x] Kyle: make measurement class for size (how to test?)
- [x] Kyle: add to control system, executables
- [x] Send the excision surface and apparent horizon, with needed quantities interpolated onto them, to the control system. Connect to existing actuator logic, to adjust the size map.
 
### Detailed discussion:
@markscheel can start on this now, using fake excision surface data, until #4591 is ready.

3/22/23 @knelli2 once these steps are done, "it should just work"

**Comment by knelli2** [comment]
Idea for test of Mark's size control signal function:
- Put Schwarzschild solution in so we know what to expect upon output.

**Comment by geoffrey4444** [comment]
Update: size control was receiving char speeds in wrong frame (fixed in Kyle's branch)
Mark rewrote his branch to add another few arguments (like radius of excision boundary in different frames)
Ping Kyle when he gets back next week

**Comment by knelli2** [comment]
Closing because interface is all working. Now it's just implementation details. Will make a new issue.
