### ISSUE TITLE
Evolve a BBH in damped harmonic gauge

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4594]
Currently, BBHs require harmonic gauge, because starting in damped harmonic gauge at t=0 requires characteristic speed control. Once characteristic speed control is working, the BinaryBlackHole executable should start in damped harmonic gauge instead of harmonic gauge.

Depends on #4593, #4592, and #4591.

**Comment by knelli2** [comment]
@geoffrey4444 This is now a priority again. I believe from discussions I had with you on Monday (7/24) you were already planning on trying this out, you just had to make ID.

**Comment by nilsvu** [comment]
Geoffrey can do inspirals. Needs some domain optimizations and deadlock fixes (in progress).

**Comment by knelli2** [comment]
To determine if there is a bug in the DH gauge, @geoffrey4444 is coding up a boosted Kerr-Schild solution to test non-zero time derivatives. See issue #5457.

**Comment by knelli2** [comment]
@geoffrey4444 Found a bug in the DH harmonic gauge condition (#5504) and now we've been running BBH inspirals in DH for a while now so this seems to be fixed.
