### ISSUE TITLE
Initial data: can we make BBH initial data with a large outer boundary?

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4597]
Is it possible to make initial data that satisfies the following criteria?
1. converges,
2. completes within 24 hours of wall time, and
3. is at least as accurate as initial data interpolated from SpEC?

If so, great. If not, what's the trouble, and can it be fixed in a ~month timescale?

**Comment by geoffrey4444** [comment]
@AlexCarpenter46 try setting "massive" to false

**Comment by nilsvu** [comment]
Results from debugging this:

- Set `Discretization.DiscontinuousGalerkin.Massive: False`
- Tighten the linear solver tolerances sufficiently, e.g. 1e-10 relative and absolute residual.
- Configure the `RadiallyCompressedCoordinates` option, observe it, and use in `generate-xdmf --coordinates RadiallyCompressedCoordinates`
- An issue on higher multigrid levels seems to remain. Set `LinearSolver.Multigrid.MaxLevels: 1` for now.

With these settings I am able to produce BBH initial data with an outer boundary at 1e10.
