### ISSUE TITLE
Ringdown: initialize domain

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4599]
# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Enable spectre, given BBH data with a common horizon, to initialize a new domain with a single excision surface.

### Detailed discussion:
Note: Until spectre can evolve to common horizon, this can be tested by interpolating SpEC data with a common horizon.

**Comment by knelli2** [comment]
Closing in favor of #5670
