### ISSUE TITLE
Failure in Unit.PointwiseFunctions.AnalyticSolutions.Gr.Tov

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#4657]
Failure is on my dev machine and is consistent across runs.

```
  Node: 0 Proc: 0
  Line: 262 of /home/wthrowe/spectre/src/PointwiseFunctions/AnalyticSolutions/
  RelativisticEuler/Tov.cpp
  'get_element(r, i) >= 0.0 and get_element(r, i) <= outer_radius_' violated!
  Function: DataType RelativisticEuler::Solutions::TovSolution::
  mass_over_radius(const DataType &) const [DataType = double]
  Invalid radius: 3.54491 not in [0.0, 3.54491]
  
############ ASSERT FAILED ############
```

The failure is triggered by the call on line 101 of the test:
```c++
      const double interpolated_mass{
          tov_out_full.mass_over_radius(intermediate_radius) * intermediate_radius};
```

**Comment by nilsdeppe** [comment]
I get the same on my machine, only with `clang-14`. Specifically:
```cpp
Invalid radius: 3.54490770284634138 not in [0.0, 3.54490770284634094]
```
@wthrowe pointed out the outer radii between two different TOV solves differ basically by machine roundoff, but that's enough to trigger the ASSERT.

**Comment by isaaclegred** [comment]
I’m confused, isn’t the problem here that tov_out_full.mass_over_radius  is an interpolator that  for some reason doesn’t extend out to beyond intermediate_radius ?  Won’t we somehow have to hack the interpolator to get this to work?

**Comment by nilsdeppe** [comment]
@isaaclegred the bug is to do with floating point math, I think the PR change shows it fairly clearly. `1.0 + (a + 1) * b` is not equal to `2.0` in general, even if the math makes it look like should be. Here equal means _bitwise_ equal. This bug was at the bitwise level.

**Comment by isaaclegred** [comment]
Ah sorry yeah, I mean there was a floating point problem in the interpolation, but your PR fixes it in a better way then I would have!
