### ISSUE TITLE
Silence clang-tidy warning about trivially copyable moves when that becomes possible

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#470]
clang-tidy recently [added an option](https://github.com/llvm-mirror/clang-tools-extra/commit/d0bf766a6ea03e8499ca9b6f51a348387cc07b7a) to not warn on moving trivially copyable types, which is one of the most common things we NOLINT (excluding pointer arithmetic and pup functions).  It will probably be a while before we can use it, but we should remember to enable it when it becomes available (I'm guessing LLVM 6).

**Comment by nilsdeppe** [comment]
Cool, great find! I think when LLVM 6 becomes available and this is in there we should update Travis to that.

**Comment by nilsdeppe** [comment]
Once IWYU works with clang-6 we can update the docker images.

**Comment by nilsdeppe** [comment]
as an example of how to use: https://www.oclcproxy.ornl.gov/6da/ArborX/-/blob/github/fork/aprokop/fix_distributed_driver/.clang-tidy
