### ISSUE TITLE
Add size control to GH vacuum executables

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#4710]
- [x] Add Shape to the EvolveGhSingleBlackHole -- PR
- [x] Make sure the Shape map can be controlled by the control system
- [x] Add control system to executable
- [ ] Add size control to single BH
- [ ] Add size control to BBH

**Comment by geoffrey4444** [comment]
3/22/23: @knelli2 is debugging for single BH

**Comment by geoffrey4444** [comment]
In progress, will push next week when @knelli2 is back

**Comment by knelli2** [comment]
In addition to actually adding the control systems to the executables, need one more size control thing (smoothing). This will be done very soon.
