### ISSUE TITLE
Building PyTensor is slow

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#4741]
We currently instantiate 240 tensor types in `DataStructures/Tensor/Python/Tensor.cpp`, which takes quite a long time (couple of minutes, depending on the machine). Not sure how to speed that up though (suggestions welcome).

**Comment by nilsdeppe** [comment]
Building in parallel will help, so just splitting the instantiations across multiple files. It's not perfect, but it works quite well. I did this for the test of the DG time derivative action because there are so many different possible combinations there too (not 240, at least!).
