### ISSUE TITLE
Add shape map to BBH domains

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#4764]
Task list:

- [x] Add distorted frames to BBH domains, not changing any maps
- [ ] Add shape map -- PRs for single and binary domains

Both the cubical and cylindrical BBH domains should be updated in parallel.

**Comment by geoffrey4444** [comment]
3/23/23: @nilsvu has volunteered to review this and dependent PRs, and @gsb76 will help as needed with reviews
