### ISSUE TITLE
Cannot compile in docker container

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#479]
# Bug reports:

### Expected behavior:

I followed the instructions in the documentation to install in a docker container and compile the latest development version of spectre. I expected that I could compile and pass the tests.
-->

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/LibraryVersions.txt` or
add its contents here.

No such file exists in /work/spectre-build/gcc

### Detailed discussion:

Here is exactly what I did after git cloning the latest spectre repo into /Users/geoffrey/Codes/spectre/spectre. Did I mess up somewhere?

$ docker pull sxscollaboration/spectrebuildenv:latest
latest: Pulling from sxscollaboration/spectrebuildenv
8b23367590c3: Already exists 
c7feb578947e: Already exists 
ac836f06379c: Already exists 
be286dc472df: Already exists 
5533df5f353d: Already exists 
8e7e1d69cc05: Already exists 
1d0624094704: Already exists 
a5b204c6b9cc: Already exists 
295e5b82cfd1: Already exists 
db75ff0af306: Already exists 
74e9d04eb3be: Already exists 
76056e99dc8f: Already exists 
1756f35e8e68: Already exists 
7d20c941733f: Already exists 
39fd3117dd72: Already exists 
91640fefb074: Already exists 
efe8e03b8985: Already exists 
4d2fc1159b79: Already exists 
e2dd0b70f58c: Already exists 
bd8537574b20: Already exists 
735a47618936: Already exists 
152c91b693e1: Already exists 
4035480d7c2c: Already exists 
8c35413e55a2: Pulling fs layer 
cab6c497d852: Pulling fs layer 
bcaa0463fa86: Pull complete 
246663742c97: Pull complete 
cfd31f1ea693: Pull complete 
f89d1522460c: Pull complete 
c24593d4de5b: Pull complete 
8541b79d06b9: Pull complete 
fe3b6c18db6e: Pull complete 
83df23562d98: Pull complete 
23dafe57f6e7: Pull complete 
48c6ba0d51aa: Pull complete 
f3f0be9feb14: Pull complete 
a1f8461a994d: Pull complete 
10eb2bc322f0: Pull complete 
114722dfbc4e: Pull complete 
cb0349368f1f: Pull complete 
2761fdb2e59c: Pull complete 
afa32455c1fc: Pull complete 
f39795ffafc6: Pull complete 
619c9cd3cfe0: Pull complete 
92956c50bf41: Pull complete 
Digest: sha256:41ff24852e5ba5c8c9990c67e2c90257f3776d540bc0b707d00d915f4f5a707f
Status: Downloaded newer image for sxscollaboration/spectrebuildenv:latest

$ docker run -v /Users/geoffrey/Codes/spectre:/Users/geoffrey/Codes/spectre --name spectre-dev -i -t sxscollaboration/spectrebuildenv:latest /bin/bash
root@db0d984fb036:/work# exit
exit
$ docker start spectre-dev 
spectre-dev
$ docker exec -it spectre-dev /bin/bash

root@db0d984fb036:~# cd /work/charm

root@db0d984fb036:/work/charm# git apply /Users/geoffrey/Codes/spectre/spectre/support/Charm/v6.8.patch

root@db0d984fb036:/work/charm# mkdir /work/spectre-build-gcc

root@db0d984fb036:/work/charm# cd /work/spectre-build-gcc/

root@db0d984fb036:/work/spectre-build-gcc# cmake -D CHARM_ROOT=/work/charm/multicore-linux64-gcc /Users/geoffrey/Codes/spectre/spectre/
-- The CXX compiler identification is GNU 6.3.0
-- The C compiler identification is GNU 6.3.0
-- The Fortran compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found PythonInterp: /usr/bin/python (found version "2.7.13") 
-- Found Git: /usr/bin/git (found version "2.11.0") 
-- CMAKE_BUILD_TYPE not specified, setting to 'Debug'
-- Found Charm: /work/charm/multicore-linux64-gcc/bin/charmc  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") 
-- Found PY_coverxygen: /usr/local/lib/python2.7/dist-packages/coverxygen  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- BLAS_LIBRARIES:  /usr/lib/libopenblas.so
-- Found Blaze: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include  
-- Blaze include: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   program_options
-- Boost include: /usr/include
-- Boost libraries: /usr/lib/x86_64-linux-gnu/libboost_program_options.so
-- Found Brigand: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/brigand-master-ii6zujge5omvvi6zafztkpvlh7nxfemq/include  
-- Brigand include: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/brigand-master-ii6zujge5omvvi6zafztkpvlh7nxfemq/include
-- Found Catch: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/catch-1.9.1-cqv7sci5wiptei22dk26tderj5asiud6/include (found suitable version "1.9.1", minimum required is "1.8") 
-- Catch include: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/catch-1.9.1-cqv7sci5wiptei22dk26tderj5asiud6/include
-- Catch version: 1.9.1
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Found GSL: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/gsl-2.4-mayy2yz23cearokiewtgluvhrs25dq23/include (found version "2.4") 
-- GSL libs: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/gsl-2.4-mayy2yz23cearokiewtgluvhrs25dq23/lib/libgsl.so;/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/gsl-2.4-mayy2yz23cearokiewtgluvhrs25dq23/lib/libgslcblas.so
-- GSL incl: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/gsl-2.4-mayy2yz23cearokiewtgluvhrs25dq23/include
-- GSL vers: 2.4
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components:  C 
-- HDF5 libs: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so/usr/lib/x86_64-linux-gnu/libpthread.so/usr/lib/x86_64-linux-gnu/libsz.so/usr/lib/x86_64-linux-gnu/libz.so/usr/lib/x86_64-linux-gnu/libdl.so/usr/lib/x86_64-linux-gnu/libm.so
-- HDF5 incl: /usr/include/hdf5/serial
-- Found JEMALLOC: /usr/include  
-- jemalloc libs: /usr/lib/x86_64-linux-gnu/libjemalloc.so
-- jemalloc incl: /usr/include
-- Found LIBXSMM: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/libxsmm-1.8.1-h542rp74wlxr3p6bppufglx7o3salwcu/include  
-- LIBXSMM libs: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/libxsmm-1.8.1-h542rp74wlxr3p6bppufglx7o3salwcu/lib/libxsmm.a
-- LIBXSMM incl: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/libxsmm-1.8.1-h542rp74wlxr3p6bppufglx7o3salwcu/include
-- Found YAMLCPP: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/yaml-cpp-develop-hqb2x42zbphyrinxktsjws4z3rc4b2zw/include  
-- yaml-cpp libs: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/yaml-cpp-develop-hqb2x42zbphyrinxktsjws4z3rc4b2zw/lib/libyaml-cpp.so
-- yaml-cpp incl: /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/yaml-cpp-develop-hqb2x42zbphyrinxktsjws4z3rc4b2zw/include

Useful Information:
-- Git Branch: develop
-- Git Hash: 6f26c651b6a6d343bc686e59ea1d2b9550538c76
-- Build Directory: /work/spectre-build-gcc
-- Source Directory: /Users/geoffrey/Codes/spectre/spectre
-- Bin Directory: /work/spectre-build-gcc/bin/
-- CMake Modules Path: /Users/geoffrey/Codes/spectre/spectre/cmake
-- CMAKE_CXX_FLAGS: -march=native -g  -W -Wall -Wextra -Wpedantic -Wcast-align -Wcast-qual -Wdisabled-optimization -Wformat=2 -Wformat-nonliteral -Wformat-security -Wformat-y2k -Winvalid-pch -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wsign-conversion -Wstack-protector -Wswitch-default -Wunreachable-code -Wwrite-strings
-- CMAKE_CXX_LINK_FLAGS:  -L/work/charm/multicore-linux64-gcc/lib
-- CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
-- CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
-- CMAKE_EXE_LINKER_FLAGS:  -L/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/gsl-2.4-mayy2yz23cearokiewtgluvhrs25dq23/lib/
-- CMAKE_BUILD_TYPE: Debug
-- CMAKE_CXX_COMPILER: /usr/bin/c++
-- SPECTRE_LIBRARIES: /usr/lib/libopenblas.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/gsl-2.4-mayy2yz23cearokiewtgluvhrs25dq23/lib/libgsl.so;/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/gsl-2.4-mayy2yz23cearokiewtgluvhrs25dq23/lib/libgslcblas.so;-lgsl;-lgslcblas;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libjemalloc.so;/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/libxsmm-1.8.1-h542rp74wlxr3p6bppufglx7o3salwcu/lib/libxsmm.a;/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/yaml-cpp-develop-hqb2x42zbphyrinxktsjws4z3rc4b2zw/lib/libyaml-cpp.so
-- Python: /usr/bin/python
-- Python Version: 2.7.13
-- Doxygen: /usr/bin/doxygen
-- Configuring done
-- Generating done
-- Build files have been written to: /work/spectre-build-gcc
root@db0d984fb036:/work/spectre-build-gcc# make -j2 
Scanning dependencies of target SPHEREPACK
Scanning dependencies of target ApparentHorizons
[  1%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/alf.f.o
[  1%] Building CXX object src/ApparentHorizons/CMakeFiles/ApparentHorizons.dir/SpherepackIterator.cpp.o
[  1%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/divgs.f.o
[  2%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/gaqd.f.o
[  2%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/gradgs.f.o
[  3%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/hrfft.f.o
[  4%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/shags.f.o
[  4%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/shsgs.f.o
[  5%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/slapgs.f.o
[  5%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/sphcom.f.o
[  6%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/vhags.f.o
[  6%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/vhsgs.f.o
[  7%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/vrtgs.f.o
[  8%] Building Fortran object external/SPHEREPACK/CMakeFiles/SPHEREPACK.dir/vtsgs.f.o
[  9%] Linking CXX static library libApparentHorizons.a
[  9%] Built target ApparentHorizons
[  9%] Linking Fortran static library libSPHEREPACK.a
Scanning dependencies of target DataStructures
[  9%] Built target SPHEREPACK
Scanning dependencies of target Domain
[  9%] Building CXX object src/DataStructures/CMakeFiles/DataStructures.dir/DataVector.cpp.o
[  9%] Building CXX object src/Domain/CMakeFiles/Domain.dir/Block.cpp.o
In file included from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/AddExpr.h:43:0,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/VecVecAddExpr.h:43,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/typetraits/IsVecVecAddExpr.h:44,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/constraints/VecVecAddExpr.h:45,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/DVecDVecAddExpr.h:48,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/DenseVector.h:45,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/CustomVector.h:46,
                 from /Users/geoffrey/Codes/spectre/spectre/src/Utilities/PointerVector.hpp:11,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.hpp:21,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.cpp:4:
/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/Expression.h:58:8: error: 'blaze::Expression' is not a template
 struct Expression
        ^~~~~~~~~~
In file included from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.hpp:18:0,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.cpp:4:
/Users/geoffrey/Codes/spectre/spectre/src/Utilities/ConstantExpressions.hpp:19:8: note: previous declaration here
 struct Expression;
        ^~~~~~~~~~
In file included from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/VecVecAddExpr.h:43:0,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/typetraits/IsVecVecAddExpr.h:44,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/constraints/VecVecAddExpr.h:45,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/DVecDVecAddExpr.h:48,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/DenseVector.h:45,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/CustomVector.h:46,
                 from /Users/geoffrey/Codes/spectre/spectre/src/Utilities/PointerVector.hpp:11,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.hpp:21,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.cpp:4:
/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/AddExpr.h:67:23: error: expected template-name before '<' token
    : public Expression<T>
                       ^
/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/AddExpr.h:67:23: error: expected '{' before '<' token
In file included from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/DVecDVecAddExpr.h:61:0,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/DenseVector.h:45,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/CustomVector.h:46,
                 from /Users/geoffrey/Codes/spectre/spectre/src/Utilities/PointerVector.hpp:11,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.hpp:21,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.cpp:4:
/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/typetraits/IsExpression.h:69:32: error: blaze::Expression' is not a template
    static TrueType test( const Expression<U>& );
                                ^~~~~~~~~~
In file included from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/DVecDVecCrossExpr.h:51:0,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/DenseVector.h:46,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/CustomVector.h:46,
                 from /Users/geoffrey/Codes/spectre/spectre/src/Utilities/PointerVector.hpp:11,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.hpp:21,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.cpp:4:
/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/CrossExpr.h:67:23: error: expected template-name before '<' token
    : public Expression<VT>
                       ^
/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/CrossExpr.h:67:23: error: expected '{' before '<' token
In file included from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/VecVecDivExpr.h:43:0,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/typetraits/IsVecVecDivExpr.h:44,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/constraints/VecVecDivExpr.h:45,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/DVecDVecDivExpr.h:48,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/DenseVector.h:47,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/CustomVector.h:46,
                 from /Users/geoffrey/Codes/spectre/spectre/src/Utilities/PointerVector.hpp:11,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.hpp:21,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.cpp:4:
/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/DivExpr.h:68:23: error: expected template-name before '<' token
    : public Expression<T>
                       ^
/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/DivExpr.h:68:23: error: expected '{' before '<' token
In file included from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/VecVecMapExpr.h:43:0,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/DVecDVecMapExpr.h:53,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/DenseVector.h:49,
                 from /work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/CustomVector.h:46,
                 from /Users/geoffrey/Codes/spectre/spectre/src/Utilities/PointerVector.hpp:11,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.hpp:21,
                 from /Users/geoffrey/Codes/spectre/spectre/src/DataStructures/DataVector.cpp:4:
/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/BinaryMapExpr.h:67:23: error: expected template-name before '<' token
    : public Expression<T>
                       ^
/work/spack/opt/spack/linux-ubuntu17.04-x86_64/gcc-6.3.0/blaze-3.2-d3gxr2rzzezao6jhhlb426p6qgfg76su/include/blaze/math/expressions/BinaryMapExpr.h:67:23: error: expected '{' before '<' token

# Many more errors after this...

**Comment by wthrowe** [comment]
> Useful Information:
> -- Git Branch: develop
> -- Git Hash: 6f26c65

That's from October.  I think your git clone must have gone wrong somehow.

**Comment by nilsdeppe** [comment]
As Will pointed out, the hash is quite old and the recommended thing to do is update your repo. Since October we've updated library dependencies, etc. so the old hash won't work in the current docker container without installing the correct modules. The error is that the container supplies Blaze 3.2 but the old version of the code wants Blaze 3.1. 

A side note: the container is used for testing on Travis, so if it ever fails to build SpECTRE we will know immediately because all testing infrastructure will blow up.

**Comment by geoffrey4444** [comment]
Thanks for the quick reply, everyone! Looks like when I decided to start over with a fresh checkout, I forgot to sync my fork upstream. Works now!

**Comment by nilsdeppe** [comment]
Awesome, glad to hear it works!
