### ISSUE TITLE
On receiving a message, do as much work as you can

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4871]
- [ ] @wthrowe has a [branch](https://github.com/wthrowe/spectre/tree/lts_precompute) that @macedo22 is testing to see how much of an improvement this can provide

**Comment by knelli2** [comment]
```
# | Before   | After
-----------------------
1 | 00:49:36 | 00:52:46
2 | 00:50:42 | 00:52:01
3 | 00:47:09 | 00:48:39
4 | 00:51:20 | 00:52:10
```

From @macedo22. 4 identical runs before and after doing this change from @wthrowe. Since this doesn't really help, we won't focus on this at the moment. Going to close this issue.
