### ISSUE TITLE
Improve ScalarWave::PlaneWave::evolution_variables performance

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#489]
# Design improvement:

In #480 @kidder brought up that the `evolution_variables` function could be optimized to reduce redundant calculations. However, naively anyway this would cause a lot of code duplication for a function call that is not frequent. Ideally the performance should be improved without causing a lot of code duplication.

**Comment by kidder** [comment]
We don't care as we don't use Scalar Wave solutions except in testing
