### ISSUE TITLE
Execute tests on CI can pass even if executable fails

### ISSUE THREAD

**Issue by knelli2** [sxs-collaboration/spectre#4911]
This can happen if all the files are written that need to be checked, but the executable still fails. We should check error codes on CI.

**Comment by wthrowe** [comment]
Does this also affect running the test suite outside of CI?

**Comment by knelli2** [comment]
@wthrowe Yes. I was able to reproduce locally. Running ctest with verbose output, I see the single BH executable failed (it may be fixed now because @markscheel has #4907 and #4901 which fix the underlying issue of why the executable failed)

**Comment by nilsvu** [comment]
This was introduced in #4000. Fixed in #5080.
