### ISSUE TITLE
Hash function changed somewhere around AppleClang 14 / M2 chips, breaks deserializing PUP::able objects from disk

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#4944]
The symptom of the problem is this:

- You serialize a domain to disk on a machine supported by CI (e.g. writing volume data to an H5 file).
- You try to deserialize the domain with AppleClang 14.0.2 on an M2 machine (I haven't tried other versions or configurations).
- You will get `Unrecognized PUP::able::PUP_ID` errors because the hashing function used by Charm++ to turn class name strings (from pretty_type in `register_classes_with_charm`) into IDs has changed.
- Also (but less importantly) you get different observation IDs when running the same simulation with the two different compiler versions, because they're hashes as well.

It's easy to reproduce: Just run any of the Python unit tests that deserialize the domain from the `VolTestData0.h5` in the repository.

**Comment by geoffrey4444** [comment]
I have reproduced this issue on my Apple Silicon Mac by running `ctest --output-on-failure -R Python.Domain`

**Comment by nilsvu** [comment]
I tracked this down: the `pretty_type::get_name<>` differs by some whitespace when I run on Wheeler vs my machine. It calls `boost::core::demangle` on `typeid().name()`. I have verified that the `typeid().name()` hasn't changed, and I don't think the implementation of `boost::core::demangle` has changed either, so my guess is that some compiler internals like `abi::__cxa_demangle` got updated.
