### ISSUE TITLE
RK and AM time steppers with Control System

### ISSUE THREAD

**Issue by knelli2** [sxs-collaboration/spectre#5132]
- [x] Error-based global adaptive time stepping with RK methods to compare with SpEC
- [ ] Time step sizes in SpECTRE are much smaller than SpEC, even though it's AB methods. A comparison would be good.
- [x] Get control systems working with RK methods in GTS.

**Comment by wthrowe** [comment]
Context?  What is this list?

The first one is done, and I believe the second is expected behavior because of the point distribution.  And AB makes the step size smaller, not larger.

**Comment by knelli2** [comment]
@geoffrey4444 or @nilsvu could you elaborate on this? I didn't understand that well what you wanted from time stepping.

**Comment by knelli2** [comment]
@wthrowe has RK working with GTS and control systems on a branch. LTS is more complicated so may put that off a bit until IMEX is in (and we can use AM in LTS methods).

**Comment by knelli2** [comment]
Done in #6043
