### ISSUE TITLE
Read and write Strahlkorper coefficients from disk

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#5183]
We need to load Strahlkorper YLM coefficients from a file to initialize the shape of our excision surfaces, both for high-spin inspirals and for ringdowns.

**Comment by knelli2** [comment]
For writing, we'll need to write the coefficients from `ObserveSurfaceData.hpp` to an h5 dat file. For reading, currently we'll want the ability to read coefficients in the `Sphere` and `BCO` domain creators. We'll probably want support for prolonging/restricting the coefficients to the input `l_max` when reading.

**Comment by nilsvu** [comment]
@macedo22 I heard that you are working on this?

**Comment by macedo22** [comment]
Yes I'm currently trying to learn a bit about how we do IO by poking around some files and plan on meeting with @knelli2 to understand what is wanted in a more concrete sense / how and where this IO needs to happen.

**Comment by nilsvu** [comment]
Ok great!

**Comment by nilsvu** [comment]
@macedo22 please let us know if you need assistance, since this is an important task for progress :)
