### ISSUE TITLE
GH FishboneMoncrief executables don't build on develop

### ISSUE THREAD

**Issue by knelli2** [sxs-collaboration/spectre#5237]
# Bug reports:

### Expected behavior:

They build. (The non-GH ones build fine)

### Current behavior:

For the magnetized case, it complains that the `MagnetizedFmDisk` ID has private member variables because it inheirits privately from `FishboneMoncriefDisk` ID:

```cpp
class MagnetizedFmDisk
    : public virtual evolution::initial_data::InitialData,
      public MarkAsAnalyticData,
      private RelativisticEuler::Solutions::FishboneMoncriefDisk {
```

Making it public causes other issues.

For the non-magnetized case, the `WrappedGr` analytic data can't find a type alias.

### Environment:

clang-10 Debug

**Comment by nilsdeppe** [comment]
I'll take a look at this. Might not be until early next week.
