### ISSUE TITLE
Test not renamed after changing the name

### ISSUE THREAD

**Issue by carmaza** [sxs-collaboration/spectre#526]
# Feature request:

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Detailed discussion:

I changed the name of a test. After rebuilding `RunTests`, the test was listed with its old name. An explanation on how to update the test name list could be added to the documentation.

**Comment by nilsdeppe** [comment]
Addressed when the unit testing documentation was improved
