### ISSUE TITLE
Failing tests do not print full precision

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#527]
# Bug reports:

When CHECK_ITERABLE_APPROX fails, it does not print to full precision.

### Expected behavior:

Print all digits, so I can see how off the approx is.
### Current behavior:

Prints only some digits, so if off by 1.e-13 I just get FAIL 0.5=approx(0.5), e.g.

### Environment:

I just used the docker image.

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
You must use CAPTURE_PRECISE to accomplish this for individual numbers, or request a change upstream.
