### ISSUE TITLE
ReadAllVolumeDataAndDistribute cannot read in floats

### ISSUE THREAD

**Issue by knelli2** [sxs-collaboration/spectre#5299]
```
Entering phase: ImportInitialData at time 00:00:02


###############################
The following exceptions were reported during the phase: ImportInitialData
Message: Unexpected index
Type: std::bad_variant_access
```

This is the error I get when I try to read in numeric ID that was written as floats. Comes from `ReadVolumeData.hpp:85`

```cpp
(*tensor_data)[i] = std::get<DataVector>(
        volume_file
            .get_tensor_component(
                observation_id,
                tensor_name + tensor_data->component_suffix(
                                  tensor_data->get_tensor_index(i)))
            .data);
```

(specifically the `std::get`) If we want to allow reading in `float`, then this needs to change. If we don't want to allow it, then this should have a better error message.

**Comment by nilsdeppe** [comment]
I'm a bit worried about reading in floats because if you restart a simulation from floats instead of doubles, then the result will be different from if you hadn't restarted the simulation at all. I agree, the error should be useful!
