### ISSUE TITLE
Type Alias for std::decay_t<tt::remove_reference_wrapper_t<T>> to simplify maps

### ISSUE THREAD

**Issue by osheamonn** [sxs-collaboration/spectre#532]
# Feature request:

It'd make a lot of code involving maps much more readable if we had an available type alias for this much used type. 

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by kidder** [comment]
suggested name is remove_cvref_wrap
