### ISSUE TITLE
BondiSachs is broken in GhValencia executables

### ISSUE THREAD

**Issue by knelli2** [sxs-collaboration/spectre#5391]
@isaaclegred found that if you tried to run the `BondiSachsInterpolation` Event in any of the GhValencia executables, that you wouldn't get any output. We traced this issue back to the actual event that's added in the `GhValenciaDivCleanBase` is incorrect. Currently, it uses the `interp::Events::Interpolate` event which is really only used for horizon finds. What actually should be used is `interp::Events::InterpolateWithoutInterpComponent`.

However, `interp::Events::InterpolateWithoutInterpComponent` needs the metavars as a template, and we found that the derived metavars that are passed in wasn't a complete type, so the compiler complained. The only reason it's templated on the metavars is because a tag needs the metavars. But there's a base tag for that other tag so we can use that instead and then remove the metavars template.

The last thing to figure out is how this will (if at all) impact the `WithHorizon` GhValencia executables because they *do* need the `interp::Events::Interpolate` event.

**Comment by nilsvu** [comment]
What a mess, on so many levels 🙈
