### ISSUE TITLE
Parallel::printf should have defined behavior if given wrong type

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#542]
# Bug reports:

Parallel::printf("This is an int: %s\n",5);  segfaults

### Expected behavior:

It should work or tell me why it didn't

### Current behavior:

segfault

### Environment:

on wheeler

**Comment by nilsdeppe** [comment]
This is the same behavior as `printf`, so other than building a format string parser and comparing types there's nothing we can do.
