### ISSUE TITLE
Tabulated EoS Interpolator Needs to be PuP'd

### ISSUE THREAD

**Issue by pajkosmi** [sxs-collaboration/spectre#5420]
# Bug reports:

### Expected behavior:

Executables using tabulated EoS run on execution.

### Current behavior:

Code would crash at runtime, during initialization.

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/BuildInfo.txt` or
add its contents here.

# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

### Detailed discussion:

Thanks to @nilsvu, a temporary fix has been proposed in Tabulated3d.cpp/hpp at 
https://github.com/sxs-collaboration/spectre/commit/12a4f8a924fa51504b2d9b252445627f4af63dd8#diff-ddaae7dca601b96e8a65295436a5f5919891980e9c7adf782c49851ce7124350L203

**Comment by nilsvu** [comment]
@ermost could you take a look at this? Feel free to use my fix that Mike linked to, which just factors out `initialize_interpolator()` and calls is from `pup` in `if (p.isUnpacking())`. Would be good to add a test that would have caught this, which just uses the EOS after `serialize_and_deserialize()`. Just ping me if anything is unclear.

**Comment by ermost** [comment]
Thanks for spotting this @pajkosmi  and @nilsvu!
 I've added your fix and included a unit test. Have a look at #5422.
