### ISSUE TITLE
Template test functions on both double and DataVector, remove check_tensor_doubles...

### ISSUE THREAD

**Issue by osheamonn** [sxs-collaboration/spectre#548]
### Issue description

Test functions for pointwise functions should be templated on both double and DataVector and make_with_value used in the CHECK statement. This should also remove the need for check_tensor_doubles_equals... function.

**Comment by kidder** [comment]
Only `Test_KerrSchild.cpp` uses `check_tensor_doubles_equals`

**Comment by kidder** [comment]
@markscheel @geoffrey4444 @prayush (i.e. the Vacuum crowd) can one of you fix this?

**Comment by geoffrey4444** [comment]
I’ll take a look

**Comment by geoffrey4444** [comment]
Proposed fix in #1595
