### ISSUE TITLE
Doxygen 1.9.7 or later creates empty documentation html index

### ISSUE THREAD

**Issue by ncorsobh** [sxs-collaboration/spectre#5490]
# Bug reports:

### Expected behavior:

Documentation should build an html index with associated entries filled in as desired.

### Current behavior:

When running with Doxygen 1.9.7 or more recent versions, the html index is generated and constructs entries, but these entries are empty.

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/BuildInfo.txt` or
add its contents here.

[BuildInfo.txt](https://github.com/sxs-collaboration/spectre/files/12704073/BuildInfo.txt)

# Feature request:

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsvu** [comment]
Should just be a matter of upgrading https://github.com/jothepro/doxygen-awesome-css to v2.2.1.

**Comment by wthrowe** [comment]
Can we get this done?  My distro's dropped support for 1.9.6.

**Comment by kidder** [comment]
> Should just be a matter of upgrading https://github.com/jothepro/doxygen-awesome-css to v2.2.1.

no, it's not...

**Comment by knelli2** [comment]
@nilsvu Assigning you since you added the `doxygen-awesome-css`

**Comment by wthrowe** [comment]
@nilsvu This has now become an actual problem for me.  Can you please look into this?

**Comment by kidder** [comment]
I'm about to make a PR fixing it...
