### ISSUE TITLE
Suspicious code in Test_Element

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#551]
As far as I can tell, [this test](https://github.com/sxs-collaboration/spectre/blob/develop/tests/Unit/Domain/Test_Element.cpp) is constructing a cluster of Elements like this,
```
-------------
| 4 |   | 4 |
|---| 1 |---|
| 7 |   | 7 |
-------------
```
and then checks,
```
CHECK(element.number_of_neighbors() == 4);
```

Neither of these makes sense in 1 dimension, but the same code is called in 1,2,3 dimensions.

Is this a logic error that needs to be fixed? Or an intentional (ab)use of infrastructure that needs to be documented?

# Bug reports:

### Environment:

Add as an attachment `$SPECTRE_BUILD_DIR/LibraryVersions.txt` or
add its contents here.

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by wthrowe** [comment]
While I can imagine some esoteric uses for it, forbidding having more than one neighbor per end in 1D sounds like a good idea to me.  It's certainly not something we'd want for any normal simulation and preventing it might catch some AMR bugs for us.

**Comment by nilsdeppe** [comment]
@kidder progress on this?
