### ISSUE TITLE
rename db::AddTags to db::AddSimpleTags

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#555]
# Feature request:

We have started referring to non-compute items in the DataBox as simple items, so we should update our naming conventions to reflect this.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

**Comment by nilsvu** [comment]
How about `AddValueTags` instead of `AddSimpleTags`, to make it clearer what‘s the difference to compute items?

**Comment by nilsdeppe** [comment]
ComputeItemsTags -> ComputeTags
