### ISSUE TITLE
Parallel::printf is not atomic

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#5722]
The deadlock output from `PrintElementInfo` is written by `Parallel::printf("%s", ss.str())`, but output from different elements is interleaved.  I don't know if the elements were on separate nodes.

Here's an example where we have boundary history information followed by the second half of the output of a `TimeStepId`:
```
   Key: (+2, [B19,(L2I2,L2I0,L1I0)]), history:
    Local Data:
     Time: 0:Slab[0.0000000000000000e+00,1.0000000000000001e-01]:0/1:0:0.0000000000000000e+00 (order 2)
     Time: 0:Slab[0.0000000000000000e+00,1.0000000000000001e-01]:0/1:1:1.9531250000000001e-04
     Time: 0:Slab[0.0000000000000000e+00,1.0000000000000001e-01]:1/16384:0:6.1035156250000003e-06 (order 2)
    Remote Data:
     Time: 0:Slab[0.0000000000000000e+00,1.0000000000000001e-01]:0/1:0:0.0000000000000000e+00 (order 18446744073709551615)
     Time: 0:Slab[0.0000000000000000e+00,1.0000000000000001e-01]:0/1:1:1.9531250000000001e-04
1.0000000000000001e-01]:1/512:0
    Key: (+1, [B8,(L2I0,L2I3,L1I0)]), next time: 0:Slab[0.0000000000000000e+00,1.0000000000000001e-01]:1/512:0
    Key: (-1, [B8,(L2I0,L2I1,L1I0)]), next time: 0:Slab[0.0000000000000000e+00,1.0000000000000001e-01]:1/512:0
    Key: (+2, [B8,(L2I0,L2I2,L1I1)]), next time: 0:Slab[0.0000000000000000e+00,1.0000000000000001e-01]:1/512:0
    Key: (+0, [B8,(L2I1,L2I2,L1I0)]), next time: 0:Slab[0.0000000000000000e+00,1.0000000000000001e-01]:1/512:0
```

**Comment by knelli2** [comment]
The [Charm docs](https://charm.readthedocs.io/en/latest/charm++/manual.html#terminal-i-o) says that `CkPrintf` is supposed to be atomic...

**Comment by knelli2** [comment]
The [Charm docs](https://charm.readthedocs.io/en/latest/converse/manual.html#input-output) also have `CmiPrintf` but I don't believe we use converse stuff.

**Comment by wthrowe** [comment]
They're the same thing (from charm.h):
```c++
#define CkPrintf                CmiPrintf
```

**Comment by knelli2** [comment]
Strange that we haven't run into this before though. I will note that the runs this output came from were done on the new Intel icelake nodes on CaltechHPC. Wonder if that had anything to do with it?

**Comment by wthrowe** [comment]
It may have to do with the amount of data printed from a single call.  The deadlock stuff can get pretty long.

Which charm backend is being used?

**Comment by knelli2** [comment]
This was `mpi-linux-x86_64-smp` using Intel MPI 2021.11. However, I did built MPI and charm on the old nodes (skylake) and just ran them on the new nodes (icelake)

**Comment by kidder** [comment]
I've made a simple executable to help test this (see #5724).  It runs fine on my desktop for small number of lines and array elements.  I'm sure @wthrowe or someone else could quickly write a script to check an arbitrary amount of output.   It could also be easily extended to create more components.

**Comment by wthrowe** [comment]
I can't seem to reproduce it locally with the executable from #5724, but I can easily on one wheeler node by increasing the number of lines to 500.  (I also increased the number of elements to 1000, but I see errors very fast so I doubt that matters.)

Counting, it clearly prints blocks of 8192 characters atomically, but strings longer than that can come out in several 8192-byte chunks.

**Comment by wthrowe** [comment]
Actually, it's smaller than that.  I see a 4096-byte block, so some power of two at most 4096.

**Comment by knelli2** [comment]
On a BBH run I did which had a lot of debugging output, I got some lines like this

```
[B7,(L2I3,L2[B3,(L1I0,L1I1,L2I0)]  0.000195312  (0.000390625) (inf): 0.000195312 Slab[0,0.1]:1/512
[B17,(L1I1,L1I0,[B11,(L2I3,L2I1,L1I0)]  0.000195312  (0.000390625) (inf): 0.000195312 Slab[0,0.1]:1/512
[B5,(L1I0,L1I0,L2I2)]  0.000[B1,(L1I1,L1I1,L2I3)]  0.000195312  (0.000390625) (inf): 0.000195312 Slab[0,0.1]:1/512
[B9,(L2I3,L2I[B2,(L1I1,L1I1,L2I3)]  0.000195312  (0.000390625) (inf): 0.000195312 Slab[0,0.1]:1/512
[B9,(L2I2,L2I1,L1I0)]  0.[B1,(L1I0,L1I1,L2I1)]  0.000195312  (0.000390625) (inf): 0.000195312 Slab[0,0.1]:1/512
[B9,(L2I2,L2I1,L1I0)]  0.000195312  ([B0,(L1I0,L1I0,L2I1)]  0.000195312  (0.000390625) (inf): 0.000195312 Slab[0,0.1]:1/512
[B2,(L1I0,L1I1,L2I2)]  0.000[B10,(L2I1,L2I0,L1I0)]  0.000195312  (0.000390625) (inf): 0.000195312 Slab[0,0.1]:1/512
[B2,(L1I0,L1I1,L2I2)]  0.000[B17,(L1I1,L1I0,L2I0)]  0.000195312  (0.000390625) (inf): 0.000195312 Slab[0,0.1]:1/512
```

Here are the number of bytes for each line that were written before the stream was interrupted by another elements' output:

1. 12
2. 16
3. 28
4. 13
5. 25
6. 37
7. 28
8. 28

There does not seem to be a minimum number of bytes in a block that is written, so it appears as if `CkPrintf` isn't atomic at all.

**Comment by nilsdeppe** [comment]
The closest to a possible culprit I've been able to find is: https://github.com/UIUC-PPL/charm/blob/32de593b61e6763d5726cc6c87e4c91f8a4e757f/src/arch/verbs/machine.C#L250

Edit:

There is also this: https://charm.readthedocs.io/en/latest/faq/manual.html#my-debugging-printouts-seem-to-be-out-of-order-how-can-i-prevent-this which is related but I'm not sure it's really what we're seeing. Likely it's the buffer. Sanjay will let me know what buffer we should increase to get around this.
