### ISSUE TITLE
I/O is broken with HDF5 1.14.3

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#5812]
Upstream bug causes FPEs when initializing the HDF5 library, crashing SpECTRE:  https://github.com/HDFGroup/hdf5/issues/3831

Marked fixed in HDF5 1.14.4, but I haven't tested.

We could presumably fix this by disabling FPEs during the initialization, but initialization seems to be done implicitly the first time an HDF5 function (maybe only some) is called, so it isn't obvious where all the possible calls are.

**Comment by nilsvu** [comment]
We could emit an incompatibility error in cmake if this specific version is used.

**Comment by wthrowe** [comment]
It would be nice to have some check, but it looks like spack at least wants to backport the fix (https://github.com/spack/spack/pull/42880), so it would also be nice if we didn't prevent patched versions from working.

I'll see if I can find an easy way to detect the problem in cmake, otherwise we'll have to choose between the two.

**Comment by wthrowe** [comment]
Submitted #5819 to add a cmake check for FPEs.
