### ISSUE TITLE
Linux + clang build failure

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#59]
I am trying to compile SpECTRE with clang on a Linux machine. The machine is set up according to the installation notes:

* llvm & SpECTRE deps installed using Spack
* Charm++ compiled using `./build charm++ multicore-linux64 clang -j8 --with-production` and patched

I am running the following CMake command for SpECTRE:
```
cmake -D CMAKE_CXX_COMPILER=clang++ -D CMAKE_C_COMPILER=clang -D CMAKE_Fortran_COMPILER=gfortran -D CHARM_ROOT=/home/francois/code/charm/multicore-linux64-clang ..
```

I get the following error:
```
[snip]
-- CMAKE_BUILD_TYPE: Debug
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LIBCXX (missing: LIBCXX_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLIBCXX.cmake:68 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/SetupLibCXX.cmake:5 (find_package)
  CMakeLists.txt:31 (include)
```

I *am* able to compile other projects with `clang++ -stdlib=libc++ ...`, so the library should be findable.

**Comment by nilsdeppe** [comment]
Can you run `ls /usr/include/c++/v1/` and post the output? Do you know where the libc++ headers are located on your machine? This is not a Linux general issue since it works on Arch and Ubuntu. We probably need to add another default path to the find_package routine.

**Comment by fmahebert** [comment]
Ok, this sounds like the result of using Spack to install llvm. My headers are in
```
~/spack/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/llvm-3.8.1-crbzdzqemjt4kdu6kbnsulnmgz2zuojv/include/c++/v1/
```
which is obviously highly variable.

**Comment by nilsdeppe** [comment]
Yes, I assume you loaded the corresponding Spack module before running cmake? If so and it doesn't find it you can set the CMake variable `-D LIBCXX_ROOT=/home/fhebert/spack/opt/spack/linux-fedora25-x86_64/gcc-6.3.1/llvm-3.8.1-crbzdzqemjt4kdu6kbnsulnmgz2zuojv/`
