### ISSUE TITLE
Add CLI to quickly plot trajectories of binaries

### ISSUE THREAD

**Issue by knelli2** [sxs-collaboration/spectre#5955]
Add a new CLI endpoint `spectre plot trajectories` that uses data written to disk to plot the trajectories of the two objects in a binary. This will be added to the growing list of `spectre plot` utilities in the `src/Visualization/Python` directory. This endpoint should

- Take a number of h5 files as arguments (so we can support multiple segments)
- optional paramters for subfile names that hold the trajectories
  - Default should be `/ApparentHorizons/ControlSystemAhA_Centers` and `/ApparentHorizons/ControlSystemAhB_Centers`
- Take some plotting options like title, x-label, y-label, etc., similar to the other plotting utilities.

To start writing this, take a look at
- `src/Visualization/Python/PlotMemoryMonitors.py`
- `src/Visualization/Python/PlotSizeControl.py`
- `src/Visualization/Python/PlotAlongLine.py`

If you have any questions, feel free to ask here or reach out

**Comment by vtommasini** [comment]
This is my pull request for the CLI: https://github.com/sxs-collaboration/spectre/pull/5976

**Comment by nilsvu** [comment]
- [x] Done in #5976
