### ISSUE TITLE
Tests failing when FPEs are reenabled

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#5983]
When RunTests was split into multiple executables, a chunk of the initialization code was lost, most notably enabling FPEs in most of the unit tests.  I've reenabled then in #5982, but this causes tests to fail.  This issue is to organize getting those fixed so the PR can be merged.  I've attempted to identify the causes of the failing tests and who made the changes.  Apologies if I've misidentified a cause.  You should be able to reproduce the problem by checking out my PR.

@isaaclegred:
* Unit.GrMhd.ValenciaDivClean.PrimitiveFromConservative - overflow in Kastaun

@knelli2:
* Unit.ControlSystem.TimescaleTuner - overflow when `decrease_timescale_threshold` is large

@nilsdeppe:
* Unit.Evolution.Systems.GhValenciaDivClean.Subcell.FixConsAndComputePrims - SIMD
* Unit.Evolution.Systems.ValenciaDivClean.Subcell.FixConsAndComputePrims - SIMD
* Unit.Evolution.GrMhd.ValenciaDivClean.FixConservatives - SIMD
* Unit.Numerical.RootFinding.TOMS748 - presumably related to the SIMD rewrite, although the first failure is not in SIMD code

@Sizheng-Ma:
* Unit.Evolution.Systems.Cce.Actions.KleinGordonH5BoundaryCommunication - sets the final time to NaN

Don't know:
* Unit.Evolution.Systems.ValenciaDivClean.Subcell.TciOnDgGrid - underflow in Kastaun

**Comment by nilsdeppe** [comment]
#6265 I think generally addressed this. There were a couple MC tests I had to disable, but we are not using that code in any evolution and the issues will need to get resolved for that anyway.

@wthrowe are you okay closing this as done?

**Comment by wthrowe** [comment]
Yeah, this is done.
