### ISSUE TITLE
BBH domain: translate inner spheres to increase size of cubes

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#6092]
We currently have the problem that the excisions grow larger than the inner cubes of the BBH domain, which crashes simulations because only the inner cubes can be deformed to conform to horizons.

Here's the domain at the start of the simulation:

![Bildschirmfoto 2024-06-13 um 11 39 24](https://github.com/sxs-collaboration/spectre/assets/746230/f51fce9a-367b-4efb-9f29-223f97b8e9cf)

And here it is close to merger, right before it crashes:

![image (1)](https://github.com/sxs-collaboration/spectre/assets/746230/a36be43e-098b-4d1d-845e-bb76a61edd91)

So to fix this, we can increase the size of the inner cubes, which we can do by translating the inner spheres within the inner cubes slightly towards the cutting plane at the center of the domain. We have to make sure to retain the equiangular map in the spheres and adjust the shape transition functions in the inner cubes.

**Comment by knelli2** [comment]
Related to #5459

**Comment by macedo22** [comment]
Addressed by #6214, #6234, and #6243
