### ISSUE TITLE
ID control should run first iteration in a subdirectory

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#6328]
Having the later iterations as subdirectories of the first iteration is confusing.  It looks like iteration 0 is the final result.

**Comment by nilsvu** [comment]
Yes absolutely. We haven't decided on a directory structure yet.

**Comment by iago-mendes** [comment]
Should this issue be closed because of #6379?

**Comment by nilsvu** [comment]
Yes, thanks for doing this @iago-mendes !
