### ISSUE TITLE
Is there a way to use spECTRE as shared libraries? without any python binding.

### ISSUE THREAD

**Issue by thisismeamir** [sxs-collaboration/spectre#6345]
I'm not a python user and most of the scientific projects I have are either in C/C++ or in Java/Kotlin. I have a project [Kotlin For Science](https://github.com/independent-society-of-knowledge/kotlin-for-science) in which we are introducing useful libraries in science for Kotlin, a statically typed general purpose language by Jetbrains (and also open-source). 

Is there a way to build the project for shared libraries, without the python bindings? because I only need the computational parts. 

Other than this I want to use it in pure C/C++ projects. and while compiling I have troubles with python modules that are inside the build process.

**Comment by kidder** [comment]
See https://spectre-code.org/spectre_build_system.html for a complete list of options to control the build.  In particular, for your question, `BUILD_SHARED_LIBS` and `BUILD_PYTHON_BINDINGS`
