### ISSUE TITLE
GCC 7 AXV512 abs_pd bug (Stampede2, etc.)

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#672]
# Bug reports:

Compilation with AVX512 fails because the `abs_pd` functions incorrectly take an `mm512` type instead of an `mm512d`. The fix for this is changing two lines in `avx512fintrin.h`:

```
_mm512_abs_pd (__m512d __A)

_mm512_mask_abs_pd (__m512d __W, __mmask8 __U, __m512d __A)
```
Unfortunately, normally someone with root access needs to patch the GCC header files. However, understandably, sys admins of supercomputers can be a bit reluctant to patching their GCC installations, so we need a workaround. Likely the best thing to do is to make a copy of the relevant file from the system GCC installation, patch the relevant lines, and then have the build system include the header file instead of the system header.

**Comment by eschnett** [comment]
I recommend against patching source files. Instead, I would define locally a macro or an inline function that takes the correct arguments, and which casts the argument to the type that `_mm512_mask_abs_pd` wrongly expects. The cast has no run-time cost. This mechanism would be conditional on the compiler vendor and compiler version (or on an autoconf test).

**Comment by nilsdeppe** [comment]
This is now fixed in Blaze.
