### ISSUE TITLE
RunTests doesn't tell you tests of failures pass when it should

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#682]
# Bug reports:

From $SPECTRE_ROOT, do `./bin/RunTests Unit.ErrorHandling.AbortWithErrorMessage.Error`. 

### Expected behavior:
Message saying the test passed.

### Current behavior:
The test fails, letting the ERROR cause the code to abort, instead of reporting that it passes. Note that the test does pass if you run all the tests with ctest.

### Environment:

# (I just used the docker container)
CMake Version: 3.9.1
SpECTRE Version: 0.0.0
SpECTRE branch: GeneralizedEigenvalue2
SpECTRE hash: 4ef8ed1defc1fd387157b80a1e174102093415cc
Hostname: ba413868db9e
Host system: Linux-4.9.60-linuxkit-aufs
Host system version: 4.9.60-linuxkit-aufs
Host system processor: x86_64
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS: 
CMAKE_CXX_FLAGS_DEBUG: -g
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_LINK_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_LINK_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/local/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 5.0.0
CMAKE_C_COMPILER: /usr/local/bin/clang
CMAKE_C_COMPILER_VERSION: 5.0.0
CMAKE_Fortran_COMPILER: /usr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 7.2.0
Python Version: 2.7.14
Charm Version:  6.8.0
BLAS_LIBRARIES:  /usr/lib/x86_64-linux-gnu/libopenblas.so
Blaze Version:  3.2
Boost Version:  1.62.0
Catch Version:  2.1.0
Google Benchmark Found
GSL Version:  2.4
HDF5 Version:  1.10.0.1
jemalloc Version:  ..
LIBXSMM Version:  1.8.1
NumPy Version:  1.14.2

# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

### Detailed discussion:

**Comment by kidder** [comment]
This does what it is supposed to do, run an executable thats fails with an error; if you want to run a single test and get what you expect you should for pass/failure you need to 
`ctest -R Unit.ErrorHandling.AbortWithErrorMessage.Error`
