### ISSUE TITLE
Allow constructing from different options

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#694]
# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

It would be great to be able to construct a class from the input file, but to be able to select which constructor is called. For example, consider a class that is constructible with either `size_t, size_t` or `std::array<size_t, 2>, size_t`. Let `A, B, X, Y` be option structs with types `size_t, size_t, std::array<size_t, 2>, size_t` respectively. Then the `options` list in the class being constructed could be `using options = tmpl::list<tmpl::list<A, B>, tmpl::list<X, Y>>;`. In the input file we could then do:
```
Klass:
  A: 2
  B: 4
```
or
```
Klass:
  X: [5, 8]
  Y: 7
```

**Comment by nilsdeppe** [comment]
@markscheel does this capture what you want?

**Comment by nilsdeppe** [comment]
@markscheel does this capture what you want?

**Comment by kidder** [comment]
@markscheel does this capture what you want?

**Comment by markscheel** [comment]
Yes.  I think the reason I was thinking about this was to add the ability to construct a Strahlkorper (for instance) by specifying L_max, M_max, or by only specifying L_max.

**Comment by wthrowe** [comment]
Done in #2625
