### ISSUE TITLE
use git-hub pages instead of netlify to host spectre-code.org

### ISSUE THREAD

**Issue by kidder** [sxs-collaboration/spectre#714]
# Feature request:

### Component:

- [ ] Code
- [x] Documentation
- [x] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

### Detailed discussion:
1) point spectre-code.org back to github-pages
2) setup let's encrypt certificates with github-pages
3) delete netlify account

**Comment by nilsdeppe** [comment]
Done.
