### ISSUE TITLE
Distinguish between block logical coordinates and element logical coordinates everywhere

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#720]
# Feature request:

There are two types of logical coordinates: Block logical coordinates that go from -1 to +1 in each dimension in a Block, and Element logical coordinates that go from -1 to +1 in each dimension in an Element.

It is unclear which one of these is referred to by `tnsr::I<T,Dim,Frame::Logical>`.
I suggest replacing `Frame::Logical` by `Frame::BlockLogical` and `Frame::ElementLogical`.

I also suggest that any documentation that uses the phrase "logical coordinates" throughout the code be clarified as to which one is meant.

### Component:

- [x] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by kidder** [comment]
fixed in #3365 and #3559
