### ISSUE TITLE
Documentation improvements on adding executables

### ISSUE THREAD

**Issue by mar-celine** [sxs-collaboration/spectre#731]
# Feature request:

It is currently unclear what is the correct, simple way to add an executable for testing purposes.
Looking at the three existing cpps for executables (Benchmark, DebugPreprocessor, and ParallelInfo)
I cannot determine what it is about each of them that makes it an executable. It is not clear which is the method that stands in for `main`, or what additional (e.g. Charm) things need to be done to have a minimal working executable to interface with SpECTRE objects. Can there be an example executable added that does this?

(In addition, I also think it would be useful to have tutorial executables that new users can use to jump into immediately seeing how the code works - for example, having an executable that gives block information given corner numberings would be an easy way to learn how to construct a domain using corner numberings - this could be done using the testing infrastructure but I feel that adds additional overhead that a new user might not need)

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
Your request is probably more complicated than you expected. There are a few different scenarios and if you tell me which one you want I can add an explanation for that first.

- Evolution executable (e.g. `Evolution/Systems/Executables`)
- An executable that uses Charm++ to run in parallel, e.g. `Executables/ParallelInfo`
- An executable that does not use Charm++ to run in parallel and supplies its own `main`
- An executable that uses Charm++ to run in parallel but supplies its own `main`
- An executable that uses custom compilation or linking flags, e.g. `DebugPreprocessor`

A related question is where the executable should go. I think `Executables` should be only for very generic things, like `ParallelInfo` `Benchmark` and `DebugPreprocessor`. Things that are tied to specific libraries should go into, e.g. `Domain/Executables`. All executables will get dumped into the `BUILD_DIR/bin` anyway, so there's no harm in spreading them out.

**Comment by mar-celine** [comment]
Looking long term I would like to have a tutorials directory of executables, but I am opening this issue because @dkvieira (and myself shortly after) would like to start writing executables using the TOV solver

**Comment by nilsdeppe** [comment]
Sorry, I don't understand a couple things:
- Why do you need a tutorials directory of executables and where?
- What do you mean by executables for using the TOV solver? Is one than one necessary?

**Comment by mar-celine** [comment]
* I think it would be convenient to have them all collected in a single place for new users to look at.
 * SpEC currently has two executables which use the TOV solver, one for a detailed solution of a single star and one which give a summarized version for a sequence of stars. I am also working on one which gives summarized information for a sequence of equations of state - I would like to have each of these as executables in SpECTRE too.

**Comment by nilsdeppe** [comment]
Ah okay.
- I don't think having all the source files in one place is the right idea. I think you want the source files in the relevant subdirectory, eg. `domain` or `PointwiseFunctions/AnalyticSolutions`. This is to reduce dependencies between directories.
- Okay, that sounds not unreasonable, though couldn't the differences just be controlled by an input file or command line arguments? It seems like all 3 will do almost the exact same thing.

**Comment by nilsdeppe** [comment]
I also think for this you will not want parallelization, but just a single executable with its own main.

**Comment by mar-celine** [comment]
* Your first point makes sense :+1: what about the organization in the build directories?
* They are pretty similar, two things I worry about though is 1:
  that the amount of code put into a single source makes it harder to decipher and make changes quickly
  for a user just beginning to look at it and 2:
  the complexity of the input files growing as the user has to set all the switches correctly.
  I do like the setup in SpEC's TOV executables where the source file and the input file are very compact, and partitioned off from any other code that might be distracting or confusing. If these executables can be merged with minimal cost to the complexity of the input files then I agree they should be merged, at least in SpECTRE.

**Comment by nilsdeppe** [comment]
- Everything goes into `BUILD_DIR/bin`. This is how Linux is organized.
- You can use an argument flag to control which approach gets used. You can then check the flag early on and go to the correct function. This means that you will have different input files for the different cases, but still only one executable. Having many executables that link in a lot of the code base will mean we will run out of disk space quickly....

**Comment by mar-celine** [comment]
That makes sense to me, thanks!

**Comment by kidder** [comment]
@gsb76 have #764 and #751 done enough to satisfy this issue, or do you want more?

**Comment by mar-celine** [comment]
Closed as #764 and #751 can be used as starting points for others to create executables. Thanks!
