### ISSUE TITLE
Add point_in_range_of_map to all CoordinateMaps.

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#733]
# Feature request:

For certain applications (horizon finding, wave extraction, visualization) we will have a set of arbitrary points in Inertial coordinates (e.g. the points on a horizon or the points on a wave extraction surface) and we will want to know which Block each point belongs too (so that we can evaluate metric functions or other variables at that point).

To do this, we call `block.coordinate_map().inverse()` on each point for each block, and if the result is in [-1,1] in each dimension, then that point is inside that block.

But for some maps, block.coordinate_map().inverse() may fail if the point is very far outside the Block.  And additionally, a CoordinateMap could often decide if the point is outside the Block even without calling the inverse map.

So I propose a function in each concrete CoordinateMap
>> template<size_t Dim>
>> InverseInfo<Dim> point_in_range_of_map(const std::array<double,Dim>& target_point)`

where InverseInfo is

>> template<size_t  Dim>
>> struct InverseInfo {
>>     bool target_is_in_range_of_map;
>>     std::array<double,Dim> src_point;
>> };

The bool is false if the target_point cannot be reached by the map, e.g. if the map is a 1D AffineMap from [-1,1] -> [3,5] and the target_point is 6.  If the bool is false, then src_point can be filled with NaNs.

The code that determines which points are within each block can call this function and immediately move on to the next block if the bool is false.

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

### Detailed discussion:

We discussed this at the Wednesday meeting.  A few points:

 - point_in_range_of_map would be needed only for doubles, not for DataVectors.
 - Computing the bool is usually much easier than computing the inverse map.
 - point_in_range_of_map can just call `inverse` (unless it determines that the bool is false, in which case it should fill the src_point with NaNs).
 - point_in_range_of_map is in SpEC, and is more complicated there because the CompositionMap in SpEC is a CoordinateMap.  For a composition map, you need to call each inverse map before calling point_in_range_of_map of the composed map.

**Comment by kidder** [comment]
PR #794 is addressing this

**Comment by wthrowe** [comment]
Fixed by #794.
