### ISSUE TITLE
Move to travis-ci.com to support GitHub Checks API

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#747]
# Feature request:

It should be possible now to migrate spectre CI from travis-ci.org over to travis-ci.com. This makes detailed CI results show up in the _Checks_ tab in PRs. More info: https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [x] Continuous integration

**Comment by kidder** [comment]
This is not yet possible see https://docs.travis-ci.com/user/open-source-on-travis-ci-com

**Comment by nilsvu** [comment]
We have migrated to GitHub actions, see #1802.
