### ISSUE TITLE
Improve BulgedCube documentation.

### ISSUE THREAD

**Issue by markscheel** [sxs-collaboration/spectre#780]
A few minor things need fixing in documentation for BulgedCube:

 - `radius_of_other_surface` is mentioned in documentation once but is never defined and apparently never used elsewhere.

- The quantity `r` in the final equation for the map is not defined.

- I don't understand the sentence at the end  "In the case where the same coordinates are used for the cube and the sphere, we have xi=Xi, etc."   I thought xi=Xi meant we are using equidistant and not equiangular coordinates.  So what does "same coordinates are used for the cube and the sphere" mean?  And also, what is the difference between Zeta and zeta?  I don't see any zeta transformation in the equiangular maps.

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by mar-celine** [comment]
To address your questions before making changes to the documentation:
`radius_of_other_surface`, `R`, and `r` all refer to the same value - I will make these consistent.

As for your second question - I've realized the documentation is inaccurate. The lower case greek coordinates come from doing linear interpolation between the surfaces, whereas the capital greek letters are used for both the flat and spherical surface coordinates - (they are either both equidistant or both equiangular throughout). The simplification in the final line comes from generalizing the linear interpolation between surfaces to an interpolation that matches the choice of coordinates used on the surfaces. That is to say, if equidistant coordinates are chosen on both surfaces, the corresponding interpolation to do would be linear interpolation, and if equiangular coordinates are used on the surfaces, one should actually do a nonlinear tan map interpolation. In other words, the formula on the final line is obtained when all of the logical coordinates are mapped the same way; both the ones parameterizing the surface and the one used for the interpolation.

Zeta is the equiangular analog to zeta just as Xi and Eta are - but I did not state this in the documentation. I will correct these things. Thanks again for the feedback!

**Comment by mar-celine** [comment]
*Correction*: There are two interpolations being done in BulgedCube - the first interpolation between the flat and spherical surfaces (along the interpolation parameter `s`) is always linear. The second interpolation between bulged faces on opposite sides of the bulgedcube is what is chosen to be either linear or nonlinear.

**Comment by markscheel** [comment]
Another thing: in the code, there is a quantity rho which is solved for in the root finder for the inverse function. I assume that this rho is given by rho^2 = Xi^2 + Eta^2 + Zeta^2, but I can't find this documented. (This would have been helpful for figuring out how the inverse function works).

**Comment by nilsdeppe** [comment]
Progress update?

**Comment by mar-celine** [comment]
@nilsdeppe I'll come back to this once the my #771 PR is done with

**Comment by mar-celine** [comment]
Addressed in #860
