### ISSUE TITLE
Reduce dependence on Metavariables

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#797]
# Proposition:

I think we should rely less on types in Metavariables because it makes the code harder to understand, as opposed to explicitly passing the information down to where it is needed. E.g. extracting `Metavariables::system::variables_tag` somewhere is less explicit that templating the same type on a `VariablesTag`.
Ubiquitous information like `Dim` might be reasonable to extract from Metavariables, but relying on types in Metavariables should be a very well-reasoned decision. The `temporal_id` might be another candidate. Others I think we should reconsider, such as all types in `ScalarWave::System`. In particular, I'd like to propose to be careful with adding more and more types to Metavariables or System in the future and instead make dependencies on such type explicit as template parameters.

**Comment by nilsdeppe** [comment]
We tried this previously and it was a mess...
