### ISSUE TITLE
Provide a way to evaluate basis functions on the mesh

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#801]
There does not seem to be any way to get the value of a basis function on the mesh, even restricted to 1D.  This would be useful in tests when one needs orthogonal polynomials.

**Comment by nilsvu** [comment]
There is the private function `Spectral::compute_basis_function_value<Basis>(size_t k, double x) -> double` (changes to `DataVector` in #716). You can forward-declare and link `Spectral` to use it, or I could make it public, too.

**Comment by wthrowe** [comment]
The DataVector version of that looks like what I wanted, yeah.  It should be public.  I've had to debug code that broke in bizarre ways because some developer decided to forward declare a function defined in an unrelated place.

**Comment by nilsvu** [comment]
Sure, if this is going to be used anywhere it should be public, just wasn't intended to be part of the `Spectral` interface so far. If we only need it in tests, should this still be public?
