### ISSUE TITLE
Unit.GrMhd.ValenciaDivClean.Sources fails with seed 196483431

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#804]
Roundoff-level differences.

I don't know the correct solution here.  Someone who knows Valencia should look at it.

**Comment by osheamonn** [comment]
This has happened with a few Pypp based tests. Should we relax the approx used in `check_with_random_values` so that we don't have to worry about this on a test by test basis?

**Comment by kidder** [comment]
That would be fine with me

**Comment by osheamonn** [comment]
If that's fine with everyone then I'll do it.

**Comment by osheamonn** [comment]
Closed via #819
