### ISSUE TITLE
WRAPPED_PUPable_decl_* docs refer to (non-)class classes

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#833]
WRAPPED_PUPable_decl_template: "Any class that derives off of a non-class template base class..."
WRAPPED_PUPable_decl_base_template: "Any class that derives off of a class template base class..."

I don't know what these are trying to say, but neither a "class class" nor a "non-class class" make any sense to me.

**Comment by nilsdeppe** [comment]
A "non-class template" base class. As in a class that does not have template parameters. I think it would be clearer to have them omit the first "class" and just be "non-template base class" and "template base class", but I'll let you decide what is best since clearly I failed at that :)

**Comment by kidder** [comment]
@wthrowe can you discuss this with @nilsdeppe in person so he knows how to fix the documentation.

**Comment by nilsdeppe** [comment]
I think this was fixed at some point. @wthrowe can you close this if you're happy with the current wording in the code?

**Comment by wthrowe** [comment]
Yes, this is fixed.
