### ISSUE TITLE
Add Spectral Functions to Doxygen Group

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#835]
# Feature request:

### Component:

- [ ] Code
- [x] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

Not all (any?) of the spectral functions are in a Doxygen group. We need to decide which group, be it an existing one or a new one.

**Comment by nilsvu** [comment]
There is a [`Spectral` group](https://spectre-code.org/group__spectralgroup) that contains the namespace and the enums. It's a bit redundant with the [`Spectral` namespace documentation](https://spectre-code.org/namespacespectral) though. The latter has a complete list of the available functionality. Any suggestions on how to improve the situation?

**Comment by nilsdeppe** [comment]
I guess that depends on whether we plan on having multiple namespaces for spectral things. A lot of the namespace documentation is redundant with groups, but that's because we want to have everything of interest show up with the groups. @kidder should we have everything be in the group? I don't think we'll have so much spectral functions that it'll need separate namespaces in the documentation to organize

**Comment by kidder** [comment]
I am happy to have things be in groups.  I am not a fan of having things be in namespaces unless there is a clear benefit to doing so.  Is there a point to having a namespace if the group and namespace are equivalent?

**Comment by nilsdeppe** [comment]
Not quite. So in quite a few places we use groups that hold things in a namespace. The group can also have things not in the namespace, and also shows up differently. I personally find the groups better because it allows us to put things together logically for documentation rather than for code. For example, the domain namespace and computationaldomaingroup dox group overlap almost entirely

**Comment by kidder** [comment]
@nilsdeppe is happy with the current status
