### ISSUE TITLE
Move specific analytic solutions to system directory

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#837]
For analytic solutions that are directly associated with a particular system, i.e. include and work with its tags, it might make more sense to keep the implementation in a `Solutions` directory with the `System.hpp` and `Tags.hpp` as opposed to `PointwiseFunctions`. I suggest the following moves:

- `PointwiseFunctions/AnalyticSolutions/Burgers/` -> `Evolution/Systems/Burgers/Solutions/`
- `PointwiseFunctions/AnalyticSolutions/WaveEquation/` -> `Evolution/Systems/ScalarWave/Solutions/`

**Comment by kidder** [comment]
In the old Bitbucket repo we stored all solutions with their systems but we found it useful to use solutions in other cases besides evolving its associated system.  Therefore we made a conscious decision to change to the present setup.  I don't see any benefit in moving some solutions, as this means more places to search for them, and then having to decide whether a new one belongs with the system or in PointwiseFunctions.

**Comment by nilsvu** [comment]
👍 Just to clarify, what would be examples of other use cases?

Feel free to close, unless anyone has more to discuss.

**Comment by kidder** [comment]
Examples: using an Einstein solution as a background for a relativistic system, using a non-relativistic solution to the wave equation as a solution to the relativistic wave equation on a Minkowski background, initializing a relativistic wave equation evolution with the flat-space wave equation solution evaluated at a particular time...

**Comment by nilsvu** [comment]
I guess we'll have to get rid of the dependence on the system tags then, but that's another issue. Thanks for clarifying 👍
