### ISSUE TITLE
Add compute item argument tags to databox automatically

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#847]
# Feature request:

When a compute item is added to the databox, can we make it automatically add missing argument tags that are themselves compute items?

Right now we build the dependency graph manually, i.e. add all simple items and compute items one by one in the initialization. Many of these tags are never used explicitly but are only needed as arguments for other compute items. Examples are the mesh on element faces, the unnormalized face normals or the inverse jacobian (and many others). Recursively adding these to the databox automatically when they are needed would make the initialization a lot less verbose and would relieve the programmer from keeping track of all dependencies manually (which I found a common source of error that comes with long compiler backtraces).

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

**Comment by nilsvu** [comment]
E.g. it would be very useful if I could just add a `Tags::FaceNormal<EuclideanMagnitude>` compute item to the databox, as opposed to adding first the unnormalized face normal, its magnitude, the mesh and then the normalized face normal tags.

**Comment by kidder** [comment]
Sure this would be nice, but it is not simple.  How do you know which of the argument tags are compute items, and even for dependent compute items how do you know what they depended on?  E.g. your system is not Euclidean, therefore your normal depends upon the spatial metric. How do you know if the spatial metric is specified as a background from an analytic solution, or should it be computed from the evolved spacetime metric, or is the spatial metric itself an evolved variable?

**Comment by nilsdeppe** [comment]
As Larry pointed out, this is not possible to do (the compiler would have to literally read your mind...).
