### ISSUE TITLE
Document OrientationMap direction better

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#856]
The documentation for things using OrientationMaps is vague and sometimes seemingly self-contradictory about which direction the OrientationMap maps.  Neighbors and BlockNeighbor both just call it "the OrientationMap of the neighbor(s)" which does not suggest either direction to me.  The OrientationMap tutorial states that it is the orientation of the block with respect to the neighbor, but then goes on to say that it maps to the neighbor from the block, which seems contradictory.  I assume the last of these (block to neighbor) is correct, because it is the most explicit statement, but the documentation should make this clear.

**Comment by kidder** [comment]
The OrientationMap that is held by the Neighbors and BlockNeighbor is supposed to (based on how I defined it originally and am assuming still does, but haven't checked) map things in the Block/Element  to what they would be in the BlockNeighbor/Neighbor.   That is if `me` is an Element and `neighbor` is its neighbor in `direction_to_neighbor`, then calling `me.neighbors().at(direction_to_neighbor).orientation()(something)` should take the dimension/direction/SegmentId in the logical coordinate frame associated with `me`, and return the corresponding dimension/direction/SegmentId in the logical coordinate frame associated with `neighbor`

**Comment by mar-celine** [comment]
I agree the documentation in Neighbors.hpp and BlockNeighbors.hpp needs to be fixed. As far as I know, OrientationMaps are always from the perspective of the highest-level object in which they are contained. That is, if an Object Self contains a (Block)Neighbors which itself holds an OrientationMap, this OrientationMap is from the perspective of the Self. I am not aware of any situations in the code in which a Self object (or any of its members) holds the OrientationMaps that are from the perspective of the Neighbor. @kidder's interpretation is correct.

**Comment by kidder** [comment]
@gsb76 is this being done, done, or going to be done?
