### ISSUE TITLE
Print Tag::name() in Variables for Databox tags

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#864]
# Bug reports:

### Expected behavior:

The `Variables::operator<<` should print the `Tag::name()` if `db::is_tag_v<Tag>`.

### Current behavior:

It currently always prints the `pretty_type::short_name<Tag>()`. For prefixed databox tags this results in the type name of the outermost prefix, e.g. `"Next: ..."` for `Tags::Next<SomeTag>` so `SomeTag` is ignored.

### Detailed discussion:

We could fix this by specialising `pretty_type::short_name` for databox tags, or by specialising the `Variables_detail::print_helper`. Which way should we go?

**Comment by nilsdeppe** [comment]
I think the `operator<<` should be changed, not `pretty_type`.

**Comment by nilsdeppe** [comment]
Tag name is now printedd via `db::tag_name`
