### ISSUE TITLE
Add ASSERT to dg::mortar_mesh

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#869]
# Bug reports:

An `ASSERT` should check that the input is only LGL.

**Comment by nilsdeppe** [comment]
@nilsleiffischer would you mind doing this so @wthrowe can focus on the other accretion disk things?

**Comment by nilsvu** [comment]
Sure I'll wait for #852 to get merged

**Comment by nilsdeppe** [comment]
@nilsleiffischer ping on this issue.

**Comment by kidder** [comment]
@nilsleiffischer ping on this issue.
