### ISSUE TITLE
Combine Similar Tests into Single Case

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#877]
# Bug reports:

After #794 is merged BulgedCube will have 3 short tests. We can reduce our test runtime be making these one test that calls all 3. This same thing should be applied throughout CoordinateMaps (and the entire code base, but that's on other people), but before doing this please wait for #814

**Comment by fmahebert** [comment]
> We can reduce our test runtime be making these one test that calls all 3.

Is the underlying issue here that starting each TEST_CASE has substantial overhead?

**Comment by nilsdeppe** [comment]
Yes, especially on some supercomputers. On wheeler I believe it's close to 1 second.

**Comment by mar-celine** [comment]
This was addressed in #1356
