### ISSUE TITLE
Docker make test-executables hangs on >2 processors

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#886]
# Bug reports:

### Expected behavior:

On a 4-core MacBook Pro with hyper threading (so 8 cores available for make), in Docker, after configuring for a clang build, running make -j8 test-executables in docker succeeds, and running make -j4 test-executables in docker succeeds.

### Current behavior:

make -j2 test-executables succeeds, but make -j4 test-executables hangs, as does make -j8 test-executables.

### Environment:

CMake Version: 3.9.1
SpECTRE Version: 0.0.0
SpECTRE branch: StrahlkorperSpinDirection
SpECTRE hash: e6ebf2d819084581dd0a9ed56f322e47baf5586f
Hostname: 5ccedf8e71c7
Host system: Linux-4.9.93-linuxkit-aufs
Host system version: 4.9.93-linuxkit-aufs
Host system processor: x86_64
CMAKE_CXX_FLAGS: 
CMAKE_CXX_LINK_FLAGS: 
CMAKE_CXX_FLAGS_DEBUG: -g
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: 
CMAKE_C_LINK_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: 
CMAKE_Fortran_LINK_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: 
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/local/bin/clang++
CMAKE_CXX_COMPILER_VERSION: 5.0.0
CMAKE_C_COMPILER: /usr/local/bin/clang
CMAKE_C_COMPILER_VERSION: 5.0.0
CMAKE_Fortran_COMPILER: /usr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 7.2.0
Python Version: 2.7.14
Charm Version:  6.8.0
BLAS_LIBRARIES:  /usr/lib/x86_64-linux-gnu/libopenblas.so
Blaze Version:  3.2
Boost Version:  1.62.0
Catch Version:  2.1.0
Google Benchmark Found
GSL Version:  2.4
HDF5 Version:  1.10.0.1
jemalloc Version:  ..
LIBXSMM Version:  1.8.1
LAPACK_LIBRARIES:  /usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so
NumPy Version:  1.14.2

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by kidder** [comment]
@geoffrey4444 you most likely ran out of memory

**Comment by kidder** [comment]
it should probably be documented that compiling executables is memory intensive

**Comment by geoffrey4444** [comment]
Didn’t realize I would run out with 16GB RAM...thanks!

**Comment by wthrowe** [comment]
Docker is probably limiting the memory available inside the container.  There is presumably some way to increase that, and we may want to mention it in our docs.

With a rough measurement I find that clang-6.0 uses about 1.25 GB to compile EvolveBurgers.cpp, and that is the most memory-intensive step in the sequence.

**Comment by nilsdeppe** [comment]
Since Docker on macOS runs in a VM you should check what the VM limits are. Likely somewhere between 2 and 4GB. @geoffrey4444 can you check this?

**Comment by geoffrey4444** [comment]
It's configurable. On the docker menubar item, choose Preferences... Then, under "Advanced" you can set the CPU, memory, and swap limits. You can raise them as high as whatever is available on your system. Currently, I have it set to use 4 cpus (I have 4 physical cores but 8 with hyper-threading) and 14GB of RAM (out of my 16GB). This lets me use more cores to compile the test-executables.

**Comment by nilsdeppe** [comment]
@geoffrey4444  I'm unclear if your reply means "Changing the settings fixed this issue." or "These are my settings and I'm still unable to compile with more than two cores." Could you clarify?

**Comment by geoffrey4444** [comment]
Adding more RAM let me use more, but not all, cores to build the test executables. So I guess that’s enough to close the issue?

**Comment by nilsdeppe** [comment]
I would say yes. It sounds like the issue is related to hardware constraints, not anything we can actually change. The only thing that might be worth doing is adding a note in the installation section for macOS users to be aware of this.
