### ISSUE TITLE
Admit primal flux lifting in the communication code

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#897]
# Feature request:

Currently the flux communication code assumes we always want the $n \cdot F$ and the $n \cdot F^\star$ on the interface boundaries. This is because these are needed by (what I will call) the _strong first-order_ flux lifting $\int_{\partial e} (F - F^*) \cdot dn$ that arises from first-order formulations of PDEs. These first-order formulations typically double (1D), triple (2D) or quadruple (3D) the number of dynamic degrees of freedom since they introduce auxiliary variables. We can get rid of them in the _primal_ formulation, significantly improving performance, at least for the elliptic systems I have investigated so far. The same should hold for evolution systems, at least those that are second order in space. Since the auxiliary variables are eliminated, the code for volume contributions simplify but doesn’t need architectural changes. However, the flux-lifting does need another implementation.

- [ ] TODO: Detail the needed changes
- [ ] TODO: Upload the PDF with math

What is certainly needed for this is to remove the assumption of strong first-order flux lifting from the communication code.

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by nilsdeppe** [comment]
Is this still relevant?

**Comment by nilsvu** [comment]
This is fixed. We ended up separating the elliptic and hyperbolic DG code, and I eliminated auxiliary DOFs from the first-order elliptic formulation with a Schur complement approach (see elliptic DG docs).
