### ISSUE TITLE
is_ready deadlocks are treated as successful termination

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#907]
Currently if all elements deadlock because an action `is_ready` function is waiting for data that will never be sent, charm detects that nothing is happening and terminates successfully.  I'm not sure how feasible it is to detect this, but it should be an error.

**Comment by nilsdeppe** [comment]
Just to make sure I understand exactly what you're saying, all elements are waiting to receive data but nothing is sending it. As a result the code notices `Nothing is happening, we can terminate` but does not report it as an error.

If that's what you mean then I agree it would be nice to detect that, and that I'm also not sure right now how feasible it would be to detect.

**Comment by wthrowe** [comment]
Yes, that is what I meant.

**Comment by kidder** [comment]
We could have "correct" termination conditions communicate with the main chare and have Exit check for such a communication having occurred.

**Comment by nilsdeppe** [comment]
What @wthrowe and I discussed was having the code optionally run a simple action on some (or all) of the components, which then do a reduction with a message saying why they failed (or `"success"` if successful). We can then print these messages (minimally, eg `"Failed because is_ready is waiting on data for IDs [..........]"`), and either exit with 0 or not 0 accordingly.

**Comment by kidder** [comment]
so, what, you call each component, check `terminate_` and if it is not true, somehow dump why all the `is_ready` functions that return false are not ready?

**Comment by nilsdeppe** [comment]
Yes, but I think that's basically the idea.

**Comment by kidder** [comment]
related to #1570

**Comment by nilsdeppe** [comment]
@wthrowe I think this is fixed with #4236 right?

**Comment by wthrowe** [comment]
Yes.
