### ISSUE TITLE
Add gdb to Docker container

### ISSUE THREAD

**Issue by moxcodes** [sxs-collaboration/spectre#931]
# Feature request:

gdb inclusion in base spectre container for debugging.

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

**Comment by geoffrey4444** [comment]
Until this is added to the spectre docker container, you can use `apt-get update; apt-get install gdb` to get gdb. But I got permission errors running gdb (and perf, which I also installed) unless I added the flags `--cap-add sys_admin --cap-add=SYS_PTRACE` to my `docker run` command when I create my spectre docker container.

**Comment by geoffrey4444** [comment]
Did you also install perf? If not, I'll open another issue for that.

**Comment by nilsdeppe** [comment]
No I did not and it also shouldn't be installed in the container. perf is Linux kernel version dependent and so should not be installed in a container since the host's kernel is used and outside of the control of the container.
