### ISSUE TITLE
We should warn about unknown `[[Tags]]` on tests

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#94]
Currently they are ignored and all the used ones are optional, so there's no protection against typos or missed updates from the old code.

**Comment by nilsdeppe** [comment]
I completely agree, only thing to decide is where we should have the list of tags we want to accept? Easiest is probably having the python file that already checks for timeouts do the work.

**Comment by nilsdeppe** [comment]
This is fixed in #177

**Comment by wthrowe** [comment]
Not fixed.  Please reopen.

**Comment by nilsdeppe** [comment]
Not a helpful comment. I need an example that fails to test against.

**Comment by nilsdeppe** [comment]
Summary of in-person discussion:

Will tag: `[[ TAG ]] TEST_CASE(...)`

Nils tag: `[[ ATTRIBUTE ]] TEST_CASE("blah", "[TAG]")`
