### ISSUE TITLE
Distinguish between User Tutorials and Dev Guides in documentation

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#945]
# Feature request:

We should have a clear distinction between [User Tutorials](https://spectre-code.org/tutorials.html) and [Dev Guides](https://spectre-code.org/dev_guide.html) in our documentation, or rename/restructure those parts if there is no clear distinction. The [front page of the documentation](https://spectre-code.org) currently defines them as follows (disclaimer: I wrote it):

- If you are looking to **run simulations with SpECTRE** we recommend starting with the [User Tutorials](https://spectre-code.org/tutorials.html). The tutorials are designed to get users up and running with a simulation, as well as analyzing and visualizing the output.
- For people looking to **contribute to SpECTRE** there are tutorials on the [Dev Guide](https://spectre-code.org/dev_guide.html) page. For instance, the dev guide details the code review guidelines, how to write unit tests, how to write documentation, and also provides information about C++ and the philosophy behind SpECTRE development.

I am opening this issue for discussion in response to #944 where User Tutorials and Dev Guides are referenced. According to the definition above, all proposed additions to the documentation in #944 should be Dev Guides. This issue can be closed straight away if people agree with that. Both the existing User Tutorials and Dev Guides need updating, but that's another issue and can be postponed.

### Component:

- [x] Documentation

**Comment by nilsdeppe** [comment]
In the future, please just comment on the issue if you have an issue with the issue.

**Comment by nilsvu** [comment]
Am I to understand this reaction as agreement?

I opened this separately to not distract from the other issue..

Also, how is this invalid?..
