### ISSUE TITLE
Discussion about Analytic Solutions

### ISSUE THREAD

**Issue by mar-celine** [sxs-collaboration/spectre#946]
# Feature request:

Currently some analytic solutions such as [Isentropic Vortex](https://spectre-code.org/classnewtonianeuler_1_1solutions_1_1isentropicvortex) return both
the conserved variables and the primitive variables. This also assumes an equation of state.
I think it is worth discussing whether this is the way other systems should be written.
It might be the case that we will only want to return primitive variables without assuming
an equation of state.

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by kidder** [comment]
You need to specify an equation of state (and in GR(M)HD a background spacetime) to specify the problem so you can determine if you have analytic solution.

As computing the conservative variables is an algebraic operation on the primitive variables, I could easily be persuaded to have the AnalyticSolutions (and future AnalyticData) only return the primitives.

The analytic solutions, however, should expose somewhere what equation of state and background metric they use.  And we need to have some way of either checking (or specifying) these so they are consistent with any input file options

**Comment by kidder** [comment]
We decided to only provide the primitives as the conservatives can be cheaply computed from them.
They should also expose the EoS and background metric used
