### ISSUE TITLE
Upgrade Blaze version

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#948]
# Feature request:

[Blaze](https://bitbucket.org/blaze-lib/blaze/) added support for [element selections](https://bitbucket.org/blaze-lib/blaze/wiki/Element%20Selections) in v3.3, which can be very useful (e.g. for #919). They also addressed https://bitbucket.org/blaze-lib/blaze/issues/166/allow-tagging-blaze-expressions in v3.4 which is relevant for us:

- https://bitbucket.org/blaze-lib/blaze/wiki/Release%20Archive

**Comment by moxcodes** [comment]
Also, if we can enforce blaze 3.4, we can simplify a lot of compatibility code in our vector types.

**Comment by kidder** [comment]
Currently stampede2 can only handle blaze 3.2

**Comment by nilsdeppe** [comment]
We use 3.8 now.
