### ISSUE TITLE
IWYU suggests "#include <math.h>"

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#952]
# Bug reports:

### Expected behavior:

When using something like `sqrt(4.0)`, include what you use should suggest `#include <cmath>`.

### Current behavior:

When this just came up for me, IWYU suggested `#include <math.h>`, which then led to clang-tidy telling me to include `#include <cmath>` instead. Not a big deal, but would be nice if IWYU just gave the best suggested fix in this case.

### Environment:

Standard Docker container.

# Feature request:

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### Desired feature:

- [ ] Detail 1
- [ ] Detail 2
- [ ] Detail 3

**Comment by kidder** [comment]
We have no control over what IWYU does.  If you want, file an issue with them

**Comment by geoffrey4444** [comment]
Thanks, @kidder.
