### ISSUE TITLE
Tests sometimes time out

### ISSUE THREAD

**Issue by fmahebert** [sxs-collaboration/spectre#96]
The SpECTRE tests have sometimes been timing out on Travis and (until recently) on my workstation as well. The changes in #89 worked around this issue by increasing the allowed duration of each test, but the underlying problem is still not understood.

I am making this issue so we keep awareness of this problem. A satisfactory resolution would involve understanding why tests sometimes time out and hopefully avoiding the workaround of #89.

Some further details given below:

---

On July 3rd, @nilsdeppe and I discussed the tests occasionally timing out on Travis and my workstation. Some experiments on my workstation suggested:
* the timeout affects, on average, roughly 1 test other every time all tests are run (at the time there were ~100 tests)
* there is no obvious pattern indicating which tests time out vs. which tests do not

Since then I have done a Linux update on my workstation and I no longer see any tests timing out, suggesting a possible link to low-level libraries or perhaps the kernel.

**Comment by nilsdeppe** [comment]
This issue seems to be resolved with kernel updates and increasing the timeout. We haven't seen this issue in a long time on Travis. I'm closing it as "fixed" until the issue shows up again.
