### ISSUE TITLE
Rename Solutions dirs and gr files

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#981]
# Bug reports:

Directories:
- `EinsteinSolutions` -> `Einstein`
- `NewtonianEulerSolutions` -> `NewtonianEuler`

Files:
- `PointwiseFunctions/GeneralRelativity/GrTags(Declarations).hpp` can just be `PointwiseFunctions/GeneralRelativity/Tags(Declarations).hpp`

**Comment by kidder** [comment]
Fixed in #990
