### ISSUE TITLE
Write NodeLock class

### ISSUE THREAD

**Issue by nilsdeppe** [sxs-collaboration/spectre#998]
# Feature request:

### Component:

- [x] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Desired feature:

Having a `Parallel::NodeLock` class that wraps Charm++'s `CmiNodeLock` (which is a `void*`). We can then document the correct copy and move semantics, etc. and also have it be strongly typed.

**Comment by moxcodes** [comment]
We can probably close this yea?

**Comment by nilsdeppe** [comment]
I agree :)
